### PR TITLE
Solr

### PR DESCRIPTION
**Pull request by julie-sullivan**
## Details

Merged in @arunans23's branch and the dev branch. 

## Testing

Ran on flymine-beta and locally. Will try on humanmine and sergio will test on thalemine.

## Checklist

Before your pull request can be approved, be sure to check all boxes:

- [ ] Passing unit test for new or updated code (if applicable)
- [ ] Passes all tests – according to Travis
- [ ] Documentation (if applicable)
- [ ] Single purpose
- [ ] Detailed commit messages
- [ ] Well commented code
- [ ] Checkstyle

### CODE REVIEW

**Comment by julie-sullivan** [comment]
Tests fail locally too, but not in intellij.

```
org.intermine.bio.ontology.SequenceOntologyTest > testGetAllClasses FAILED
    java.lang.RuntimeException at SequenceOntologyTest.java:41
        Caused by: java.io.FileNotFoundException at SequenceOntologyTest.java:41

org.intermine.bio.ontology.SequenceOntologyTest > testNoFile FAILED
    java.lang.RuntimeException at SequenceOntologyTest.java:50
        Caused by: java.io.FileNotFoundException at SequenceOntologyTest.java:50

org.intermine.bio.ontology.SequenceOntologyTest > testParents FAILED
    java.lang.RuntimeException at SequenceOntologyTest.java:62
        Caused by: java.io.FileNotFoundException at SequenceOntologyTest.java:62

```

**Comment by julie-sullivan** [comment]
@arunans23 and @danielabutano Can you read over this really quick:

https://intermine.readthedocs.io/en/latest/system-requirements/software/solr/

I just copied and pasted from your beautiful google doc. Make sure I haven't made any copy/paste errors! :) I'll ask @sergiocontrino to use these docs to test too.

**Comment by julie-sullivan** [comment]
`java.lang.RuntimeException: Couldn't find obo file: '/tmp/so-obo1696604295664466044.tmp'` <-- this file is there.

But if you look at the end of the stacktrace, this is the actual problem:

```
Caused by: java.io.FileNotFoundException: /local-data/git/intermine/bio/build/obo5089388558916714736.tmp (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at org.intermine.bio.ontology.OboParser.processRelations(OboParser.java:146)
	at org.intermine.bio.ontology.SequenceOntology.process(SequenceOntology.java:737)
	... 46 more
```

That file is NOT there.

**Comment by julie-sullivan** [comment]
```
        File f = new File("build");
        if (!f.exists()) {
            temp = File.createTempFile("obo", ".tmp");
        } else {
            temp = File.createTempFile("obo", ".tmp", f);
        }
```

The `/build` directory is set by us. I don't know why it fails though.

**Comment by julie-sullivan** [comment]
Now fails with another weird error:

```
Caused by: java.nio.file.NoSuchFileException: build/je.info.0.lck
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at java.util.logging.FileHandler.openFiles(FileHandler.java:459)
	at java.util.logging.FileHandler.<init>(FileHandler.java:402)
	at com.sleepycat.je.util.FileHandler.<init>(FileHandler.java:55)
	at com.sleepycat.je.dbi.EnvironmentImpl.initFileHandler(EnvironmentImpl.java:1276)
	... 50 more
```
Same issue I expect? Probably looking for `build` directory which is the `ant` style of doing things. Will fix.

**Comment by julie-sullivan** [comment]
@danielabutano @arunans23 Since you are the Solr experts, I was wondering if you could answer a question for me. I was hoping this issue would just magically go away with Solr. Not so!

Eight results:
http://beta.flymine.org/beta/keywordSearchResults.do?searchTerm=heterotaxy*&searchBag=&facet_Category=Disease

No results:
http://beta.flymine.org/beta/keywordSearchResults.do?searchTerm=heterotaxy&searchBag=&facet_Category=Disease

That's because the actual search item is named  `HETEROTAXY, VISCERAL, 1, X-LINKED`. The comma is the problem. We can't really ignore punctuation, from #1464, because punctuation, like dashes, e.g. ZDB-GENE-990415-8 or colons, e.g. GO:0021912, mean something.

Any ideas for solutions?

We had this issue for the Lucene search.

**Comment by danielabutano** [comment]
Julie I can not run the test locally, but for me it's ok to merge your solr branch into gradle-search

**Comment by arunans23** [comment]
> @arunans23 and @danielabutano Can you read over this really quick:
> 
> * [How to install SOLR](https://intermine.readthedocs.io/en/latest/system-requirements/software/solr/)
> * [How to configure search results](https://intermine.readthedocs.io/en/latest/webapp/keyword-search/)
> 
> I just copied and pasted from your beautiful google doc. Make sure I haven't made any copy/paste errors! :) I'll ask @sergiocontrino to use these docs to test too.

@julie-sullivan There is another configuration that you can pass in keyword_search.properties. `index.optimize = true`
I have explained about this in the detailed technical doc.

> Optimizing the solr index
> 
> There is an option in solr to optimize the index at the end of the index process. This is similar to defragmentation of a hard disk. It will take the index and reorganise it so that the chunks are placed together in the storage which might improve the search time. But this process requires an empty space in the storage which is same as the index and also takes additional time. You can enable/disable this option through a flag set in keyword_search.properties file.

The default value is false here. @danielabutano  Do we need to document this? This was not added in the setup document because this pull request was made later.

**Comment by danielabutano** [comment]
Thank you @arunans23 . I had forgotten it. yes, I think we need to add it.

**Comment by arunans23** [comment]
> @danielabutano @arunans23 Since you are the Solr experts, I was wondering if you could answer a question for me. I was hoping this issue would just magically go away with Solr. Not so!
> 
> Eight results:
> http://beta.flymine.org/beta/keywordSearchResults.do?searchTerm=heterotaxy*&searchBag=&facet_Category=Disease
> 
> No results:
> http://beta.flymine.org/beta/keywordSearchResults.do?searchTerm=heterotaxy&searchBag=&facet_Category=Disease
> 
> That's because the actual search item is named `HETEROTAXY, VISCERAL, 1, X-LINKED`. The comma is the problem. We can't really ignore punctuation, from #1464, because punctuation, like dashes, e.g. ZDB-GENE-990415-8 or colons, e.g. GO:0021912, mean something.
> 
> Any ideas for solutions?
> 
> We had this issue for the Lucene search.

In Solr, when I was creating the [Field Type definitions](https://github.com/intermine/intermine/blob/gradle-search/intermine/api/src/main/java/org/intermine/api/searchengine/solr/SolrIndexHandler.java#L267), I replicated the same approach as that was in Lucene. First I used a Whitespace Tokenizer to split them on white spaces and used a Lowercase Filter to make them case in-dependable.

Solr provides different kinds of [Tokenizers](https://lucene.apache.org/solr/guide/7_2/tokenizers.html) . But each of them would change the search results in a huge manner and we don't know which is right. Earlier I was using StandardTokenizer which would split words "-" and all. That returned some weird search results since most of the biodata have hyphen in them. 

I'll continue to look for whether there is a better tokenizer for biodata or whether we can create our own tokenizer thorugh code.

**Comment by julie-sullivan** [comment]
Thanks! I've added `index.optimize` to the docs! 

Thanks for that, that's helpful. We had the exact same issue with the tokenisers with Lucene. Will take some thought! 

You know, just thinking on this now, maybe the solution is to make the _data_ better. e.g. for the OMIM example I gave you, what if in the parser I split by comma and made synonyms. That would solve this problem but would not solve others. What other use cases are there? Maybe none! Might be a good thing to talk with the group about.

**Comment by julie-sullivan** [comment]
@arunans23 I just read through all the tokenisers and filters and don't see what we need.

**ignore all punctuation (whitespace tokeniser does this)**

We have meaningful punctuation, e.g. `ZDB-GENE-990415-8` and `GO:0021912`, so need to keep except ...

**EXCEPT COMMAS (standard tokeniser does this)**

Except for commas, we need to discard those, e.g. `Heterotaxy, visceral, 4, autosomal`

With PatternTokenizerFactory or the regex tokeniser we can specify the tokens but I don't want to have to specify which are valid and which are not. I just want what the whitespace tokeniser does, plus splitting on commas.

Maybe we can [copy](https://wiki.apache.org/solr/SchemaXml#Indexing_same_data_in_multiple_fields) ? So use two tokenisers? 

`Heterotaxy, visceral, 4, autosomal` would still be in the index but so would `Heterotaxy`, `visceral`, `4`, and `autosomal`

**Comment by julie-sullivan** [comment]
@arunans23 I just read through all the tokenisers and filters and don't see what we need.

**ignore all punctuation (whitespace tokeniser does this)**

We have meaningful punctuation, e.g. `ZDB-GENE-990415-8` and `GO:0021912`, so need to keep except ...

**EXCEPT COMMAS (standard tokeniser does this)**

Except for commas, we need to discard those, e.g. `Heterotaxy, visceral, 4, autosomal`

With PatternTokenizerFactory or the regex tokeniser we can specify the tokens but I don't want to have to specify which are valid and which are not. I just want what the whitespace tokeniser does, plus splitting on commas.

Maybe we can [copy](https://wiki.apache.org/solr/SchemaXml#Indexing_same_data_in_multiple_fields) ? So use two tokenisers? 

`Heterotaxy, visceral, 4, autosomal` would still be in the index but so would `Heterotaxy`, `visceral`, `4`, and `autosomal`

**Comment by julie-sullivan** [comment]
@arunans23 I just read through all the tokenisers and filters and don't see what we need.

**ignore all punctuation (whitespace tokeniser does this)**

We have meaningful punctuation, e.g. `ZDB-GENE-990415-8` and `GO:0021912`, so need to keep except ...

**EXCEPT COMMAS (standard tokeniser does this)**

Except for commas, we need to discard those, e.g. `Heterotaxy, visceral, 4, autosomal`

With PatternTokenizerFactory or the regex tokeniser we can specify the tokens but I don't want to have to specify which are valid and which are not. I just want what the whitespace tokeniser does, plus splitting on commas.

Maybe we can [copy](https://wiki.apache.org/solr/SchemaXml#Indexing_same_data_in_multiple_fields) ? So use two tokenisers? 

`Heterotaxy, visceral, 4, autosomal` would still be in the index but so would `Heterotaxy`, `visceral`, `4`, and `autosomal`

**Pull request merged**
