### PR TITLE
Run fewer analyses during dataloading

### PR DESCRIPTION
**Pull request by rnsmith**
Avoid running slow an unnecessary ANALYSEs on database tables during dataloading. This change both reduces the frequency of ANALYSEs and for data loading provides a list of tables on which primary key queries are run - these are the only tables that will be analysed.

### CODE REVIEW

**Comment by julie-sullivan** [comment]
@rnsmith has a script that parses the log files to see how long each source analysed for.

I am going to keep the logs for the current flymine build, then run another build with on this branch and compare the two.

**Comment by julie-sullivan** [comment]
```
Wed Jul  1 18:44:14 BST 2015

starting command: ant -v -Dsource=fly-fish


BUILD FAILED
/data/code/intermine/imbuild/integrate.xml:54: The following error occurred while executing this line:
/data/code/intermine/imbuild/source.xml:330: java.lang.NullPointerException
        at org.intermine.sql.DatabaseUtil.getTableName(DatabaseUtil.java:608)
        at org.intermine.dataloader.DataLoaderHelper.getPrimaryKeyTableNames(DataLoaderHelper.java:334)
        at org.intermine.dataloader.ObjectStoreDataLoader.process(ObjectStoreDataLoader.java:95)
        at org.intermine.dataloader.ObjectStoreDataLoader.process(ObjectStoreDataLoader.java:63)
        at org.intermine.dataloader.ObjectStoreDataLoaderTask.execute(ObjectStoreDataLoaderTask.java:128)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)

```

**Comment by rnsmith** [comment]
In 9f7c74b fix exception loading `fly-fish` by removing invalid key, improved error reporting.

**Comment by julie-sullivan** [comment]
@rnsmith Thanks, I've updated and restarted the build.

**Comment by rnsmith** [comment]
I've compared the load performance of FlyMine builds with and without this change - there's no significant difference either way. However, FlyMine never had a problem with ANALYSEs taking a long time.

I've actually commented out in `ObjectStoreDataLoader` the change that only ANALYSEs tables that have an integration key for the source being loaded. The load process actually does DELETEs on a lot more tables (I'm not sure why) and it may be they would slow down without ANALYSEing the tables. It may be better to keep ANALYSEs on all tables, just less frequent.

**Comment by julie-sullivan** [comment]
@rnsmith Maybe I should test on a humanmine build? Or are you happy with this change?

What should I be testing? Just the speed. Is this something that @JoeCarlson would be able to test better than me?

**Comment by julie-sullivan** [comment]
Checkstyle error

```
BUILD SUCCESSFUL

Total time: 15 seconds

FILE: /home/travis/build/intermine/intermine/intermine/integrate/main/src/org/intermine/dataloader/ObjectStoreDataLoader.java

  line:   15, column:   8 - warning - Unused import - java.util.Set.

  line:   25, column:   8 - warning - Unused import - org.intermine.objectstore.intermine.ObjectStoreWriterInterMineImpl.

  line:   29, column:   8 - warning - Unused import - org.intermine.sql.writebatch.BatchWriterPostgresCopyImpl.
```

**Comment by julie-sullivan** [comment]
We could make this an "analyse less" mode and let people set config to get this functionality.

**Comment by julie-sullivan** [comment]
Needs docs too.

**Comment by rnsmith** [comment]
Julie to test again with humanmine builds with and without this change and compare performance. If it is as fast or faster when analysing fewer tables we can keep the change.

**Comment by rnsmith** [comment]
c007a6a6cafb7dc4678693152fa6cf7477921e28 is the optional change set.

**Comment by julie-sullivan** [comment]
It looks like the build is a little bit slower. The individual sources are a bit faster though, so may be worth merging after all?

Build on `rnsmith:analyse-freq`

```
action name                                   time in seconds
-------------------------------------------------------------
ensembl-snp                                            33569
ensembl-snp-dump                                        1065
ensembl-human                                           1587
ensembl-human-chr-fasta                                  357
human-gene                                               188
ncbi-summaries                                            59
ncbi-summaries-dump                                     1535
pubmed-gene                                              203
mgi-identifiers                                           99
ensembl-mouse-chr-fasta                                  317
mgi-alleles                                              101
mgi-alleles-dump                                        1917
rgd-identifiers                                           85
so                                                        58
arrayexpress-atlas                                      1989
protein-atlas                                            270
uniprot                                                  501
uniprot-keywords                                          56
interpro                                                 103
psi-mi-ontology                                           51
mammalian-phenotype-ontology                             108
go                                                       535
go-annotation                                            414
omim                                                      55
hpo                                                       82
hpo-annotation                                           120
hpo-annotation-dump                                     1971
psi-intact                                               371
biogrid                                                  123
kegg-pathway                                              65
reactome                                                  68
panther                                                 3238
huge-gwas                                                 75
update-publications                                     3767
update-data-sources                                       47
entrez-organism                                           41
create-references                                        185
transfer-sequences                                     13008
transfer-sequences-dump                                 2343
do-sources                                              1524
create-gene-flanking-features                            179
create-bioseg-location-index                            1185
create-overlap-view                                       20
create-attribute-indexes                                7302
summarise-objectstore                                   7040
create-autocomplete-index                                 75
create-search-index                                    10575
final-dump                                              9201

total                                                 107827
```

build on the beta branch:

```
action name                                   time in seconds
-------------------------------------------------------------
ensembl-snp                                            34796
ensembl-snp-dump                                        1007
ensembl-human                                           1713
ensembl-human-chr-fasta                                  380
human-gene                                               208
ncbi-summaries                                            65
ncbi-summaries-dump                                     1284
pubmed-gene                                              215
mgi-identifiers                                          108
ensembl-mouse-chr-fasta                                  324
mgi-alleles                                              122
mgi-alleles-dump                                        1247
rgd-identifiers                                          100
so                                                        84
arrayexpress-atlas                                      2501
protein-atlas                                            279
uniprot                                                  582
uniprot-keywords                                          66
interpro                                                 105
psi-mi-ontology                                           91
mammalian-phenotype-ontology                             124
go                                                       572
go-annotation                                            442
omim                                                      78
hpo                                                       90
hpo-annotation                                           154
hpo-annotation-dump                                     1482
psi-intact                                               398
biogrid                                                  310
kegg-pathway                                              66
reactome                                                  65
panther                                                 2705
huge-gwas                                                 67
update-publications                                     3837
update-data-sources                                       42
entrez-organism                                           37
create-references                                        231
transfer-sequences                                     12808
transfer-sequences-dump                                 2017
do-sources                                              1535
create-gene-flanking-features                            199
create-bioseg-location-index                            1111
create-overlap-view                                       21
create-attribute-indexes                                7225
summarise-objectstore                                   7869
create-autocomplete-index                                 66
create-search-index                                    11031
final-dump                                              7951

total                                                 107810
```

**Comment by julie-sullivan** [comment]
Unless @JoeCarlson says this speeds up his builds, I am not going to merge this in as it doesn't seem to help us any.

**Comment by JoeCarlson** [comment]
I have not seen significant differences when changing the rate of 
analyses. We've seen significant improvement with hardware (SSD caching) 
improvements and we're happy with that.

**Pull request closed without merging**
