### PR TITLE
Links to other mines

### PR DESCRIPTION
**Pull request by danielabutano**
## Details

test link to humanmine from flymine report page (e.g. gene  MYH16)

## Testing

*Besides running unit tests, how can the reviewer test your feature / bug fix? Are there edge cases to be aware of?*

## Checklist

Before your pull request can be approved, be sure to check all boxes:

- [ ] Passing unit test for new or updated code (if applicable)
- [ ] Passes all tests – according to Travis
- [ ] Documentation (if applicable)
- [ ] Single purpose
- [ ] Detailed commit messages
- [ ] Well commented code
- [ ] Checkstyle

### CODE REVIEW

**Comment by sergiocontrino** [comment]
tested from a current flymine, all fine!

**Comment by pengchy** [comment]
Hi @danielabutano and @sergiocontrino ,
    Could you please give an example for configuring "links to other Mines in the bagDetails page" and "links to FlyMine and HumanMine in the report page".

Thank you and best!
Pengcheng

**Comment by sergiocontrino** [comment]
hi Pengcheng,
please check configurations here
https://github.com/intermine/intermine/blob/dev/intermine/webapp/src/main/webapp/WEB-INF/global.web.properties

for generic external link, configuration is in web.properties, e.g. for 
flymine
https://github.com/intermine/flymine/blob/master/webapp/src/main/webapp/WEB-INF/web.properties

if i understood correctly your question!
thanks
sergio

**Comment by pengchy** [comment]
Hi Sergio,
Thank you for your reply. I am also reading the tutorials and email archives but still don't understand some features of InterMine quite well. So I still need your help on these problems. Hope you are not scared by these many questions.

There are some problems about "links to other mines" and listed below:
1. take https://www.flymine.org/flymine/gene:FBgn0005558 this gene in FlyMine for example, which has been listed as an example in the paper (Lyne, R. et al. Genesis 53, 547-560, 2015). This gene indeed has an homologue in human (https://www.humanmine.org/humanmine/gene:5080), and vice versa. However, the "links to other Mines" in the gene report pages from both FlyMine and HumanMine don't have links to each other.

2. I have checked MouseMine, even http://www.mousemine.org/mousemine/portal.do?externalids=MGI:97490&class=Gene&origin=HumanMine this page was linked from HumanMine, the link to HumanMine of this gene in the MouseMine is still empty. And the link to FlyMine is empty too.

3. For my own Mine (for example TestMine), I have tested using FBgn ID and CG ID as primaryIdentifier, respectively, to load Fly's homologue genes, however, the link to FlyMine in the gene report page is still empty. I have used Entrez ID as primaryIdentifier for Human homologue genes, but the link to HumanMine still empty. Please take this gene for example http://insectmine.org:8080/:8080/testmine/gene:SFR20115.

4. In this link https://www.flymine.org/flymine/bagDetails.do?scope=all&bagName=esyN+demo+list, there exist an facet displaying "View homologues in other Mines:". It is very cool and useful implementation for list. I want to implement this function in my own Mine. Could you please show me where can I configurate this tool? And in this facet, the links to HumanMine still empty.

5. In this link https://www.flymine.org/flymine/bagDetails.do?scope=all&bagName=esyN+demo+list, there exist an facet displaying "Orthologues", from which we could get the homologue gene IDs of other species. However, in my own Mine, http://insectmine.org:8080/testmine/bagDetails.do?scope=all&bagName=gene.expression#, the link to other species is empty, although it displayed there exist homologue genes in other species.

I have deposited the testmine project on github https://github.com/pengchy/testmine.

Thank you sergio!

Best,
Pengcheng

**Pull request merged**
