### PR TITLE
adds handling of schema property (e.g. tripal), simplifies logs

### PR DESCRIPTION
**Pull request by sergiocontrino**
see #966 .
you need to add a line to db properties settings like:
`db.your_source.datasource.schema=your_schema`

for example
`db.tripaldbname.datasource.schema=chado`

i'll add a note here
http://intermine.readthedocs.io/en/latest/database/data-sources/library/chado/?highlight=tripal
if fine.

Note: removed classloader (very long string) info from the log about opening/closing of db connections.

### CODE REVIEW

**Comment by sergiocontrino** [comment]
@julie-sullivan, could you do a normal small build as a further test?

**Comment by julie-sullivan** [comment]
Just a normal build to make sure this parameter isn't required?

**Comment by sergiocontrino** [comment]
yes please (i have done a few, but one more from another person would be great). thanks.

**Comment by julie-sullivan** [comment]
I ran a full humanmine build without adding schema parameter and got no errors.

**Comment by sergiocontrino** [comment]
tested using redfly source.
it works fine, precedence is given as expected to the source configuration file rather than the generic one. 
please note that this local file has to be called 
red-fly_config.properties, using a different convention respect the current one (that would entail a redfly_config.properties name).

**Pull request merged**
