### PR TITLE
make the range inclusive. Refs #1108

### PR DESCRIPTION
**Pull request by julie-sullivan**

### CODE REVIEW

**Comment by julie-sullivan** [comment]
@rachellyne Can you test?

Specifically I made this change: 31763c39a3104ad79620f69bc252f11d0c3cc098

By default, the postgres index is exclusive, meaning the boundaries provided are not included in the search. Meaning if I search ranges [1,3], I get back only the value 2. NOT 1 and 3. This isn't noticeable (well, wasn't noticed by us) except in cases where feature size = 1. e.g. SNPs and point mutations.

Can you look at FlyMine and make sure that everything is as it should be.

Here is an example: 

Has overlaps
http://beta.flymine.org/beta/portal.do?class=Exon&externalids=Dere_gnomon_100_gene.13268951%3A1

No overlaps
 http://www.flymine.org/flymine/portal.do?class=Exon&externalids=Dere_gnomon_100_gene.13268951%3A1

**Comment by julie-sullivan** [comment]
@rachellyne I've redeployed humanmine-test with the fix but I can't seem to find a SNV of size 1 that has overlaps.

**Comment by julie-sullivan** [comment]
Here's a list of sequence features that have size = 1:

```
 rs190207943
 rs144023246
 rs185066721
 rs184732368
 rs113521347
 rs183827533
 rs7209929
 rs112039964
 rs367819487
 rs182692037
 rs374289282
 rs7215510
 rs147731827
 rs138910485
 rs151190301
 rs192019563
 rs376179813
 rs139016025
 rs34556017
 rs367886943
 rs78963114
 rs140659435
 rs375245594
 rs114323615
 rs372059515
 rs57094262
 rs185596020
 rs373011389
 rs191592762
 rs145699483
 rs142353813
 rs111303253
 rs191608788
 rs181693142
 rs78328777
 rs36080012
 rs11281221
 rs77507579
 rs114169207
 rs58286657
 rs192245952
 rs150838649
 rs146078319
 rs142480019
 rs377502622
```

**Comment by rachellyne** [comment]
rs113521347 has a length of 1 and should overlap gene ENSG00000227158.  It doesn't show up.  Whereas rs370938128 which has a length of 2 and also overlaps that gene does show up in overlapping features.  I don't think it's fixed.

**Comment by rachellyne** [comment]
Also not working in FlyMine even though I said it looked ok previously - I was re-running the template that was previously broken, but that point mutation has a length of 2.

**Comment by julie-sullivan** [comment]
@rachellyne Can you give a flymine example? There are overlaps in the database for features with a size of 1. This isn't the case in humanmine though.

**Comment by julie-sullivan** [comment]
This is the flymine test I found: https://github.com/intermine/intermine/pull/1130#issuecomment-138595196

**Comment by rachellyne** [comment]
No, sorry I was lying - I think the query was timing out rather than not running.  It is working in FlyMine.  Point mutation with length = 1 returns overlapping features.

**Comment by julie-sullivan** [comment]
@rachellyne Great! Whew! Thanks. I need to update humanmine correctly, I will rebuild and ask you to look again.

Also we should think about re-releasing flymine with this fix.

**Comment by julie-sullivan** [comment]
@rachellyne I had built humanmine wrong. Can you test again? rs113521347 overlaps ENSG00000227158 correctly now. This is on the test humanmine.

**Comment by julie-sullivan** [comment]
@sergiocontrino I am just a bit worried that my changing the index has broken something.

1. @rachellyne looked at humanmine and flymine and found that SNPs with a size = 1 now have overlaps. Maybe make some more checks?
2. check that other overlaps haven't broken. queries are okay. response time is comparable.

**Comment by sergiocontrino** [comment]
tested on a full thalemine, comparing the mine before and after re-running the post process with the modification (create-overlap-view) and the create-location-overlap-index.
used 2 queries: one on a set of about 150 genes and their overlapping features, and one on a set of about 20k genes and their overlapping features.

the first one works on both instances, while the second and more demanding fails on the new implementation. comparing the logs...

query 1
```
<query name="" model="genomic" view="Gene.primaryIdentifier Gene.overlappingFeatures.primaryIdentifier Gene.overlappingFeatures.length" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.symbol" op="=" value="ab*"/>
</query>
```

query 
```
<query name="" model="genomic" view="Gene.primaryIdentifier Gene.overlappingFeatures.primaryIdentifier Gene.overlappingFeatures.length" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.symbol" op="=" value="a*"/>
</query>
```

**Comment by sergiocontrino** [comment]
confirming that the new view makes the queries take longer (tested reverting the createoverlapview on the same db).  dropping and re-creating the overlap index does not help. not sure what changes. the behaviour is reproducible, and amounts to a delay of approx 30 s for the small query.

**Comment by julie-sullivan** [comment]
It makes sense that it takes longer because we are searching more of the region but 30s sounds like a long time. 

Did you ever get that second query running?

**Comment by julie-sullivan** [comment]
@sergiocontrino This pull request fixes a bug, meaning the current overlaps are wrong. If this fix doesn't work, does that mean we go back to bioseg?

**Comment by sergiocontrino** [comment]
a solution for the slow queries is to change the create view like below and change the current location__int4range index to include upper limit.
note:  the default is '[)', so we should need to change only the upper limit, see http://www.postgresql.org/docs/9.3/static/functions-range.html
a small patch added to the branch to do this.
i think we need to check again if the results are correct now...

```
AND int4range(l1.intermine_start, l1.intermine_end +1) 
&& int4range(l2.intermine_start, l2.intermine_end +1)
```

**Comment by julie-sullivan** [comment]
@sergiocontrino Fantastic! I will test on flymine today.

**Comment by julie-sullivan** [comment]
Refs #1108

**Comment by julie-sullivan** [comment]
@sergiocontrino rs113521347 overlaps ENSG00000227158 correctly with the change. Also FlyMine is working correctly.

**Pull request merged**
