### PR TITLE
Added QueryExpression.LENGTH and QueryExpression.CONCAT operators.

### PR DESCRIPTION
**Pull request by sammyjava**
## Details

I've added two new operators to QueryExpression: LENGTH returns the length of string and CONCAT concatenates two strings. So, they are used as such:
```
QueryField qf = new QueryField(qc, "primaryIdentifier");
QueryExpression qe = new QueryExpression(QueryExpression.LENGTH, qf);
```
```
QueryField qf = new QueryField(qc, "primaryIdentifier");
QueryValue qv = new QueryValue(".appendme");
QueryExpression qe = new QueryExpression(qf, QueryExpression.CONCAT, qv);
```
## Testing

I've tested with my own code and added the appropriate unit test code to those classes.

## Checklist

Before your pull request can be approved, be sure to check all boxes:

- [ ] Passing unit test for new or updated code (if applicable)
- [ ] Passes all tests – according to Travis
- [ ] Documentation (if applicable)
- [ ] Single purpose
- [ ] Detailed commit messages
- [ ] Well commented code
- [ ] Checkstyle

### CODE REVIEW

**Comment by sammyjava** [comment]
TravisCheckstyleSux

**Comment by sammyjava** [comment]
Wow, all complaints about indentation level and tabs; my editor NEVER puts in tab characters. And normally indents correctly. I'll wait for your order to handle this. We need a program that reformats indentation and removes any tabs to make Travis happy. That's all this is about!

**Comment by sammyjava** [comment]
@danielabutano all I see are warnings about indentation. I've removed all the tabs. Are we blocking a PR simply due to warnings? I don't see an actual error in Travis. If it's the warnings that are blocking, I can't fix them -- my editor won't indent the way Travis wants. We'll file under "Sam can't contribute to InterMine because Travis blocks Emacs Java syntax." Seriously. We shouldn't block PRs due to syntax warnings, it's counter-productive. But if you see an actual *error* let me know and I'll fix it. Otherwise, we can just forget this PR, I've got the update in my fork where I use it. :)

**Comment by danielabutano** [comment]
@sammyjava the test are run after checkstyle pass. For this reason, you do no see any test failing.
Let me talk with the team and I will let you know. We might leace the PR to the nex release

**Comment by sammyjava** [comment]
Sorry, I deleted the files to replace them (I found a couple tabs) and I guess I can't add new ones back to this PR. So I'll close this PR and add a new one. Waiting until the next release is totally fine, this is a very esoteric PR probably only to be used by me, but who knows?

**Comment by danielabutano** [comment]
It's nice to have your contribution included in the main repo, as you said, "who knows"?
Thanks @sammyjava! I will include your new PR in the next release

**Pull request closed without merging**
