### PR TITLE
Template user tags

### PR DESCRIPTION
**Pull request by julie-sullivan**
## Details

Add user tags to template JSON.

See #2011

## Testing

Make sure tags are still correct for super users. Needs a code review though, not sure it's the best thing to attach profile to template?

## Checklist

Before your pull request can be approved, be sure to check all boxes:

- [ ] Passing unit test for new or updated code (if applicable)
- [ ] Passes all tests – according to Travis
- [ ] Documentation (if applicable)
- [ ] Single purpose
- [ ] Detailed commit messages
- [ ] Well commented code
- [ ] Checkstyle

### CODE REVIEW

**Comment by yochannah** [comment]
I've deployed this locally but can't test as I'm getting a 500 error in the templates web service specifically. @danielabutano is getting a similar error on a totally different branch so she's looking in to it...

**Comment by julie-sullivan** [comment]
@danielabutano @yochannah I can deploy on beta flymine for ease of testing.

**Comment by danielabutano** [comment]
I have figured out the problem!!If you do not specify the format it fails

**Comment by yochannah** [comment]
@danielabutano nice one!! 

Can we default to some format (maybe json?)

=========

I can confirm that the tags for my personal template are returned, so long as I add ?format=json to the end of the endpoint. Without it, the server returns a 500. 

I've created an issue to [add this as a test to imjs](https://github.com/intermine/imjs/issues/38) - I need some help from @danielabutano to determine whether there are any personal templates with tags in the testmodel db to test against. 

Do we also want to add an issue to the python client to test this? I think it makes sense to maintain parity.

**Comment by yochannah** [comment]
@danielabutano has been very helpful while we've been investigating this. I've created a test for the bugfix ( https://github.com/intermine/imjs/pull/40 ) but I've had some trouble getting the correct test data into testmine.

It looks like there are two file where the templates in testmine are loaded from:

1. https://github.com/intermine/intermine/blob/dev/testmine/dbmodel/resources/default-template-queries.xml which creates superuser templates, and
2. https://github.com/intermine/intermine/blob/dev/testmine/webapp/src/main/resources/userprofile-withuser.xml which creates templates for `intermine-test-user`

imjs tests against intermine-test-user. When I add the following xml to userprofile-withuser.xml

```xml
    <tags>
      <tag name="thisIsAPrivateTag" objectIdentifier="private-template-1" type="template"/>
      <tag name="thisIsAlsoAPrivateTag" objectIdentifier="private-template-1" type="template"/>
    </tags>
```

the tags don't seem to get added.

BUT if I add equivalent tags to the other file, the tags do get created.

@danielabutano has a theory why.

**Comment by danielabutano** [comment]
the 2 xml files are loaded by 2 different classes: userprofile-withuser.xml by ProfileReadTask.java and default-template-queries by LoadDefaultTemplatesTask.java.
Both use the ProfileHandler.java to parse the profiles BUT the second one (that one which is able to add the tags) has also this section https://github.com/intermine/intermine/blob/dev/intermine/webtasks/src/main/java/org/intermine/web/task/LoadDefaultTemplatesTask.java#L166

**Comment by julie-sullivan** [comment]
> @yochannah @julie-sullivan I have figured out the problem!!If you do not specify the format it fails

I can never replicate your bugs! Can you give me the command you run? Because these all work for me:

http://localhost:8080/human/service/templates
http://localhost:8080/human/service/templates?format=json
http://localhost:8080/human/service/templates?format=xml

**Comment by yochannah** [comment]
I wonder why it works for you?

- http://www.humanmine.org/humanmine/service/templates >> 500, same as on my local machine. 
- http://www.flymine.org/flymine/service/templates >> 500
- http://mynock:8080/humanmine/service/templates >> 500 (I think the link should work for you as you're on the same network).

**Comment by yochannah** [comment]
catalina.2019-04-02.log    
catalina.out
localhost.2019-04-02.log   

are all silent on this matter.

**Comment by julie-sullivan** [comment]
Those URLs all work for me @yochannah, using cURL and the chrome extension.

**Comment by julie-sullivan** [comment]
> are all silent on this matter.
Probably because there is no error?

**Comment by julie-sullivan** [comment]
@danielabutano @yochannah I am able to load template tags.

Here is my snippet:

```
    <tags>
        <tag name="privateTag" objectIdentifier="My-Favourite-Employees" type="bag"/>
        <tag name="privateTag" objectIdentifier="The great unknowns" type="bag"/>
        <tag name="thisIsAPrivateTag" objectIdentifier="private-template-1" type="template"/>
        <tag name="thisIsAlsoAPrivateTag" objectIdentifier="private-template-1" type="template"/>
    </tags>
```

Here is my database:
```
 1000019 | private-template-1                       | template | thisIsAlsoAPrivateTag |       1000012
 1000020 | My-Favourite-Employees                   | bag      | privateTag            |       1000012
 1000021 | private-template-1                       | template | thisIsAPrivateTag     |       1000012
 1000022 | The great unknowns                       | bag      | privateTag            |       1000012
```

They do not show up in the webapp UI, but that is expected.

**Comment by julie-sullivan** [comment]
@yochannah ready for you to test!

I added a script `init-solr.sh` for travis to use.

**Comment by julie-sullivan** [comment]
all tests are passing, @yochannah is happy, we are done here folks.

**Pull request merged**
