### PR TITLE
cache the list of valid global templates

### PR DESCRIPTION
**Pull request by julie-sullivan**
Refs #1648

### CODE REVIEW

**Comment by yochannah** [comment]
I haven't been able to kill beta humanmine no matter how hard I tried. Yay.

**Comment by julie-sullivan** [comment]
@yochannah yay!!!

**Comment by julie-sullivan** [comment]
This needs to be tested *very* carefully. Everything looks good so far but what do I know.

* Is the iOS app able to topple a mine with these changes. @yochannah says no. I tested by making three requests for `http://beta.humanmine.org/beta/service/templates?format=json` simultaneously. Before this change that broke the site, after this change it has no impact. (I used the charles proxy tester suggested by Yo).
* Did I correctly invalidate the cache? Did I miss somewhere? Templates are handled by the profile exclusively, but tags are used for other things so handled by the TagManager and other places.
* Is this change threadsafe. will a change via web service be reflected in a request via the webapp?

**Comment by julie-sullivan** [comment]
@justinccdev Okay I made static and synchronised. Take a look?

Thanks for being so thorough!

**Comment by justinccdev** [comment]
Looks good.  Other comments:

* Profile.deleteTemplate() does not do the super-user check.  I think it should?
* Profile.invalidateTemplateCache() repeats the isSuperUser() check that all the other calls (except deleteTemplate()) also perform.  Can we rely on the Profile.invalidateTemplateCache() check and remove those in the callers, to reduce code duplication?  I would also suggest renaming invalidateTemplateCache() -> invalidateTemplateCacheIfRequired() to make the code more self-documenting.
* I think TagManager.deleteTag() methods should call a common subsequent deleteTag() method to avoid duplicating the TagNames.IM_PUBLIC.equals(tagName) check, just like addTag() only has this in one place.  Perhaps something like

```
public void deleteTag(String tagName, Profile profile) {
    if (TagNames.IM_PUBLIC.equals(tagName)) {
        profile.invalidateTemplateCache();
    }
}
called by the other relevant deleteTag() methods.
```

* TagManager.deleteTag(String, WebSearchable, Profile) is firing ws.FireEvent() before cache invalidation, whereas addTag() is doing it after.  This should be consistent.  I would suggest that this deleteTag() should also fire the event after cache invalidation.

* You eliminated the unused TemplateManager.model but did not eliminate it from the constructors.  This should also be done, and it means you won't need to introduce a separate TemplateManager(Profile) constructor.

**Comment by julie-sullivan** [comment]
```
You eliminated the unused TemplateManager.model but did not eliminate it from the constructors. This should also be done, and it means you won't need to introduce a separate TemplateManager(Profile) constructor.
```

I didn't want to change that to be backwards compatible. Do you think that's required?

**Comment by justinccdev** [comment]
> I didn't want to change that to be backwards compatible. Do you think that's required?

I don't think it's required in this case.  I would say almost certainly we are the only caller of those constructors and even if we weren't, adjusting is a 30 seconds change.  By leaving this stuff in, the code becomes more difficult to reason about and we accumulate cruft.

**Comment by julie-sullivan** [comment]
```
You eliminated the unused TemplateManager.model but did not eliminate it from the constructors. This should also be done, and it means you won't need to introduce a separate TemplateManager(Profile) constructor.
```

I didn't want to change that to be backwards compatible. Do you think that's required?

**Comment by julie-sullivan** [comment]
So you are saying .. don't be lazy. ;p but i want to be lazy!!

**Comment by julie-sullivan** [comment]
```
Profile.deleteTemplate() does not do the super-user check. I think it should?
```

Fixed by 7992c0cf836570c2e59ac0f96080b05cb1211af9 
Nice catch.

**Comment by julie-sullivan** [comment]
@justinccdev okay all done. Check it again? All good points. 

I did everything but the additional deleteTags() method. There are already 5 delete tags methods so I think it's best if I just leave that as is.

**Comment by justinccdev** [comment]
Yeah, looking at deleteTag() again I see it's not that straightforward so okay, let's leave that.

However, I just realized that simply using synchronized methods on TemplateManager will not work.  That's because each profile is instantiating on its own TemplateManager but the contended globalValidTemplateCache is now static.  Instead you'll have to synchronize explicitly, perhaps with

```
synchronized (TemplateManager.class) { ... }
```

**Comment by julie-sullivan** [comment]
You are right, most certainly. That's the "correct" way. But is it worth it compared to threading issues we might encounter? Which is what caused this mess in the first place.

Worst case scenario (for the code as-is in this branch right now):

1. Rachel removes the `im:public` tag from a template.
2. Simultaneously you request a list of templates. You get the bad template in your request.
3. the next request will find the `globalValidTemplateCache` empty and get the correctly tagged templates without the bad template Rachel just decommissioned.

Worst case scenario (for synchronised method):

1. Rachel removes the `im:public` tag from a template.
2. Simultaneously you request a list of templates. 
3. Site dies because of some weird race condition. 

What are your thoughts?

**Comment by justinccdev** [comment]
It's entirely possible that the issues we are seeing are due to synchronization not being done properly underneath, so we really don't want to introduce more as it's hard to predict what the effects are now and in the future.  The code change I've attached should perform proper synchronization now.  Please take a look.

If we're happy then I think we can go ahead and merge, though we now have an inconsistency in TemplateManager where other methods are not caching (and possibly code that hits them hard may trigger the same error).  And ideally we would know the exact underlying problem that's causing our hang issue in the first place.  But maybe the easiest thing is to take on that technical debt for now and address things again down the line.

**Comment by julie-sullivan** [comment]
this all works correctly. I was able to make three simultaneous requests x 10 and it's super fast.

**Pull request merged**
