### PR TITLE
corrects issues with subfeatures in jbrowse

### PR DESCRIPTION
**Pull request by sergiocontrino**
should be tested (postprocess and webapp) with flymine or humanmine.

### CODE REVIEW

**Comment by julie-sullivan** [comment]
@sergiocontrino What problem will be fixed? JBrowse isn't currently working in humanmine. Is this something @justinccdev could test in synbiomine?

If this is a thale-specific problem, might get away with not testing.

**Comment by sergiocontrino** [comment]
hi @julie-sullivan, this will solve a bug (an infinite loop with subfeatures) that made fail one of the jbrowse endpoints in intermine in thalemine, so i thought we could test it with humanmine and see if we can use the mine webservices for jbrowse? or maybe @justinccdev could give it a go on synbio (if it has subfeatures).

**Comment by justinccdev** [comment]
synbiomine doesn't have subfeatures so not testable there.

**Comment by julie-sullivan** [comment]
Working correctly in humanmine and thalemine now.

**Comment by julie-sullivan** [comment]
http://intermine.readthedocs.io/en/latest/database/database-building/post-processing/
@sergiocontrino can you add to these docs?

**Pull request merged**
