### PR TITLE
Update IntegrateUtils.groovy - add obo.ontology.description support

### PR DESCRIPTION
**Pull request by sammyjava**
obo.ontology.description added (should not have been missing)

## Details

*Summary of pull request, including references to relevant tickets (if applicable).*

## Testing

*Besides running unit tests, how can the reviewer test your feature / bug fix? Are there edge cases to be aware of?*

## Checklist

Before your pull request can be approved, be sure to check all boxes:

- [x] Passing unit test for new or updated code (if applicable)
- [x] Passes all tests – according to Travis
- [x] Documentation (if applicable)
- [x] Single purpose
- [x] Detailed commit messages
- [x] Well commented code
- [x] Checkstyle

### CODE REVIEW

**Comment by sammyjava** [comment]
Wow, I'm getting good at this! I can't believe I and no one else caught that the obo description parameter doesn't get loaded into DataSet.description.

**Comment by sammyjava** [comment]
Sorry, accidentally closed this PR. :)

**Comment by sergiocontrino** [comment]
tested with fly-misc-cvterms. it did not work (the setting, in project.xml, is ignored).
i tried also adding 
obo.ontology.description=FlyBase Controlled Vocabulary
in fly-misc-cvterms/fly-misc-cvterms.properties
the ontology name propriety is correctly taken from the project.xml file (if present). 
should i test it with something else? (why?) or should i set the description elsewhere?

**Comment by sammyjava** [comment]
Are you sure it didn't work? Here's an example ontology in a project.xml:
```
    <!-- plant ontology -->                                                                                                                                                                  
    <source name="plant-ontology" type="obo">                                                                                                                                                
      <property name="src.data.file" location="/data/plant-ontology/po.obo"/>                                                                                                                
      <property name="ontology.prefix" value="PO"/>                                                                                                                                          
      <property name="obo.ontology.name" value="Plant Ontology"/>                                                                                                                            
      <property name="obo.ontology.url" value="http://planteome.org/"/>                                                                                                                      
      <property name="obo.ontology.licence" value="https://creativecommons.org/licenses/by/4.0/"/>                                                                                           
      <property name="obo.ontology.description" value="The Plant Ontology (PO) is a community resource consisting of standardized terms, definitions, and logical relations describing plant\
 structures and development stages, augmented by a large database of annotations from genomic and phenomic studies."/>                                                                       
    </source>
```
which does indeed load the obo.ontology.description into the corresponding dataSet.description:
```
soymine=> select * from dataset where name='Plant Ontology';
-[ RECORD 1 ]-+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
description   | The Plant Ontology (PO) is a community resource consisting of standardized terms, definitions, and logical relations describing plant structures and development stages, augmented by a large database of annotations from genomic and phenomic studies.
licence       | https://creativecommons.org/licenses/by/4.0/
id            | 4000002
url           | http://planteome.org/
name          | Plant Ontology
version       | 
datasourceid  | 4000001
publicationid | 
class         | org.intermine.model.bio.DataSet
```

**Comment by sergiocontrino** [comment]
thank you @sammyjava, i'll check with another source.

**Comment by sergiocontrino** [comment]
i am still unable to have this working. i have tried also the go source.
@danielabutano could you have a look? i'm probably doing some basic mistake..

**Comment by danielabutano** [comment]
@sergiocontrino I will have a look at it

**Comment by danielabutano** [comment]
Hi @sammyjava, I have tried but it doesn't work.
Looking at the code, it's not enought to change the IntegrateUtils class only, we should add a new method setDescription in the OboConverter (which will be called dinamically by the configureDynamicAttributes [here](https://github.com/intermine/intermine/blob/dev/bio/core/src/main/java/org/intermine/bio/task/OboConverterTask.java#L122)) to set the new attribute description and we should use this to set the property in the datasetitem [here](https://github.com/intermine/intermine/blob/dev/bio/core/src/main/java/org/intermine/bio/dataconversion/OboConverter.java#L200).
Maybe this PR doesn't contain all your changes?
Another possibility is that the description column in the DB has been loaded by the [datasets.xml](http://intermine.org/im-docs/docs/next/database/data-sources/library/data-sets/).

**Comment by sammyjava** [comment]
NOTE: I'll start with the current official dev and make changes until this works. Which is what I thought I did, but I'll do it again. :)

**Comment by sammyjava** [comment]
I just re-PRed this update, simply copying over the two changed files from our LIS branch to the current 5.0.5 dev branch. This update DOES work on our mines, and I don't think any other files are involved. These are the two files that @danielabutano mentioned as needing to be changed, and they were changed. So if it doesn't work on your mines, there's something else going on!

**Pull request closed without merging**
