### PR TITLE
Update SolrKeywordSearchHandler.java

### PR DESCRIPTION
**Pull request by sammyjava**
Wrap faceted search term in quotes so it works on things like "C. arietinum".

## Details

*Summary of pull request, including references to relevant tickets (if applicable).*

## Testing

*Besides running unit tests, how can the reviewer test your feature / bug fix? Are there edge cases to be aware of?*

## Checklist

Before your pull request can be approved, be sure to check all boxes:

- [ ] Passing unit test for new or updated code (if applicable)
- [ ] Passes all tests – according to Travis
- [x] Documentation (if applicable)
- [x] Single purpose
- [x] Detailed commit messages
- [x] Well commented code
- [ ] Checkstyle

### CODE REVIEW

**Comment by sergiocontrino** [comment]
the change is fine, but i am not sure about the intended behaviour. 
i thought it was solving a bug in filtering by organism, but this seems to work. if this is meant to allow matches with multi words terms, this can already be done enclosing them with " in the UI. I think that the default search behaviour is meant to have an OR between terms.  is this we want to change?

**Comment by sammyjava** [comment]
Wrapping the search term in quotes makes the search indexing work for faceting "C. arietinum," etc. at least as far as I could tell at the time I PRed this. :) If you like I can back out the change and check that everything works correctly. It could be that I fixed two things at the same time. It's been a while. :)

**Comment by sergiocontrino** [comment]
hi @sammyjava , sorry for the long time it took us to check this! (it is again release time..) 
if the issue was the faceting by organism, this is working in dev, so i think we can skip the PR.  if the issue was to be able to search with multi-words terms i would probably use the " in the search box, but we can discuss with @rachellyne if this is the expected behaviour. 
if i misunderstood just please let me know, i can implement and do the testing here (at last and at least..). thanks!

**Comment by sammyjava** [comment]
Sounds fine, I think I'll remove this update in my fork and see what happens that I didn't like before, if it happens. :)

**Comment by sergiocontrino** [comment]
i think we can close this, please reopen @sammyjava if needed. thanks!

**Comment by sammyjava** [comment]
I agree. :)

**Comment by sammyjava** [comment]
So, @danielabutano and @sergiocontrino a user noticed that a recent mine of mine doesn't properly facet on organism (built after I'd removed this change). I can confirm that this bug is reproduced in the current FlyMine and that this PR does, in fact, fix it on my mines.

1.  Do a FlyMine keyword search on "glucose": you'll get 4930 results
2.  Select _R. norvegicus_ -- works correctly, you get 353 displayed results, all _R. norvegicus_. (But note that this is the only _Rattus_ species in the mine.)
3. Unselect _R. norvegicus_ and select _D. pseudoobscura_ which should display only 31 results. But it displays 221 results for that and EVERY other species in _Drosophila_

This is, in fact our bug. We have several species within the same genus, and the Organism facet filter always returns all organisms within the chosen genus, because of this issue with the space in  _G. species_ that is fixed with this PR.

So, I'm going to add a PR again for a future update (the repo for this one is gone), I'll reference it below.

**Pull request closed without merging**
