### PR TITLE
Make batch size used in genomic region search inititialisation configurable

### LINKED ISSUE #867: Feature request: configuable parameter
Genomic region search initializing is very slow with a mine with a large number of scaffolds. Resetting query batch size to a larger value speeds up the initializing in this case. Can this query batch size be a configurable parameter?

### PR DESCRIPTION
**Pull request by rnsmith**
Make batch size used in genomic region search inititialisation larger by default and configurable by setting `genomicRegionSearch.initBatchSize` in `web.properties`.

Also speed up a query and refactor some code to improve clarity a little. 

Fixes #867.

### CODE REVIEW

**Comment by rnsmith** [comment]
Sorry, I commited fixes for issue #861 in this branch as well by mistake.

**Comment by julie-sullivan** [comment]
@sergiocontrino Maybe we wait for @JoeCarlson to test?

Also, I don't know if we want partial fixes? See above:

> Sorry, I commited fixes for issue #861 in this branch as well by mistake.

Richard is back in a few weeks.

**Comment by julie-sullivan** [comment]
@sergiocontrino Can you test that this region search works correctly? if so, I will merge this in. I'll ask @JoeCarlson if this addresses the original issue of the region search start up being too slow.

**Comment by julie-sullivan** [comment]
To test: make sure region search works as expected.

**Comment by justinccdev** [comment]
Did you want me to test against current rnsmith:i867 or merge it to current beta?  It doesn't currently compile on beta because of commit 9a666aaa though that should be a fairly simple fix.

Also, to save me digging in to doc/code myself, how would I actually go about testing this?

**Comment by julie-sullivan** [comment]
To test: make sure region search works as expected.

**Comment by julie-sullivan** [comment]
@justinccdev I checked out richard's code and deployed a webapp. The region search seems to be working fine for me, and the other queries too. All the travis tests passed.

Can you clarify what wasn't working for you?

**Comment by justinccdev** [comment]
It wasn't so much that it didn't work as the branch us a year old and
doesn't compile against current beta, though it looks like the change
required is not too complicated

**Comment by julie-sullivan** [comment]
@justinccdev You say that the branch doesn't compile, can you clarify? Everything works for me, so if you are more specific about your problem I can try to investigate.

**Comment by justinccdev** [comment]
If you update the branch to current beta it no longer compiles. Or am I
mistaken about this?

**Comment by julie-sullivan** [comment]
@justinccdev Not sure! I can deploy the webapp just fine and all my tests pass (locally, in intermine/all, didn't try bio). But maybe I've done something different. Can you post the error message you get?

**Comment by justinccdev** [comment]
Many apologies, this looks like a failure on my part where that I assumed Eclipse was showing me real compile errors but in fact the failures were due to its files not being up-to-date.  The build itself is fine.

**Comment by justinccdev** [comment]
I will test this soon (but might not be until later on Thursday due to SynBioMine work).  I see there's region search doc at [1] .

[1] http://flymine.readthedocs.org/en/latest/region-search/Documentationregionsearch.html

**Pull request merged**
