### PR TITLE
added config to text bugfix for https://github.com/intermine/intermin…

### PR DESCRIPTION
**Pull request by yochannah**
…e/issues/1126

### CODE REVIEW

**Comment by julie-sullivan** [comment]
> WARNING! The following mines were unreachable:    HumanMine 

HumanMine seems to be working okay though

**Comment by julie-sullivan** [comment]
Is it querying all friendly mines? or just humanmine? 

I don't think this tool is worth spending more time on. We should spend our time making a nice new tool instead of fixing this obsolete one. imo.

**Comment by yochannah** [comment]
Mine works ok for HumanMine. Could it be CORS raising its evil head?

**Comment by julie-sullivan** [comment]
oh yes, I didn't fix CORS with humanmine. Shouldn't we be able to query humanmine from anywhere though? I don't really understand CORS.

**Comment by yochannah** [comment]
we can query humanmine from anywhere, but when we query it from multiple different sites on the same client, something in the session is causing the error, due to what I think is our faulty config(?). It goes roughly like this: 

1. You access WhateverMine's webservices via appA.com. 
2. WhateverMine starts a session, and says you came from appA.com.
3. You access WhateverMine's webservices via appB.com.
4. Whatevermine should say "cool, that's ok" but instead it says "hold on, you just came from appA.com! This must be a highjacked session! I can't let you do this." and so appB.com never works. 

So if you accessed WhateverMine's web services, for example, from localhost:8080, and then accessed it again from the live site, the error would peek out its mean little head and laugh at you.

**Comment by julie-sullivan** [comment]
@joshkh Can you take a look at this? Do we want to spend more time on this tool? 

I'd like to work on workshop-related items now and fix this later. but maybe with the CORS issues fixed this all works fine now?

**Comment by yochannah** [comment]
I am pretty sure it should work fine if the CORS issue is fixed, but please double check...

**Comment by julie-sullivan** [comment]
going to wait until next release for this.

**Comment by julie-sullivan** [comment]
I'm going to close this temporarily whilst I reconfigure the branch system.

**Pull request closed without merging**
