### PR TITLE
Json queries

### PR DESCRIPTION
**Pull request by julie-sullivan**
Refs #1327 and #1656

### CODE REVIEW

**Comment by julie-sullivan** [comment]
To test:

- [ ] Works with JSON or XML
- [ ] Many queries, one query
- [ ] Fails gracefully
- [ ] works on all constraint types.

**Comment by julie-sullivan** [comment]
@joshkh Can you start testing this? I can put on beta branch if that's easier.

I am still working on implementing a JSON validator, but you can start making sure I implemented everything correctly. There is a checklist above, and @yochannah put a checklist of the end points in the ticket.

**Comment by julie-sullivan** [comment]
@joshkh @yochannah Can you take a look at the test failure?

https://travis-ci.org/julie-sullivan/intermine/jobs/274090813
```
302: SyntaxError: Unexpected end of JSON input
```
It says it's bad JSON. This is not a true fact! Fake news!

**Comment by yochannah** [comment]
So, I replicated this locally on the testmodel and ran it through charles to inspect the error. It's definitely returning a 302, for this query:

**POST** http://localhost:8080/intermine-demo/service/query/code
**Query params: **
query: 

```
<query model="testmodel" view="Employee.name Employee.department.name Employee.department.manager.name Employee.department.company.name Employee.fullTime Employee.address.address" ></query>
```
lang: `py` (or any other lang)

The fun part? I don't think this happens for flymine. Could this be a testmodel misconfiguration?

you should be able to replicate it yourself, like this

```
curl -X POST   http://localhost:8080/intermine-demo/service/query/code   -H 'authorization: Token test-user-token'   -H 'cache-control: no-cache'   -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW'   -H 'postman-token: 3e8e0252-adce-eaf1-edfe-82a73c32aa3b'   -F 'query=%3Cquery+model%3D%22testmodel%22+view%3D%22Employee.name+Employee.department.name+Employee.department.manager.name+Employee.department.company.name+Employee.fullTime+Employee.address.address%22+%3E%3C%2Fquery%3E& lang=py' -v
```

**Comment by julie-sullivan** [comment]
When I run the code generation code in the testmodel webapp:

```
Error: 404
Stack trace:
blocking/</<@http://cdn.intermine.org/js/intermine/imjs/3.15.0/im.js:146:31
[29]</EventEmitter.prototype.emit@http://cdn.intermine.org/js/intermine/imjs/3.15.0/im.js:8281:9
[54]</Response.prototype.handle@http://cdn.intermine.org/js/intermine/imjs/3.15.0/im.js:13263:14
[53]</module.exports/xhr.onreadystatechange@http://cdn.intermine.org/js/intermine/imjs/3.15.0/im.js:13026:9
```

**Comment by julie-sullivan** [comment]
@yochannah @joshkh Before merge, I want to squash all the commits into one.

**Comment by julie-sullivan** [comment]
Also I have no idea why travis isn't showing up. It's all passing! I am being honest!

**Comment by julie-sullivan** [comment]
@joshkh before this can be merged, the web service version has to be incremented. (version will depend on which pull request you merge in first!)

**Comment by julie-sullivan** [comment]
Does this address #1732

**Comment by julie-sullivan** [comment]
@sergiocontrino 

* I want to squash the commits into one I think before merge
* Need to increment the web service version before merge
* Josh asked for JSON queries, but they are not implemented in blue genes yet, so ONLY test the XML. Make sure I did not break the current functionality. That the JSON queries are correctly formatted will be up to @yochannah to test when that feature is implemented.

**Comment by sergiocontrino** [comment]
Fails gracefully with informative error messages: yes in the case of wrong path

> Path Gen in constraint is not in the model.

**Comment by julie-sullivan** [comment]
@yochannah We are going to merge this into dev. We haven't tested with BlueGenes but the idea is that what InterMine provides is the canonical JSON query syntax. (I think BlueGenes has its own shortcut?).

**Comment by yochannah** [comment]
That sounds right to me.

**Comment by julie-sullivan** [comment]
I forgot GAF, BED and FASTA queries!

**Comment by yochannah** [comment]
Is it okay to review this after BOSC (e.g. in July?)

**Pull request merged**
