### PR TITLE
I think I've got this in an up-to-date dev branch now. Allows null name field in the OBO.

### PR DESCRIPTION
**Pull request by sammyjava**
## Details

*Summary of pull request, including references to relevant tickets (if applicable).*

## Testing

*Besides running unit tests, how can the reviewer test your feature / bug fix? Are there edge cases to be aware of?*

## Checklist

Before your pull request can be approved, be sure to check all boxes:

- [x] Passing unit test for new or updated code (if applicable)
- [x] Passes all tests – according to Travis
- [x] Documentation (if applicable)
- [x] Single purpose
- [x] Detailed commit messages
- [x] Well commented code
- [x] Checkstyle

### CODE REVIEW

**Comment by sammyjava** [comment]
@julie-sullivan here's the new pull request on OboParser.java. I'm still a bit confused on how to update OboParserTest.java, I've left a comment on the previous pull request requesting your sage counsel.

**Comment by julie-sullivan** [comment]
@sammyjava We reviewed this as a group and the code is fine but people aren't happy as this could possibly mess up the enrichment tools. (We assume all terms have a name).

1. What is the use case for having a term without an identifier? They can't be used to annotate anything, surely.
2. Can we discard these terms instead?

**Comment by sammyjava** [comment]
The use case is not having to hack the OBO files so they load. We shouldn't have to customize OBO files to suit IM. I don't load the terms, I just don't let the loader crash.

**Comment by sammyjava** [comment]
Sorry, right-o, I do allow terms without names, because I've got a boatload of them from the cowpea crop ontology. BUT I don't need to load those, let me update this so it simply bails without throwing a RuntimeException in the case of no name. (I'm a bit confused by what I wrote, anyway!)

**Comment by julie-sullivan** [comment]
From @sammyjava 

```
I looked again and it does indeed NOT store terms with missing names. There are a few legacy 
terms getting stored elsewhere that do have missing names, which confused me, but they're not
 coming from OboParser.java because I put some debug lines in OboConverter.java and they
 didn't turn up. I have no idea what those are. 
```

**Comment by julie-sullivan** [comment]
@sammyjava Looking at the code, I see:

```
    // if name is null
    OboTerm term = new OboTerm(id, name);
    term.setObsolete(isTrue(tvs, "is_obsolete"));
    terms.put(term.getId(), term);
```
So it looks like the term _is_ being stored but set as obsolete. From your comment above, you had decided to discard the terms instead.

Can you clarify? Thanks!!

**Comment by sammyjava** [comment]
Oh, bugger, I had an older version in here. I was looking at the one on my server thinking they were the same. This one indeed does NOT store terms w/o names and has been tested as such with some OBO files that contain nameless terms.

**Comment by sammyjava** [comment]
And Travis is probably going to whine about spacing and such, so I'll hit that when he'd done whining.

**Comment by sammyjava** [comment]
This code is FINE, and was formatted by Emacs java-mode. Which is FINE. So I'll let you wrangle Travis on this one, it's those damned case statements.

**Comment by julie-sullivan** [comment]
Just to be clear, that code you have is storing the terms without names. However, it's marking them as "is obsolete" or "is transitive". 

You commented above that we just wanted to discard these terms instead of throwing an exception.

Can you clarify?

**Comment by sammyjava** [comment]
I do NOT store any nameless terms in any way in this new version. The confusion arose because it turned out I had a newer version on my server than up here and I was looking at the server version earlier. This version SKIPS terms without names.

**Comment by julie-sullivan** [comment]
Tested

* same number of terms created
* removed a name, no error and term was not saved in database -- just discarded.

**Pull request merged**
