### PR TITLE
remove duplicates from treefam too

### PR DESCRIPTION
**Pull request by julie-sullivan**
don't store duplicate homologues. Refs #957 and #960

### CODE REVIEW

**Comment by sergiocontrino** [comment]
i am still getting duplications (see #960), to check
 primaryidentifier  
--------------------
 ENSDARG00000069345
 ENSMUSG00000022421
 ENSDARG00000068880
 ENSRNOG00000039402
 ENSDARG00000003370
 ENSDARG00000069347
 ENSDARG00000069366
 ENSDARG00000069330
 ENSDARG00000069355
 ENSG00000183741
 ENSDARG00000069359
 ENSDARG00000068852
 ENSRNOG00000039378
(13 rows)

**Comment by julie-sullivan** [comment]
@sergiocontrino Can you try again? I just re-ran the build and did not get any duplicates. Maybe you didn't do a clean-all or somesuch?

**Comment by julie-sullivan** [comment]
This is the query to see if genes are homologues of themselves:

> select * from homologue h1, homologue h2 where h1.id=h2.id and h1.geneid=h2.homologueid;

**Comment by julie-sullivan** [comment]
This is the query to detect duplicate homologues:
> select geneid, homologueid, count(*) from homologue group by geneid, homologueid having count(*) > 1;

So my fix didn't work. But we might not want this as each line of the file might have different evidence.

**Comment by sergiocontrino** [comment]
the duplications of the previous comment are gone. number of items seems ok, although 76 less (not 13)
old:1970086
new:1970010

**Comment by sergiocontrino** [comment]
i think the correct query to check duplications is actually
select * from homologue h1, homologue h2 
where h1.geneid=h2.geneid 
and h1.homologueid=h2.homologueid
and h1.id!=h2.id;

this gives 0 in the new code, while is returning 152 in the old.
this explains now the difference in total numbers mentioned in previous comment.
fix is working then.

**Pull request merged**
