### PR TITLE
Imtables 2.0 - including support for imtables 2.0

### PR DESCRIPTION
**Pull request by alexkalderimis**
Tables tested in all contexts.

This change set also reintroduces some lost features, such as list operations on the bagDetails page, and the ability to remove items from lists.

### CODE REVIEW

**Comment by julie-sullivan** [comment]
@alexkalderimis Is this meant to work with non-testmodel intermines?

**Comment by alexkalderimis** [comment]
Of course. What issues have you encountered?

**Comment by julie-sullivan** [comment]
@alexkalderimis Take a look at beta.flymine.org. I did a clean-all and redeployed twice. Was there config I have to change?

**Comment by alexkalderimis** [comment]
Right - this is do do with the CSS file. We need to generate one for flymine, but we can use the generic one in the interim

**Comment by julie-sullivan** [comment]
The boxes don't line up on the front page:

front-box

**Comment by julie-sullivan** [comment]
The summary popup can be quite tall. 
summary-pop

**Comment by julie-sullivan** [comment]
Adding a filter dialogue doesn't work as expected.

1. Chrome -- took ~30 seconds to appear, then turned black. The whole screen.
2. Firefox -- took ~30 seconds to appear but then complained.

add-filter

**Comment by alexkalderimis** [comment]
The add filter dialogue will be due to trying to render too much of the model. I will try and make it lazier

**Comment by julie-sullivan** [comment]
Adding a filter doesn't work as expected.

http://beta.flymine.org/beta/template.do?name=Gene_BDGP

I was testing ONE OF/NONE OF and constrained on Gene.organism.name.

1. didn't get a dropdown
2. constrained to be NONE OF Drosophila Melanogaster but did not change my output (which were Dmel genes). Failed with != too.

**Comment by alexkalderimis** [comment]
Having had a look at the filter thing I think it is due to the type-ahead model path search. That can be addressed, I think...

**Comment by julie-sullivan** [comment]
The query results aren't showing up:

> [11:31:17.653] ReferenceError: imtables is not defined @ http://beta.flymine.org/beta/results.do?trail=%7Cquery%7Cresults.0&queryBuilder=true:811

**Comment by julie-sullivan** [comment]
@alexkalderimis I just got the black screen of death when trying to add a filter. I believe this was going to be fixed by https://github.com/intermine/intermine/pull/954#issuecomment-77626940

Can you fix?

**Comment by julie-sullivan** [comment]
@alexkalderimis  Open issues:

1. can't merge
2. black screen of death
3. ONE OF does not work as expected see https://github.com/intermine/intermine/pull/954#issuecomment-77563473

**Comment by julie-sullivan** [comment]
Things to test:

* region search
* keyword search
* memory leaks
* JS code gen
j* browse
* CDN (hosted and not)
* pathways displayer
* bag details, widgets

**Comment by julie-sullivan** [comment]
@alexkalderimis Can we remove the keyword search changes from this pull request?

**Comment by alexkalderimis** [comment]
rebase complete

**Comment by alexkalderimis** [comment]
JS code gen seems to work: 
js-code-gen

**Comment by alexkalderimis** [comment]
`ONE OF` seems to work correctly for me.

**Comment by alexkalderimis** [comment]
merge is obviously fixed...

**Comment by alexkalderimis** [comment]
Region search works in biotestmine: 
region-search-biotestmine

**Comment by alexkalderimis** [comment]
Confirmed that the filter dialogue performs well in bio mines

**Comment by alexkalderimis** [comment]
@julie-sullivan Let me know if there are any blockers - I think this looks pretty good.

I understand there are keyword search changes here: if that is a blocker I will work on fixing them...

**Comment by julie-sullivan** [comment]
What is the checklist of things I need to test? Is this right:


    region search
    keyword search
    memory leaks
    JS code gen
    jbrowse
    CDN (hosted and not)
    pathways displayer
    bag details, widgets

**Comment by julie-sullivan** [comment]
still blocking

1. sequence feature facet instead of gene
2. title is empty

kw


Can we just remove the keyword search changes? Or isolate the google changes? Someone can't log in to flymine, so I need the fix ASAP.

**Comment by julie-sullivan** [comment]
JavaScript generation 

1. Have to click twice to get the file. select JavaScript, then click to download. Only have to click once on current flymine. 
2. Save file as query.html and look at in browser. Shows garbled JS. In current flymine, loading query.html shows the results tables.

**Comment by sergiocontrino** [comment]
region search: seems to work, the navigation bar and changing the number of results displayed are not working.

**Comment by sergiocontrino** [comment]
gene report page: get unresponsive script (on firefox); 
pathway displayer: message:This app requires jQuery 2.x.x

**Comment by julie-sullivan** [comment]
From @rachellyne 

screenshot from 2015-05-05 11 46 05

it looks like she was on the report page but wasn't able to do anything.

**Comment by alexkalderimis** [comment]
The Google changes can be isolated.
I'll look into fixing the kw search issues today maybe
On 5 May 2015 11:00 am, Julie Sullivan <notifications@github.com> wrote:still blocking

sequence feature facet instead of genetitle is empty



Can we just remove the keyword search changes? Or isolate the google changes? Someone can't log in to flymine, so I need the fix ASAP.

**Comment by alexkalderimis** [comment]
The JS code gen can be made runnable without downloading anything - I'll do that today

**Comment by julie-sullivan** [comment]
https://github.com/intermine/intermine/pull/954#issuecomment-77560224 is still an issue. 

We need to only have attributes in the summary and leave off the references. Otherwise the popup is too tall for my monitor.

**Comment by julie-sullivan** [comment]
rows-per-page

There is an extra "25" option on the rows-per-page dropdown.

**Comment by julie-sullivan** [comment]
Sometimes the summary popup doesn't go away, e.g. when I was getting that screenshot (above, the extra 25 in the dropdown). The summary for the runt gene won't go away no matter what I do.

**Comment by sergiocontrino** [comment]
list analysis and widgets seems fine.

**Comment by rachellyne** [comment]
Add a new filter - what is "Wernham-Hogg?   Also found positioning of "update, cancel, remove"  boxes odd - didn't see them at first - I immediately went to the bottom of the box.


Uploading screenshots is not working for me - I'll have to show you.  (template: Gene -> Protein).

**Comment by rachellyne** [comment]
New summary pop ups are way to big. Was a nice idea but maybe doesn't work.

**Comment by rachellyne** [comment]
Manage relationships - great that added.  I'm not sure I would understand it if I was coming to this new.  We can maybe work on the help message.

**Comment by rachellyne** [comment]
New font - looks like computers from the olden days!

**Comment by sergiocontrino** [comment]
regarding new imtables:
good, with a couple of issues:
- add a filter: second window does not remember what you entered in the first one (always David* ?!)
- not sure we need to display the 'releted items' in the summary
- code generation: i sort of preferred the old way (i think specifying a starting type, e.g. Python, could make people think this is the only one, and you need to do click 1 more time if you select the one you want). 
- manage relationship is great.

**Comment by julie-sullivan** [comment]
"download data" on column summary only downloads first 25. Works as expected on live flymine.org.

**Comment by julie-sullivan** [comment]
Filtering on column summaries not working as expected. Nothing happens when filtering on a string.

**Comment by julie-sullivan** [comment]
#797 UI for range contraints is working correctly. Need some help text. @rachellyne What do you think?

**Comment by julie-sullivan** [comment]
#641 still can't filter on booleans

**Comment by alexkalderimis** [comment]
#641 should be fixed now (see beta.flymine)

**Comment by julie-sullivan** [comment]
ONE OF

* filters correctly
* no dropdowns
* Wernham-Hogg suggested for organism name

lookup

**Comment by julie-sullivan** [comment]
> A script on this page may be busy, or it may have stopped responding. You can stop the script now, or you can continue to see if the script will complete.
> Script: http://cdn.intermine.org/js/intermine/im-tables/2.0.0-beta/imtables.js:49091

Collections on report pages aren't loading. This is what @rachellyne was reporting.

**Comment by julie-sullivan** [comment]
Can we remove the keyword searches from this pull request? The build still takes 90 minutes instead of 15, and the search results are still missing the title.

```
postprocess:
[postprocess] Found 18 post-processes
[postprocess] Performing postprocess: create-search-index
[postprocess] Creating lucene index for keyword search...

do-action:

-post-action:

action:

default:

BUILD SUCCESSFUL
Total time: 97 minutes 36 seconds
```

**Comment by alexkalderimis** [comment]
I will fix the suggestion (still working on the list upload now).

I will either pull out the keyword search changes (very painful) or better just fix it.

The keyword search issues are complicated by a lack of tests.

**Comment by alexkalderimis** [comment]
@julie-sullivan, @rachellyne Regarding the facets, make sure that the `keyword_search.properties` file has the correct Category facet:

```properties
index.facet.multi.Category = Category
```

Not that this should be a *multi* facet.

**Comment by julie-sullivan** [comment]
@alexkalderimis Can you update your branch? I am not sure how I would be able to do a pull request on your branch.

**Comment by julie-sullivan** [comment]
on imtables branch:

```
julie ~/git/intermine/testmodel $ ./setup.sh 
------> Checking configuration...
------> Checking config...
------> Checking properties file
------> Checking databases...
objectstore-demo exists
userprofile-demo exists
------> Processing books...
test -d venv || virtualenv venv
/bin/sh: 1: virtualenv: not found
make: *** [venv/bin/activate] Error 127
```

on beta:

```
julie ~/git/intermine/testmodel $ ./setup.sh 
------> Checking config...
------> Checking databases...
userprofile-demo exists.
objectstore-demo exists.
------> Removing current webapp
------> Loading demo data set...
------> Building and releasing web-app...
[tomcat-deploy] OK - Deployed application at context path /intermine-demo
------> All done. Build log is available in /local-homes/julie/git/intermine/testmodel/build.log
```

Is there new config needed?

**Comment by alexkalderimis** [comment]
@julie-sullivan The testmodel needs virtualenv (the python package).

**Comment by alexkalderimis** [comment]
@julie-sullivan Sorry I'm confused, update my branch to what?

**Comment by julie-sullivan** [comment]
@alexkalderimis Sorry! You suggested I make this change:

https://github.com/intermine/intermine/pull/954#issuecomment-100854497

Instead, can you update human and flymine's properties file on the imtables-2.0 branch? That would be easier for me as I am testing with a few users on a few servers.

**Comment by alexkalderimis** [comment]
@julie-sullivan - the key-word search properties have been updated.

**Comment by julie-sullivan** [comment]
Open issues:

1. keyword search (various)
2. querybuilder CSS needs to be adjusted (minor)
3. filtering on booleans doesn't work when there are NULLs  see #641
4. report page - outer joins and memory issue
5. code generation - have to double click, JavaScript doesn't render
6. summary popup too tall
7. there is an extra "25" listed on the page size dropdown menu.

**Comment by alexkalderimis** [comment]
Of those, I believe 3, 5b (js doesn't render) and 6 have been addressed

**Comment by sergiocontrino** [comment]
manage filter: using 'none of' appear to add an empty item at the start.

**Comment by alexkalderimis** [comment]
@sergiocontrino Screenshots, XML, json - all would be helpful

**Comment by alexkalderimis** [comment]
4 and 5a have been addressed

**Comment by julie-sullivan** [comment]
1. keyword search (various)
2.   querybuilder CSS needs to be adjusted (minor)
3.   filtering on booleans doesn't work when there are NULLs see #641
4.  report page - outer joins
5.  report page - memory issue
6.  code generation - have to double click
7.  code generation - JavaScript doesn't render
8.  summary popup too tall
9. there is an extra "25" listed on the page size dropdown menu.
10. tomcat - everytime I have to redeploy beta flymine, I have to kill tomcat. Related to number 5 I hope.

**Comment by sergiocontrino** [comment]
noneof

**Comment by julie-sullivan** [comment]
@alexkalderimis Run this query

```xml
<query name="" model="genomic" view="Gene.primaryIdentifier Gene.proteins.primaryAccession Gene.proteins.isUniprotCanonical" longDescription="" sortOrder="Gene.primaryIdentifier asc">
</query>
```

Filter on NULL and FALSE. It only returns FALSE values.

**Comment by julie-sullivan** [comment]
Going to the report page crashed the webapp.

**Comment by alexkalderimis** [comment]
As in killed the server? How is that possible? 
On 14 May 2015 9:51 am, Julie Sullivan <notifications@github.com> wrote:Going to the report page crashed the webapp.

**Comment by julie-sullivan** [comment]
@alexkalderimis  There were a bunch of these in the log files:

> Exception in thread "ajp-bio-8009-exec-71" java.lang.OutOfMemoryError: PermGen space

**Comment by julie-sullivan** [comment]
The saving of the JavaScript works on the list page and all the others work on the results page. The only saving that doesn't work is JavaScript on the results page. 

> ReferenceError: saveAs is not defined imtables.js:8697

**Comment by julie-sullivan** [comment]
nm user error report page is fine now!

**Comment by alexkalderimis** [comment]
What JVM is beta on?
On 14 May 2015 10:42 am, Julie Sullivan <notifications@github.com> wrote:@alexkalderimis  There were a bunch of these in the log files:


Exception in thread "ajp-bio-8009-exec-71" java.lang.OutOfMemoryError: PermGen space

**Comment by alexkalderimis** [comment]
Phew
On 14 May 2015 10:50 am, Julie Sullivan <notifications@github.com> wrote:nm user error report page is fine now!

**Comment by alexkalderimis** [comment]
Hmm, dependency issue?
On 14 May 2015 10:50 am, Julie Sullivan <notifications@github.com> wrote:The saving of the JavaScript works on the list page and all the others work on the results page. The only saving that doesn't work is JavaScript on the results page. 


ReferenceError: saveAs is not defined imtables.js:8697

**Comment by julie-sullivan** [comment]
I ran this query:

```
<query model="genomic" view="Chromosome.locatedFeatures.feature.primaryIdentifier Chromosome.locatedFeatures.feature.symbol Chromosome.primaryIdentifier Chromosome.locatedFeatures.feature.chromosomeLocation.start Chromosome.locatedFeatures.feature.chromosomeLocation.end Chromosome.locatedFeatures.feature.chromosomeLocation.strand" sortOrder="Chromosome.locatedFeatures.feature.primaryIdentifier ASC" constraintLogic="A and B and C and D" name="ChromLocation_Gene" >
  <constraint path="Chromosome.organism" type="Organism" />
  <constraint path="Chromosome.locatedFeatures.feature" type="Gene" />
  <constraint path="Chromosome.locatedFeatures.feature.chromosomeLocation" type="Location" />
  <constraint path="Chromosome.primaryIdentifier" op="=" value="2L" code="A" />
  <constraint path="Chromosome.organism.name" op="=" value="Drosophila melanogaster" code="B" />
  <constraint path="Chromosome.locatedFeatures.feature.chromosomeLocation.start" op="&gt;" value="1" code="C" />
  <constraint path="Chromosome.locatedFeatures.feature.chromosomeLocation.end" op="&lt;" value="50000" code="D" />
</query>
```

Changed a couple relationships to outer and got this error:

> XML is well formatted but query contains errors:
> Order by element Chromosome.locatedFeatures.feature.primaryIdentifier ASC is not in the root outer join group.

**Comment by julie-sullivan** [comment]
Changing chromosomeLocation to an outer join (in above query) made the cell formatter go away.

**Comment by julie-sullivan** [comment]
This text looks funny

bolding

**Comment by sergiocontrino** [comment]
12- the filter is working, but display seems wrong.
to reproduce (example):
- go to list and use the only one available.
- click manage filters
- click define new filter
- choose symbol (2 clicks)
- drop down choose NONE OF
=> the form display already an empty field
noneof1
you can go on adding your value etc, and filtering actually works
noneof2

**Comment by julie-sullivan** [comment]
regarding outer joins:

colsumm


1. column summary is blank
2. toggle visibility button does nothing
3. See #744

**Comment by rachellyne** [comment]
"Show results" button is out of place on the query builder.

**Comment by julie-sullivan** [comment]
Error when trying to download FASTA:

1. run this query

```
<query model="genomic" view="Gene.name Gene.mRNAExpressionResults.stageRange Gene.mRNAExpressionResults.expressed Gene.mRNAExpressionResults.mRNAExpressionTerms.name Gene.mRNAExpressionResults.dataSet.dataSource.name Gene.locations.start Gene.locations.end Gene.locations.strand" sortOrder="Gene.name ASC" constraintLogic="A and C and B" >
  <constraint path="Gene.mRNAExpressionResults.dataSet.name" op="=" value="BDGP in situ data set" code="B" />
  <constraint path="Gene.organism.name" op="=" value="Drosophila melanogaster" code="C" />
  <constraint path="Gene" op="LOOKUP" value="runt" code="A" />
</query>
```
2. export
3. FASTA

```
Pale Moon can't find the file at http://beta.flymine.org/beta/service/query/results/fasta?query=<query model="genomic" view="Gene.name Gene.mRNAExpressionResults.stageRange Gene.mRNAExpressionResults.expressed Gene.mRNAExpressionResults.mRNAExpressionTerms.name Gene.mRNAExpressionResults.dataSet.dataSource.name Gene.locations.start Gene.locations.end Gene.locations.strand" sortOrder="Gene.name ASC" constraintLogic="A and C and B" ><constraint path="Gene.mRNAExpressionResults.dataSet.name" op="=" value="BDGP in situ data set" code="B" /><constraint path="Gene.organism.name" op="=" value="Drosophila melanogaster" code="C" /><constraint path="Gene" op="LOOKUP" value="runt" code="A" /></query>&format=fasta&start=0&filename=results&token=o1R42d65T1VbKa7be8le.
```

**Comment by julie-sullivan** [comment]
beta flymine fell over again:

> java.lang.OutOfMemoryError: PermGen space

This is probably the highest priority.

**Comment by julie-sullivan** [comment]
Sometimes the summary popups won't go away on the query results.

pops

**Comment by alexkalderimis** [comment]
What JVM is beta running on? Anything interesting in the logs? How much perm gen space is there?
On 14 May 2015 12:34 pm, Julie Sullivan <notifications@github.com> wrote:beta flymine fell over again:


java.lang.OutOfMemoryError: PermGen space


This is probably the highest priority.

**Comment by julie-sullivan** [comment]
Java

```
flymine@met1:/webapp/apache-tomcat-7.0.52/logs$ java -version
java version "1.6.0_26"
Java(TM) SE Runtime Environment (build 1.6.0_26-b03)
Java HotSpot(TM) 64-Bit Server VM (build 20.1-b02, mixed mode)
```
LOGs

Rachel was running a bunch of invalid range queries right before the last incident. However it's happened several times. And the logs of course don't tell me what is causing it.

```
2015-05-14 12:33:02 ERROR org.intermine.webservice.server.WebService     - Service failed by internal error. Request parameters: 
query: <query model="genomic" view="Gene.childFeatures.id" ><constraint path="Gene.id" op="=" value="7503576" /></query>
format: jsoncount
java.lang.OutOfMemoryError: PermGen space

2015-05-14 12:33:09 ERROR org.intermine.webservice.server.WebService     - Service failed by internal error. Request parameters: 
query: <query model="genomic" view="Gene.synonyms.id" ><constraint path="Gene.id" op="=" value="7503576" /></query>
format: jsoncount
java.lang.OutOfMemoryError: PermGen space

2015-05-14 12:33:11 ERROR org.intermine.webservice.server.WebService     - Service failed by internal error. Request parameters: 
query: <query model="genomic" view="Gene.diseases.id" ><constraint path="Gene.id" op="=" value="7503576" /></query>
format: jsoncount
java.lang.OutOfMemoryError: PermGen space

2015-05-14 12:33:13 ERROR org.intermine.webservice.server.WebService     - Service failed by internal error. Request parameters: 
query: <query model="genomic" view="Gene.goAnnotation.id" ><constraint path="Gene.id" op="=" value="7503576" /></query>
format: jsoncount
java.lang.OutOfMemoryError: PermGen space

2015-05-14 12:33:17 ERROR org.intermine.webservice.server.WebService     - Service failed by internal error. Request parameters: 
start: 0
size: 250
query: <query model="genomic" view="Protein.primaryIdentifier" sortOrder="Protein.primaryIdentifier ASC" ><constraint path="Protein" op="LOOKUP" value="lola*" extraValue="" code="A" /></query>
format: json
java.lang.OutOfMemoryError: PermGen space

2015-05-14 12:33:20 ERROR org.intermine.webservice.server.WebService     - Service failed by internal error. Request parameters: 
query: <query model="genomic" view="Gene.locatedFeatures.id" ><constraint path="Gene.id" op="=" value="7503576" /></query>
format: jsoncount
java.lang.OutOfMemoryError: PermGen space

2015-05-14 12:33:22 INFO  org.intermine.objectstore.intermine.ObjectStoreInterMineImpl     - Creating temporary table Integer_bag_33816 of size 387 for SELECT a1_ FROM org.intermine.model.InterMineObject AS a1_ WHERE a1_.id IN ?
2015-05-14 12:33:24 ERROR org.intermine.webservice.server.WebService     - Service failed by internal error. Request parameters: 
query: <query model="genomic" view="Protein.primaryIdentifier" sortOrder="Protein.primaryIdentifier ASC" ><constraint path="Protein" op="LOOKUP" value="lola*" extraValue="" code="A" /></query>
format: jsoncount
java.lang.OutOfMemoryError: PermGen space

2015-05-14 12:33:25 INFO  org.intermine.objectstore.intermine.ObjectStoreInterMineImpl     - Creating temporary table Integer_bag_33817 of size 387 for SELECT a1_ FROM org.intermine.model.InterMineObject AS a1_ WHERE a1_.id IN ?
2015-05-14 12:33:27 ERROR org.intermine.webservice.server.WebService     - Service failed by internal error. Request parameters: 
query: <query model="genomic" view="Protein.primaryIdentifier Protein.id" sortOrder="Protein.primaryIdentifier ASC" ><constraint path="Protein" op="LOOKUP" value="lola*" extraValue="" code="A" /></query>
summaryPath: Protein.id
format: jsonrows
java.lang.OutOfMemoryError: PermGen space
```

$ANT_OPTS
> -server -XX:MaxPermSize=512M -Xmx50000m -XX:+UseParallelGC

**Comment by alexkalderimis** [comment]
The null value constraint issue is a problem with the intermine pathquery engine. The tables are generating the correct query:

```xml
<query model="genomic" view="Gene.primaryIdentifier Gene.proteins.primaryAccession Gene.proteins.isUniprotCanonical" sortOrder="Gene.primaryIdentifier ASC" >
  <constraint path="Gene.proteins.isUniprotCanonical" op="ONE OF" >
    <nullValue/>
    <value>false</value>
  </constraint>
</query>
```

But the result returned do not include any nulls. Interestingly, on string columns that include nulls, the query engine behaves correctly.

**Comment by alexkalderimis** [comment]
fasta/gff3 issue fixed with imtables@2.0.0-beta31

**Comment by alexkalderimis** [comment]
Regarding the blank summary above - I think it is to do with the very expensive summary (performing stats on over 800k publication IDs).

**Comment by alexkalderimis** [comment]
@sergiocontrino Thanks for the walk-through. 

This issue is due to the following: when you change the operator, the value is preserved. If you change the operator before providing a value, then the value `null` is promoted to the values `[null]`

**Comment by alexkalderimis** [comment]
@sergiocontrino The null  value promotion issue is fixed by beta 32

**Comment by alexkalderimis** [comment]
The testmodel is indexing fairly quickly - it's last run was `170712 documents finished in 00:12.641 minutes`, ie. over 13k documents per second. What are flymine's stats?

**Comment by julie-sullivan** [comment]
Can't merge this branch as it is out of date.

**Pull request closed without merging**
