### PR TITLE
Update FASTA on region search

### PR DESCRIPTION
**Pull request by julie-sullivan**
improve text for region search. Refs #1569

### CODE REVIEW

**Comment by julie-sullivan** [comment]
From Gos:

1. Separate top header from bottom. Black header image is too much. Maybe have similar headings: `Results for all regions` `Results per region`.
2. Change text, not all exports are sequences
3. Add tool tips. (but people don't read?)
4. Add breaks between buttons so we have room for explanatory text.

**Comment by justinccdev** [comment]
So on some screen sizes, the export options are now up against the paging options, which I found confusing (see screenshot).
flymine screenshot
My suggestion would be to have each option (export data, export sequences, create list) on separate lines.

Also, fwiw, I find "Export data for all regions" and "Export regions as entire sequences" better as less wordy and it's obviously implied that the export is for all regions (at least for me).

**Comment by julie-sullivan** [comment]
Ugh, I don't like that it wraps, I'll have to shorted the text somehow. 

I am not putting the buttons on new lines because I don't know how. You are welcome to try!

**Comment by justinccdev** [comment]
Okay, this change puts the options on distinct lines.  Please review/test.  If good then might be worth getting a proper webdev to review the changes too.

**Pull request merged**
