### PR TITLE
Biojava

### PR DESCRIPTION
**Pull request by sergiocontrino**
## Details

updates biojava to 4.2 (from 1.7), both for the webapp and for build (fasta)
## Testing
* unit tests passing
* built mine using fasta sources (uniprot-fasta,flybase-dmel-cds-fasta,flybase-dmel-5prime-utr-fasta,flybase-dmel-3prime-utr-fasta,flybase-dmel-gene-fasta)
* built webapp

*Besides running unit tests, how can the reviewer test your feature / bug fix? Are there edge cases to be aware of?*
build
`../bio/scripts/project_build -r -a uniprot-fasta,flybase-dmel-gene-fasta,flybase-dmel-cds-fasta,flybase-dmel-5prime-utr-fasta,flybase-dmel-3prime-utr-fasta -v -b localhost /tmp/test_dmp`

failed (see below). note that 
`uniprot-fasta,flybase-dmel-cds-fasta,flybase-dmel-5prime-utr-fasta,flybase-dmel-3prime-utr-fasta `
and
`flybase-dmel-gene-fasta,flybase-dmel-cds-fasta,flybase-dmel-5prime-utr-fasta,flybase-dmel-3prime-utr-fasta`
both work. seems unrelated, but to check.

```
Caused by: org.intermine.objectstore.ObjectStoreException: Error adding to bag
	at org.intermine.objectstore.intermine.ObjectStoreWriterInterMineImpl.replaceClobWithConnection(ObjectStoreWriterInterMineImpl.java:1340)
	at org.intermine.objectstore.intermine.ObjectStoreWriterInterMineImpl.writePendingClobs(ObjectStoreWriterInterMineImpl.java:1054)
	at org.intermine.objectstore.intermine.ObjectStoreWriterInterMineImpl.storeWithConnection(ObjectStoreWriterInterMineImpl.java:604)
	at org.intermine.objectstore.intermine.ObjectStoreWriterInterMineImpl.store(ObjectStoreWriterInterMineImpl.java:581)
	at org.intermine.dataloader.IntegrationWriterAbstractImpl.store(IntegrationWriterAbstractImpl.java:448)
	at org.intermine.dataloader.IntegrationWriterDataTrackingImpl.shortcut(IntegrationWriterDataTrackingImpl.java:603)
	at org.intermine.dataloader.IntegrationWriterDataTrackingImpl.store(IntegrationWriterDataTrackingImpl.java:263)
	at org.intermine.dataloader.IntegrationWriterAbstractImpl.store(IntegrationWriterAbstractImpl.java:180)
	at org.intermine.dataloader.DirectDataLoader.storeBatch(DirectDataLoader.java:107)
	at org.intermine.dataloader.DirectDataLoader.store(DirectDataLoader.java:79)
	at org.intermine.bio.dataconversion.FastaLoaderTask.processSequence(FastaLoaderTask.java:337)
	... 36 more
Caused by: java.sql.SQLException: Error writing to database, running statement COPY Gene (class, briefDescription, score, description, scoreType, id, symbol, length, name, cytoLocation, primaryIdentifier, secondaryIdentifier, upstreamIntergenicRegionId, downstreamIntergenicRegionId, sequenceOntologyTermId, organismId, chromosomeLocationId, sequenceId, chromosomeId) FROM STDIN BINARY, data size = 1268583
	at org.intermine.sql.writebatch.FlushJobPostgresCopyImpl.flush(FlushJobPostgresCopyImpl.java:58)
	at org.intermine.sql.writebatch.Batch$BatchFlusher.run(Batch.java:461)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: index row size 3408 exceeds maximum 2712 for index "gene__key_primaryidentifier"
  Hint: Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
  Where: COPY gene, line 783
```

## Checklist

Before your pull request can be approved, be sure to check all boxes:

- [x] Passing unit test for new or updated code (if applicable)
- [x] Passes all tests – according to Travis
- [ ] Documentation (if applicable)
- [ ] Single purpose
- [ ] Detailed commit messages
- [ ] Well commented code
- [x] Checkstyle

### CODE REVIEW

**Comment by julie-sullivan** [comment]
@sergiocontrino Failed!

1. that same "saved bag" error you have above.
2. Also the webapp doesn't seem to load.

Specifically it can't find these imports:

https://github.com/intermine/intermine/blob/dev/bio/webapp/src/org/intermine/bio/web/export/GenomicRegionSequenceExporter.java#L23-L26

Should these be updated to the new biojava?

**Comment by julie-sullivan** [comment]
I also get this (on the gradle branch):

```
 [dataLoad] [main] INFO com.zaxxer.hikari.HikariDataSource - HikariCP pool db.production is starting.
 [dataLoad] java.lang.NumberFormatException: For input string: "7227 6239 7165 4932 9606 10090 10116 46245 7230 7244 7217 7220 7222 7238"
 [dataLoad]     at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
 [dataLoad]     at java.lang.Integer.parseInt(Integer.java:580)
 [dataLoad]     at java.lang.Integer.<init>(Integer.java:867)
 [dataLoad]     at org.intermine.bio.dataconversion.FastaLoaderTask.getOrganism(FastaLoaderTask.java:256)
 [dataLoad]     at org.intermine.bio.dataconversion.FastaLoaderTask.processSequence(FastaLoaderTask.java:271)
 [dataLoad]     at org.intermine.bio.dataconversion.FastaLoaderTask.processFile(FastaLoaderTask.java:217)
 [dataLoad]     at org.intermine.task.FileDirectDataLoaderTask.process(FileDirectDataLoaderTask.java:50)
```

**Comment by julie-sullivan** [comment]
Sergio to fix the FASTA export on the region search. To get it working for now:

1. Comment out the fasta search in the region search, make sure code compiles.
2. Fix the getIdentifiers() in the flybase fasta source. It's using the whole header instead of the identifier!

**Comment by julie-sullivan** [comment]
@sergiocontrino We still have a mix of biojava versions 3 and 4. Is that going to cause conflicts?

```
./bio/core/main/lib/biojava-core-4.2.0.jar
./bio/core/main/lib/biojava3-core-3.0.5.jar
```

**Comment by julie-sullivan** [comment]
To test:

- [ ] Database build
- [ ] Unit tests (travis may be lying!)
- [ ] Verify data is correct
- [ ] Deploy webapp
- [ ] FASTA export works as expected

@sergiocontrino Is there anything else that biojava is used for (Besides PDB). Any tricky bits to look out for? 

What did we decide about the case of the residues? 

Also, great job on this! We were way overdue for an update!

**Comment by julie-sullivan** [comment]
@sergiocontrino I am still getting the error listed in the description above, error with the gene identifier. It looks like it's taking the entire header instead of parsing out the identifier. Ideas on how to fix?

**Comment by sergiocontrino** [comment]
removed obsolete libs. the issue seems to fixed now. tested load with all the fasta sources for dmel (not the humanmine ncbi though). webapp appears to work as expected.

**Comment by sergiocontrino** [comment]
it breaks the extension feature for adding flanking regions to fasta sequences! see #1809

**Comment by sergiocontrino** [comment]
verified that the fasta export works with extension from region search and webservice.

**Comment by julie-sullivan** [comment]
I can do this:

1. load a flymine FASTA source
2. deploy webapp 

AND

1. load a humanmine source (i used ncbi-gene)
2. deploy a webapp

I cannot do this:

1. load ncbi-fasta (human)
2. deploy a humanmine webapp

I get this error:

```
retrieve-objectstore-summary:
[summarise-objectstore] [main] INFO com.zaxxer.hikari.HikariDataSource - HikariCP pool db.production is starting.
[summarise-objectstore] summarising objectstore...
java.lang.OutOfMemoryError: Java heap space
Dumping heap to /tmp/java_pid7385.hprof ...
Heap dump file created [3693247082 bytes in 16.054 secs]

BUILD FAILED
/local-data/git/intermine/imbuild/application.xml:29: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuffer.append(StringBuffer.java:270)
	at org.intermine.objectstore.ObjectStoreSummary.toProperties(ObjectStoreSummary.java:407)
	at org.intermine.task.SummariseObjectStoreTask.execute(SummariseObjectStoreTask.java:94)
```

I didn't analyse the dump file.

**Comment by julie-sullivan** [comment]
Also, the number of chromosomes is incorrect:

```
humanmine=# select primaryidentifier from chromosome;
 primaryidentifier 
-------------------
 11
 14
 15
 18
 19
 20
 4
 5
 8
 MT
(10 rows)
```

I think people have more lol.

**Comment by julie-sullivan** [comment]
I get this error:

```
18361 [http-nio-8080-exec-3] ERROR org.intermine.web.struts.InterMineExceptionHandler  - java.lang.NullPointerException
        at org.intermine.bio.web.logic.GenomicRegionSearchQueryRunner.getChromosomeInfo(GenomicRegionSearchQueryRunner.java:305)
        at org.intermine.bio.web.logic.GenomicRegionSearchService.getChromosomeInfomationMap(GenomicRegionSearchService.java:765)
        at org.intermine.bio.web.logic.GenomicRegionSearchService.setupWebData(GenomicRegionSearchService.java:145)
        at org.intermine.bio.web.struts.GenomicRegionSearchOptionsController.execute(GenomicRegionSearchOptionsController.java:57)
        at org.apache.struts.tiles.actions.TilesAction.execute(TilesAction.java:76)
```

What I did:

1. pull in updates to github branch biojava
2. run `fasta` data sources for flymine. (the command mentioned in the pull request description)
3. deployed webapp. did a clean!
4. clicked on region search tab.

**Comment by julie-sullivan** [comment]
All of the fasta tests fail for me. Can you try locally? Travis seems to be happy but I don't think it runs the bio-sources tests. 

```
   testFastaLoad        Failure expected:<2> but was:<0>
                                junit.framework.AssertionFailedError: expected:<2> but was:<0>
                                at org.intermine.bio.dataconversion.FastaLoaderTaskTest.testFastaLoad(FastaLoaderTaskTest.java:104)
```

**Comment by julie-sullivan** [comment]
Refs #83

**Pull request merged**
