### PR TITLE
Java 8

### PR DESCRIPTION
**Pull request by danielabutano**
fix https://github.com/intermine/intermine/issues/1343
Updated LazyCollection and SingletonResult as discussed

### CODE REVIEW

**Comment by julie-sullivan** [comment]
@danielabutano is this backwards compatible with older Java versions?

**Comment by danielabutano** [comment]
yes, of course

**Comment by sammyjava** [comment]
This update (I'm pretty sure it's this one of the May 12 updates) has broken SequenceProcessor in chado-db, a variation of which I use. I've reverted back to April 26 14:07:28 (Julie: footer tweaks) and this problem goes away; I pulled back to May 12 16:52:32 (Julie: merge Java 8) and my data source throws the following stack trace during integration of data into the production database:
```
     [echo] 
     [echo]       Loading chado-genomics (legfed-chado-db) tgt items into production DB
     [echo]     
[integrate] [main] INFO com.zaxxer.hikari.HikariDataSource - HikariCP pool db.production is starting.
[integrate] [main] INFO com.zaxxer.hikari.HikariDataSource - HikariCP pool db.common-tgt-items is starting.
[integrate] Creating index: CREATE INDEX Chromosome__key_primaryidentifier ON Chromosome (primaryIdentifier)
[integrate] Creating index: CREATE INDEX Organism__key_taxonid ON Organism (taxonId)
[integrate] Creating index: CREATE INDEX Ontology__key_name ON Ontology (name)
[integrate] Creating index: CREATE INDEX PolypeptideDomain__key_primaryidentifier ON PolypeptideDomain (primaryIdentifier)
[integrate] Creating index: CREATE INDEX SOTerm__key_name ON SOTerm (name)
[integrate] Creating index: CREATE INDEX OntologyTerm__key_name ON OntologyTerm (name)
[integrate] Creating index: CREATE INDEX GeneticMarker__key_primaryidentifier ON GeneticMarker (primaryIdentifier, organismid)
[integrate] Creating index: CREATE INDEX ConsensusRegion__key_primaryidentifier ON ConsensusRegion (primaryIdentifier)

BUILD FAILED
/home/intermine/intermine/imbuild/integrate.xml:54: The following error occurred while executing this line:
/home/intermine/intermine/imbuild/source.xml:330: java.lang.RuntimeException: java.lang.ClassCastException: org.intermine.objectstore.query.SingletonResults cannot be cast to java.util.Set
	at org.intermine.dataconversion.ItemToObjectTranslator.translateFromDbObject(ItemToObjectTranslator.java:418)
	at org.intermine.objectstore.translating.ObjectStoreTranslatingImpl.execute(ObjectStoreTranslatingImpl.java:167)
	at org.intermine.objectstore.fastcollections.ObjectStoreFastCollectionsForTranslatorImpl.execute(ObjectStoreFastCollectionsForTranslatorImpl.java:193)
	at org.intermine.dataloader.BatchingFetcher$NoseyObjectStore.execute(BatchingFetcher.java:580)
	at org.intermine.objectstore.query.ResultsBatches.fetchBatchFromObjectStore(ResultsBatches.java:193)
	at org.intermine.objectstore.query.PrefetchManager.doRequest(PrefetchManager.java:241)
	at org.intermine.objectstore.query.PrefetchManager.doRequest(PrefetchManager.java:236)
	at org.intermine.objectstore.query.PrefetchManager.doRequest(PrefetchManager.java:146)
	at org.intermine.objectstore.query.ResultsBatches.getBatch(ResultsBatches.java:164)
	at org.intermine.objectstore.query.ResultsBatches.getRowsFromBatch(ResultsBatches.java:139)
	at org.intermine.objectstore.query.Results.range(Results.java:197)
	at org.intermine.objectstore.query.SingletonResults.range(SingletonResults.java:65)
	at org.intermine.objectstore.query.Results.get(Results.java:226)
	at org.intermine.objectstore.query.Results$Iter.hasNext(Results.java:378)
	at org.intermine.dataloader.ObjectStoreDataLoader.process(ObjectStoreDataLoader.java:135)
	at org.intermine.dataloader.ObjectStoreDataLoader.process(ObjectStoreDataLoader.java:60)
	at org.intermine.dataloader.ObjectStoreDataLoaderTask.execute(ObjectStoreDataLoaderTask.java:128)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:442)
	at org.intermine.task.Integrate.performAction(Integrate.java:219)
	at org.intermine.task.Integrate.performAction(Integrate.java:132)
	at org.intermine.task.Integrate.execute(Integrate.java:123)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.Main.runBuild(Main.java:809)
	at org.apache.tools.ant.Main.startAnt(Main.java:217)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.lang.ClassCastException: org.intermine.objectstore.query.SingletonResults cannot be cast to java.util.Set
	at org.intermine.model.bio.ExonShadow.setFieldValue(ExonShadow.java:411)
	at org.intermine.dataconversion.ItemToObjectTranslator.translateFromDbObject(ItemToObjectTranslator.java:402)
	... 48 more
```
I'm running:
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

I'm pretty sure you'll be able to reproduce this if you run chado-db/SequenceProcessor in FlyMine.

**Comment by sammyjava** [comment]
I'll note that no sources under chado-db are referenced in the stack trace. The error appears to originate in org.intermine.dataconversion.ItemToObjectTranslator OR maybe it's a Java version, since I'm running 8 and maybe you removed the -source 1.6 somewhere? And this class isn't Java-8 compatible? Just a guess. I'll sit on the April 26 14:07:28 revision, but I'm happy to try out any updates.

**Comment by sammyjava** [comment]
OK, more info:" it's definitely this specific commit. I reverted to just the May 12 11:02:05 push (Julie: Merge branch 'dev'...) and we're fine. So it's definitely this specific merge/push: https://github.com/intermine/intermine/commit/729bfcd8bb2ecb4def5c383a12be8f4509a0c95a.

**Pull request merged**
