### PR TITLE
modify SolrIndexHandler to support newer Solr versions

### LINKED ISSUE #1970: Solr: can't use version 7.5.0 (only 7.2.1 works)
```
 Task :dbmodel:postProcess
Performing postprocess create-search-index.
[corePostProcess] SLF4J: Class path contains multiple SLF4J bindings.
[corePostProcess] SLF4J: Found binding in [jar:file:/home/shokin/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.7/8095d0b9f7e0a9cd79a663c740e0f8fb31d0e2c8/slf4j-simple-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[corePostProcess] SLF4J: Found binding in [jar:file:/home/shokin/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-jdk14/1.7.10/13675a57601d9106fe82314fe9eebb9b2d9b13c6/slf4j-jdk14-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[corePostProcess] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[corePostProcess] SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
[corePostProcess] [Task worker for ':'] INFO com.zaxxer.hikari.HikariDataSource - db.production - Starting...
[corePostProcess] [Task worker for ':'] INFO com.zaxxer.hikari.HikariDataSource - db.production - Start completed.
[corePostProcess] Creating index for keyword search...
[corePostProcess] Creating keyword index failed
[corePostProcess] org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteExecutionException: Error from server at http://localhost:8983/solr/beanmine-search: error processing commands
[corePostProcess]       at org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteExecutionException.create(HttpSolrClient.java:829)
[corePostProcess]       at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:620)
[corePostProcess]       at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:255)
[corePostProcess]       at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:244)
[corePostProcess]       at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:194)
[corePostProcess]       at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:211)
[corePostProcess]       at org.intermine.api.searchengine.solr.SolrIndexHandler.createFieldTypeDefinitions(SolrIndexHandler.java:304)
[corePostProcess]       at org.intermine.api.searchengine.solr.SolrIndexHandler.createIndex(SolrIndexHandler.java:65)
[corePostProcess]       at org.intermine.bio.postprocess.CreateSearchIndexProcess.postProcess(CreateSearchIndexProcess.java:66)
[corePostProcess]       at org.intermine.task.PostProcessorTask.execute(PostProcessorTask.java:70)
[corePostProcess]       at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[corePostProcess]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[corePostProcess]       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[corePostProcess]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[corePostProcess]       at java.lang.reflect.Method.invoke(Method.java:498)
[corePostProcess]       at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[corePostProcess]       at groovy.util.AntBuilder.performTask(AntBuilder.java:327)
[corePostProcess]       at groovy.util.AntBuilder.nodeCompleted(AntBuilder.java:272)
[corePostProcess]       at groovy.util.BuilderSupport.doInvokeMethod(BuilderSupport.java:154)
[corePostProcess]       at groovy.util.AntBuilder.doInvokeMethod(AntBuilder.java:207)
[corePostProcess]       at groovy.util.BuilderSupport.invokeMethod(BuilderSupport.java:67)
[corePostProcess]       at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
[corePostProcess]       at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
[corePostProcess]       at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
[corePostProcess]       at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
[corePostProcess]       at org.intermine.plugin.postprocess.PostProcessPlugin$_apply_closure2$_closure6$_closure7.doCall(PostProcessPlugin.groovy:127)
[corePostProcess]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[corePostProcess]       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[corePostProcess]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[corePostProcess]       at java.lang.reflect.Method.invoke(Method.java:498)
[corePostProcess]       at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
[corePostProcess]       at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
[corePostProcess]       at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
[corePostProcess]       at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
[corePostProcess]       at groovy.lang.Closure.call(Closure.java:414)
[corePostProcess]       at groovy.lang.Closure.call(Closure.java:430)
[corePostProcess]       at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2040)
[corePostProcess]       at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2025)
[corePostProcess]       at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2066)
[corePostProcess]       at org.codehaus.groovy.runtime.dgm$162.invoke(Unknown Source)
[corePostProcess]       at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
[corePostProcess]       at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
[corePostProcess]       at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
[corePostProcess]       at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
[corePostProcess]       at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
[corePostProcess]       at org.intermine.plugin.postprocess.PostProcessPlugin$_apply_closure2$_closure6.doCall(PostProcessPlugin.groovy:67)
[corePostProcess]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[corePostProcess]       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[corePostProcess]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[corePostProcess]       at java.lang.reflect.Method.invoke(Method.java:498)
[corePostProcess]       at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
[corePostProcess]       at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
[corePostProcess]       at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
[corePostProcess]       at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
[corePostProcess]       at groovy.lang.Closure.call(Closure.java:414)
[corePostProcess]       at groovy.lang.Closure.call(Closure.java:430)
[corePostProcess]       at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:681)
[corePostProcess]       at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:656)
[corePostProcess]       at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
[corePostProcess]       at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
[corePostProcess]       at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
[corePostProcess]       at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
[corePostProcess]       at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
[corePostProcess]       at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
[corePostProcess]       at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
[corePostProcess]       at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
[corePostProcess]       at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
[corePostProcess]       at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
[corePostProcess]       at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
[corePostProcess]       at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
[corePostProcess]       at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
[corePostProcess]       at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
[corePostProcess]       at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
[corePostProcess]       at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
[corePostProcess]       at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
[corePostProcess]       at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
[corePostProcess]       at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
[corePostProcess]       at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
[corePostProcess]       at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
[corePostProcess]       at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
[corePostProcess]       at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
[corePostProcess]       at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
[corePostProcess]       at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
[corePostProcess]       at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
[corePostProcess]       at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
[corePostProcess]       at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
[corePostProcess]       at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
[corePostProcess]       at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
[corePostProcess]       at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
[corePostProcess]       at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
[corePostProcess]       at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
[corePostProcess]       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[corePostProcess]       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[corePostProcess]       at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
[corePostProcess]       at java.lang.Thread.run(Thread.java:748)


BUILD SUCCESSFUL in 7s
8 actionable tasks: 5 executed, 3 up-to-date
[Thread-41] INFO com.zaxxer.hikari.HikariDataSource - db.production - Shutdown initiated...
[Thread-41] INFO com.zaxxer.hikari.HikariDataSource - db.production - Shutdown completed.


AND

Performing postprocess create-autocomplete-index.
[corePostProcess] SLF4J: Class path contains multiple SLF4J bindings.
[corePostProcess] SLF4J: Found binding in [jar:file:/home/shokin/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.7/8095d0b9f7e0a9cd79a663c740e0f8fb31d0e2c8/slf4j-simple-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[corePostProcess] SLF4J: Found binding in [jar:file:/home/shokin/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-jdk14/1.7.10/13675a57601d9106fe82314fe9eebb9b2d9b13c6/slf4j-jdk14-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[corePostProcess] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[corePostProcess] SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
[corePostProcess] [Task worker for ':'] INFO com.zaxxer.hikari.HikariDataSource - db.production - Starting...
[corePostProcess] [Task worker for ':'] INFO com.zaxxer.hikari.HikariDataSource - db.production - Start completed.
[corePostProcess] create autocomplete index ...
[corePostProcess] Indexing SOTerm.name
[corePostProcess] Indexing OntologyTerm.name


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dbmodel:postProcess'.
> org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteExecutionException: Error from server at http://localhost:8983/solr/beanmine-autocomplete: error processing commands

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dbmodel:postProcess'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: : org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteExecutionException: Error from server at http://localhost:8983/solr/beanmine-autocomplete: error processing commands
        at org.intermine.task.PostProcessorTask.execute(PostProcessorTask.java:73)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.intermine.plugin.postprocess.PostProcessPlugin$_apply_closure2$_closure6$_closure7.doCall(PostProcessPlugin.groovy:127)
        at org.intermine.plugin.postprocess.PostProcessPlugin$_apply_closure2$_closure6.doCall(PostProcessPlugin.groovy:67)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:681)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:656)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 27 more
Caused by: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteExecutionException: Error from server at http://localhost:8983/solr/beanmine-autocomplete: error processing commands
        at org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteExecutionException.create(HttpSolrClient.java:829)
        at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:620)
        at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:255)
        at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:244)
        at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:194)
        at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:211)
        at org.intermine.web.autocompletion.AutoCompleter.buildIndex(AutoCompleter.java:244)
        at org.intermine.bio.postprocess.CreateAutocompleteIndexProcess.postProcess(CreateAutocompleteIndexProcess.java:53)
        at org.intermine.task.PostProcessorTask.execute(PostProcessorTask.java:70)
        ... 40 more


* Get more help at https://help.gradle.org

BUILD FAILED in 9s
8 actionable tasks: 5 executed, 3 up-to-date
[Thread-41] INFO com.zaxxer.hikari.HikariDataSource - db.production - Shutdown initiated...
[Thread-41] INFO com.zaxxer.hikari.HikariDataSource - db.production - Shutdown completed. 
```

### PR DESCRIPTION
**Pull request by arunans23**
## Details
I have added multiple conditions to check whether same Field names are added to Solr ManagedSchema again and again. 

Basically following three updates are validated : 
- FieldTypeDefinitions
- Fields
- CopyFields

*Summary of pull request, including references to relevant tickets (if applicable).*
Resolves #1970 

## Testing
Tested with Solr 7.2.1 and Solr 7.6.0

## Checklist

Before your pull request can be approved, be sure to check all boxes:

- [x] Passing unit test for new or updated code (if applicable)
- [x] Passes all tests – according to Travis
- [ ] Documentation (if applicable)
- [x] Detailed commit messages
- [x] Single purpose
- [ ] Well commented code
- [x] Checkstyle

### CODE REVIEW

**Comment by julie-sullivan** [comment]
@danielabutano Can you test this?

@arunans23 This is SO helpful! Thanks so much for this! Can you summarise (briefly) why this change was needed? In later Solr versions, the indexing fails if the index already exists. The Solr version we have now doesn't care. Is that right?

Can you also suggest some tests for us. What should we look out for specifically? edge cases? e.g. if something were to go wrong with this pull request, what would it be?

**Comment by arunans23** [comment]
@julie-sullivan 
It is not index that causes the problem. It is the definitions that we create in the managed_schema file of the Solr collection.  Each data we index in Solr has to have a field name, and every field name has attributes like field type definition.

For eg: 
`<field name="ontologyterm_name" type="analyzed_string" multiValued="true" indexed="true" required="false" stored="false"/>`

An example of type definition would be : 
```
<fieldType name="analyzed_string" class="solr.TextField" positionIncrementGap="100" multiValued="true">
    <analyzer type="index">
      <tokenizer class="solr.WhitespaceTokenizerFactory"/>
      <filter class="solr.LowerCaseFilterFactory"/>
    </analyzer>
    <analyzer type="query">
      <tokenizer class="solr.WhitespaceTokenizerFactory"/>
      <filter class="solr.LowerCaseFilterFactory"/>
    </analyzer>
  </fieldType>
```
These schema details has to be included in the managed_schema before we start the indexing process. (Solr has the capability to automatically create this by analyzing the data, but it is prone to errors and we cannot expect what the data type will turn out to be). This is where the issue came. In Solr 7.2.1, if I add a same fieldtype with the same name, it would not care. But in the newer versions it returns an error. To overcome the issue now I am retrieving a list of field types from the Solr and I check whether the field name is already there. If it is there I skip the field name adding part. 

After all of this is done, the indexing process will start and it will run smoothly. People who are experts in Solr, they manage the schema file manually. They add whatever parameters to the field types that suits them. But when I was upgrading Intermine from Lucene to Solr, I tried to handle everything through code. Hence no one has to go and touch the managed_schema file.

Some edge cases to test would be to run the Indexing process after changing the data files. First you run an Indexing process. And then you change the field names (add or delete fields) and re-run the process. My understanding is that this will work. (But you never know!!)

**Comment by danielabutano** [comment]
Thanks @arunans23 for this fix!! We really appreciate your great contributions to the project. @julie-sullivan I have code reviewed and tested either with solr7.2.1 and solr 7.7.0 (the latest released).
I have tested:
- the postprocesses create-autocomplete-index and create-serch-index
- search functionality
- autocomplete functionality
- template filter
Everything works fine! Thank you Arunan!
I think we can merge it. We have only to change the release number from 3.1.1 to 3.1.2

**Comment by julie-sullivan** [comment]
@arunans23 is the best!!! :D

**Pull request merged**
