### PR TITLE
New jsp jars

### PR DESCRIPTION
**Pull request by sergiocontrino**
as requested by AIP and for tomcat 8 compatibility

### CODE REVIEW

**Comment by justinccdev** [comment]
Build fails with following error

do-compile-without-gen-src:
    [javac] Compiling 58 source files to /local-homes/justincc/jc/resources/k/knowledge/science-natural/biology/genetics/bioinformatics/data/warehousing/intermine/src/intermine-github/intermine/web/test/build/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
    [javac] /local-homes/justincc/jc/resources/k/knowledge/science-natural/biology/genetics/bioinformatics/data/warehousing/intermine/src/intermine-github/intermine/web/test/src/org/intermine/MockHttpRequest.java:24: error: MockHttpRequest is not abstract and does not override abstract method <T>upgrade(Class<T>) in HttpServletRequest
    [javac] public class MockHttpRequest implements HttpServletRequest
    [javac]        ^
    [javac]   where T is a type-variable:
    [javac]     T extends HttpUpgradeHandler declared in method <T>upgrade(Class<T>)
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error
    [javac] 1 warning

it looks like Tomcat 8 has added a new method that needs to be mocked out.

**Comment by julie-sullivan** [comment]
I couldn't replicate @justinccdev, everything compiled and deployed fine. However, when I went to the home page, I got this error:

```
02-Sep-2015 14:08:04.186 SEVERE [http-nio-8080-exec-12] org.apache.catalina.core.ApplicationDispatcher.invoke Servlet.service() for servlet jsp threw exception
 org.apache.jasper.JasperException: The absolute uri: http://java.sun.com/jsp/jstl/core cannot be resolved in either web.xml or the jar files deployed with this application
```
Worked fine with Tomcat 7.

@sergiocontrino Were you able to successfully deploy a webapp using Tomcat 8?

**Comment by julie-sullivan** [comment]
This is causing a few tests to fail. Those will need to be fixed before this is merged.

**Comment by justinccdev** [comment]
Travis builds show same build error that I was seeing.

**Comment by sergiocontrino** [comment]
this is now passing travis tests

**Comment by julie-sullivan** [comment]
deploys fine, everything seems to be working fine.

**Pull request merged**
