### PR TITLE
Report page: Null pointer exception when inline lists are configured but there's no data

### PR DESCRIPTION
**Pull request by sneuhaus**
Prevent null objects from being added to the linline list collection.

### CODE REVIEW

**Comment by julie-sullivan** [comment]
@sneuhaus Thanks! We got some checkstyle errors: 

```
FILE: /home/travis/build/intermine/intermine/intermine/web/main/src/org/intermine/web/logic/results/InlineList.java

  line:   54, column:   - - warning - if at indentation level 10 not at correct indentation, 12

  line:   54, column:  13 - warning - 'if' is not followed by whitespace.

  line:   54, column:  33 - warning - '{' is not preceded with whitespace.

  line:   55, column:   - - warning - if child at indentation level 12 not at correct indentation, 16

  line:   57, column:   - - warning - if child at indentation level 12 not at correct indentation, 16

  line:   58, column:   - - warning - if child at indentation level 12 not at correct indentation, 16

  line:   59, column:   - - warning - try at indentation level 12 not at correct indentation, 16

  line:   61, column:   - - warning - try child at indentation level 16 not at correct indentation, 20

  line:   62, column:   - - warning - try child at indentation level 16 not at correct indentation, 20

  line:   63, column:   - - warning - try rcurly at indentation level 12 not at correct indentation, 16

  line:   64, column:   - - warning - catch child at indentation level 16 not at correct indentation, 20

  line:   64, column:   - - warning - method call child at indentation level 16 not at correct indentation, 20

  line:   65, column:   - - warning - catch rcurly at indentation level 12 not at correct indentation, 16

  line:   68, column:   - - warning - if child at indentation level 12 not at correct indentation, 16

  line:   69, column:   - - warning - assign child at indentation level 16 not at correct indentation, 20

  line:   71, column:   - - warning - if child at indentation level 12 not at correct indentation, 16

  line:   71, column:   - - warning - method call child at indentation level 12 not at correct indentation, 16

  line:   72, column:   - - warning - if rcurly at indentation level 10 not at correct indentation, 12

  line:   72, column:  12 - warning - 'else' is not preceded with whitespace.

  line:   72, column:  12 - warning - '}' is not followed by whitespace.

  line:   72, column:  16 - warning - 'else' is not followed by whitespace.

  line:   72, column:  16 - warning - '{' is not preceded with whitespace.

  line:   73, column:   - - warning - Line is longer than 100 characters (found 113).

  line:   73, column:   - - warning - Line matches the illegal pattern 'System\.out\.println'.

  line:   74, column:   - - warning - else rcurly at indentation level 10 not at correct indentation, 12
```

Can you fix? You can run the `checkstyle` target to test.

Or I can make the change, let me know!

**Comment by julie-sullivan** [comment]
Thanks!! That fixed it. :)

Also, how would you suggest I test this change?

**Comment by sneuhaus** [comment]
@julie-sullivan 

We found the bug when we added a reference to the BioEntity class

 <reference name="earliestPublication" referenced-type="Publication" />

Not all (for example) alleles will have an earliest publication, but most will.
For alleles in the webconfig-model we have an inlinelist configuration
 <inlinelist>
      <table path="earliestPublication.citation" showInHeader="true" lineLength="200" showLinksToObjects="true" />
 </inlinelist>

When viewing an allele page for an allele with no earliest publication, the code was trying to call a method to get the citation field for a publication where the publication object was null.

Hope that explains things.

Steve.

**Comment by julie-sullivan** [comment]
@sneuhaus Can you clarify something for me? Here is a random human gene in flymine:

http://www.flymine.org/flymine/portal.do?class=Gene&externalids=5468

Here's where we have inline list configuration for probesets:

https://github.com/intermine/intermine/blob/beta/flymine/webapp/resources/webapp/WEB-INF/webconfig-model.xml#L143

We don't load probesets for human genes, so this will always be null. But the report page for human genes loads fine. I thought it might be because of the `showInHeader="true"` so I added that and the page still loads correctly.

I'll test other types since this is a gene and you are testing bioentities.

**Comment by julie-sullivan** [comment]
@sneuhaus Oh, I just looked at the actual code. It seems like you have null objects in your `BioEntity.earliestPublication` collection? Do you agree? This might be why I can't replicate the problem. If my assumption is correct, then this error shouldn't happen and is a data loading problem.

I could be misunderstanding!

**Comment by sneuhaus** [comment]
@julie-sullivan 
It is entirely possible (quite likely) this is due to us loading the data incorrectly.

**Comment by sneuhaus** [comment]
Once the data is loaded our allele table has a column "earliestpubliation_id" which would normally be a publication id. But for some allele's this is null. It was viewing the details page for such an allele (or other bioentity) that resulted in the NPE.

**Comment by julie-sullivan** [comment]
Hrm. Well I tested probesets which is a collection. Maybe I should test for a reference? Maybe it handles the data differently? I will test.

**Comment by julie-sullivan** [comment]
Oh, do you have the full stacktrace? That might help me replicate too.

**Comment by julie-sullivan** [comment]
Yes, that was it! I was testing collections (which works fine) and it was the reference that was failing. sorry for being slow!

```
java.lang.NullPointerException
	at org.intermine.web.logic.results.InlineList.<init>(InlineList.java:60)
	at org.intermine.web.logic.results.ReportObject.initialiseInlineList(ReportObject.java:635)
	at org.intermine.web.logic.results.ReportObject.initialise(ReportObject.java:810)
	at org.intermine.web.logic.results.ReportObject.getNormalInlineLists(ReportObject.java:916)
	at org.intermine.web.struts.ReportController.execute(ReportController.java:107)
	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)
	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
	at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:449)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
```

**Pull request merged**
