### PR TITLE
2018 08 fixes

### PR DESCRIPTION
**Pull request by justinccdev**
## Details

*Summary of pull request, including references to relevant tickets (if applicable).*

## Testing

*Besides running unit tests, how can the reviewer test your feature / bug fix? Are there edge cases to be aware of?*

## Checklist

Before your pull request can be approved, be sure to check all boxes:

- [ ] Passing unit test for new or updated code (if applicable)
- [ ] Passes all tests – according to Travis
- [ ] Documentation (if applicable)
- [ ] Single purpose
- [ ] Detailed commit messages
- [ ] Well commented code
- [ ] Checkstyle

### CODE REVIEW

**Comment by justinccdev** [comment]
Probably the gradle change doesn't need to go in 2.0, we just have to be live with the fact that it won't build on Ubuntu 18.04 since the version reported by the Java it ships with (10.0.2) can't be properly interpreted by Gradle 4.1.

**Comment by justinccdev** [comment]
Not sure why the xml parser casting failed in the build.  Might be affected by the gradle update so probably another good reason not to merge this.

**Comment by julie-sullivan** [comment]
@justinccdev Okay to close this then?

**Comment by justinccdev** [comment]
sure

**Pull request closed without merging**
