### PR TITLE
789 ws query defaults

### PR DESCRIPTION
**Pull request by sergiocontrino**
adds and tests the possibility of adding default queries to iodocs. hopefully solves checkstyle error in previous pull attempt.

### CODE REVIEW

**Comment by julie-sullivan** [comment]
@sergiocontrino Can you add some docs on how to do this?

**Comment by sergiocontrino** [comment]
@julie-sullivan fine here http://intermine.readthedocs.io/en/latest/web-services/ , in the http api section?

**Comment by julie-sullivan** [comment]
I think so?

**Comment by julie-sullivan** [comment]
That page is more about how to use the web services.

**Comment by sergiocontrino** [comment]
ok, i'll add a short chapter here http://intermine.readthedocs.io/en/latest/webapp/

**Comment by sergiocontrino** [comment]
done a short doc in im-docs, i'll wait pushing to master until release?

**Comment by sergiocontrino** [comment]
ok, doc in master.

**Pull request merged**
