### PR TITLE
removes subtype ban #1296

### PR DESCRIPTION
**Pull request by sergiocontrino**
removed the ban on subtype (#1296). seems fine to me, but please test

### CODE REVIEW

**Comment by julie-sullivan** [comment]
```
BUILD SUCCESSFUL

Total time: 3 minutes 50 seconds

[Thread-88] INFO com.zaxxer.hikari.pool.HikariPool - HikariCP pool db.unittest is shutting down.

CHECKING results

FAILURE: Class org.intermine.web.logic.pathqueryresult.PathQueryResultsHelperTest, method testGetDefaultViewSubClass

junit.framework.AssertionFailedError: No exception thrown when getting default view for subclass, got: [Department.employees.fullTime, Department.employees.age, Department.employees.end, Department.employees.name]

	at org.intermine.web.logic.pathqueryresult.PathQueryResultsHelperTest.testGetDefaultViewSubClass(PathQueryResultsHelperTest.java:166)

2271 tests were run

1 TESTS FAILED


```

Some tests failed @sergiocontrino

**Comment by sergiocontrino** [comment]
@JoelRichardson, we think your #1296 is solved and the patch applied to http://beta.flymine.org
would you be able to test a bit the application to check if there are unintended side effects?
we are doing the same here. thanks!

**Comment by JoelRichardson** [comment]
Thanks @sergiocontrino. I'm not exactly sure what you want me to test. ?

**Comment by sergiocontrino** [comment]
sorry @JoelRichardson, the request is vague and i was a bit hesitant to ask for your help. the task would be to test for abnormal behaviour when using sub classing in queries. regarding the bug, any gene list should produce a working link to go terms now. 
we have not noticed anything wrong up to now, and i was going to propose to merge the fix. 
if you have time to run a couple of additional queries, please let me know if you discover anything. 
thanks!

**Comment by JoelRichardson** [comment]
The converters seem to work. I've run some other queries involving subtype constraints and they seemed to work. Created some lists and did various operations, and the results had the expected types. It all looks good to me. Thanks so much!

**Comment by sergiocontrino** [comment]
thank you for helping @JoelRichardson

**Comment by sergiocontrino** [comment]
ready to merge.

**Pull request merged**
