### PR TITLE
Update JSON lib. Refs #1450

### PR DESCRIPTION
**Pull request by julie-sullivan**
Update JSON lib. Refs #1450

### CODE REVIEW

**Comment by julie-sullivan** [comment]
All the tests are failing, e.g. 

```
ERROR: Class org.intermine.webservice.server.JWTVerifierTest, method testBadToken

java.lang.UnsupportedClassVersionError: org/json/JSONObject

	at org.intermine.webservice.server.JWTBuilder.encodeContent(JWTBuilder.java:165)

	at org.intermine.webservice.server.JWTBuilder.issueToken(JWTBuilder.java:157)

	at org.intermine.webservice.server.JWTBuilder.issueToken(JWTBuilder.java:125)

	at org.intermine.webservice.server.JWTVerifierTest.setup(JWTVerifierTest.java:81)
```

**Comment by justinccdev** [comment]
Versioning errors still occurring in the travis test suite for some reason.  Will need to investigate further.

**Comment by justinccdev** [comment]
Okay, now more of the test suite is passing except for CLIENT=js (some unexplained failure with promises) and ALL (some failure that looks related to the json change).  Both will need more investigation.

**Comment by justinccdev** [comment]
Unsurprisingly, the tests still fail with the same errors, since there's only a small commit delta between the 2 jars and none of those were obviously applicable bug fixes.  Probably the API of JSON-java changed in those 5 years.  Will need further investigation.

**Comment by julie-sullivan** [comment]
Refs #1450

**Comment by sammyjava** [comment]
It's probably the lack of spaces around equals signs. :) *runs away*

**Comment by julie-sullivan** [comment]
ha ha! no. Justin doesn't like checkstyle either! Listen you people, if we don't have rules, then it's anarchy I tell you. ANARCHY.

**Comment by justinccdev** [comment]
I don't mind rules, I just prefer as few as possible :) (indenting, brace placement, not super-super long lines).  I find that some of the current Checkstyle rules are making the code less readable rather than more.

**Comment by justinccdev** [comment]
On futher analysis, it turns out that the code in the existing jar is actually much older than 2011-01-06, possibly as early as 2009-04-14.  This places it early than the beginning of [1].

Frustratingly, I cannot reproduce the CI test success on my local system even with the current jar (either with "ant" in intermine/web/test or with "ant fulltest" in intermine/all.  There may be some ordering dependency in how the CI tests are running which causes them to succeed but local attempts to fail.

Since this change is not critical, we are currently thinking that we will overhaul the build system first before coming back to it, since the overhaul will change the way tests are run anyway, which will hopefully bring the CI and local test running into better alignment.

[1] https://github.com/stleary/JSON-java

**Comment by julie-sullivan** [comment]
closing for now. Revisit after build refactor for InterMine 2.0. See #1450

**Pull request closed without merging**
