### PR TITLE
FAIR: add data licences to model

### PR DESCRIPTION
**Pull request by julie-sullivan**
## Details

* added `DataSet.licence` to the core InterMine data model.
* Looked up licences for the core data model, added the licence (where available) to the data parsers
  * [spreadsheet](https://docs.google.com/spreadsheets/d/1xLTt13gqXZCu22EmDmI6kgswPkPuPIWSrlE7rOkAuvU/edit#gid=0)
* updated flymine's project XML to include licence information
* @danielabutano is writing the blog post and the docs for the wiki. 

Running a build now. 

## Testing

Not much testing to do, was a simple code change. Make sure licence information is correct and queryable and viewable on the report page.

## Checklist

Before your pull request can be approved, be sure to check all boxes:

- [ ] Passing unit test for new or updated code (if applicable)
- [ ] Passes all tests – according to Travis
- [ ] Documentation (if applicable)
- [ ] Single purpose
- [ ] Detailed commit messages
- [ ] Well commented code
- [ ] Checkstyle

### CODE REVIEW

**Comment by julie-sullivan** [comment]
NB: This branch includes the `fair-obo` branch.

**Comment by julie-sullivan** [comment]
To add a licence to a GFF3 data set, use this parameter:

```
<property name="gff3.licence" value="myGFFLicence"/>
```

To add a licence to a data set produced by the FASTA parser, use this parameter:

```
<property name="fasta.licence" value="myFASTALicence"/>
```

For ontologies, or ontology annotations, use this parameter:
```
<property name="licence" value="myRegularLicence"/>
```

**Comment by danielabutano** [comment]
here it still points to 2 https://github.com/julie-sullivan/intermine/blob/fair-obo-licences/bio/postprocess/gradle.properties#L4

**Comment by julie-sullivan** [comment]
beta.humanmine is (temporarily!) hosting a build with licences and ontology terms.

http://beta.humanmine.org/beta/begin.do

**Query for licences**

```
<query name="" model="genomic" view="DataSet.name DataSet.url DataSet.dataSource.name DataSet.licence" longDescription="" sortOrder="DataSet.name asc">
</query>
```

* in the results table and report page, the URLs don't link out. there must be a setting somewhere?
* We don't have very many licences!
* going to build flymine with this branch too.
* there was another ticket for how to display the licences better, maybe templates will help

**Ontology terms in data model**

The model has ontology terms on classes and attributes:

http://beta.humanmine.org/beta/service/model
http://beta.humanmine.org/beta/service/model?format=json

* Based on @rachellyne and my best guesses. These can be changed of course. (at least until we start generating RDF and people start using this!)
* There are some missing terms. Rachel posted a list of missing terms on the other ticket.
* Only annotated the *core* data model. We should also annotate the flymine and humanmine model.

I am running a build now for the strains model change so may have to take this webapp down temporarily to test that. I'll give you notice!

**Comment by danielabutano** [comment]
Great. What about renaming the branch into fair?

**Comment by julie-sullivan** [comment]
tested and merged onto the FAIR branch.

**Pull request closed without merging**
