### PR TITLE
InterMine 1.5.1 - results tables updates

### PR DESCRIPTION
**Pull request by julie-sullivan**
Fix for embiggening issue

### CODE REVIEW

**Comment by julie-sullivan** [comment]
@alexkalderimis  @joshkh  @sergiocontrino 

Bug list:

1. #779 - FASTA (Can't test because extension menu is missing)
2. saving lists work, but message is not there.
3. QB CSS - #1011
4. expand / collapse all subtables icon for outer joins is missing

**Comment by julie-sullivan** [comment]
This query fails:

```
<query model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.proteins.primaryIdentifier Gene.proteins.primaryAccession" sortOrder="Gene.primaryIdentifier ASC" name="Gene_Protein" >
  <constraint path="Gene" op="LOOKUP" value="CG*" extraValue="D. melanogaster" code="A" />
</query>
```
@sergiocontrino Do you think we should pull in the fix? 3896038ddac497e753a77aaf8f2e5f3d33661b61

**Comment by sergiocontrino** [comment]
region search does not display feature types (so cannot work)

**Comment by julie-sullivan** [comment]
@sergiocontrino Could you take a look at the region search problem? We can't really release 1.5.1 with that issue.

**Comment by sergiocontrino** [comment]
list analysis: convert to a different type contains the list itself.
sametyoe

**Comment by julie-sullivan** [comment]
All the bugs are fixed in the above but now we have new ones:

1. Can't view or download widget data

     > [14:16:34.091] TypeError: this.imjs.rows(...).done is not a function @ http://cdn.intermine.org/js/intermine/apps-c/list-widgets/2.1.0/app.min.js:1

1. Templates don't show their totals anymore. So you can click on a template with no results and get an empty result table. Lower priority.

**Comment by alexkalderimis** [comment]
I'll fix that tonight
On 22 May 2015 2:19 pm, Julie Sullivan <notifications@github.com> wrote:All the bugs are fixed in the above but now we have new ones:


Can't view or download widget data


[14:16:34.091] TypeError: this.imjs.rows(...).done is not a function @ http://cdn.intermine.org/js/intermine/apps-c/list-widgets/2.1.0/app.min.js:1

Templates don't show their totals anymore. So you can click on a template with no results and get an empty result table. Lower priority.

**Pull request merged**
