### PR TITLE
to allow https protocol

### PR DESCRIPTION
**Pull request by sergiocontrino**
to be tested. needs update of properties files.

### CODE REVIEW

**Comment by sergiocontrino** [comment]
tested on flymine at
https://beta.flymine.org/beta
needs certified cdn (done by paul b, for now on cdn-dev)  
added 
head.cdn.location = https://cdn-dev.intermine.org
in flymine web.propeties
and all seems fine, apart from the link from feature in the results of the region search, which directs to 
http://met1:8080/beta

**Comment by julie-sullivan** [comment]
@sergiocontrino this isn't working on beta.humanmine. Looks like it's dropping the path? Can you fix?

**Comment by sergiocontrino** [comment]
i have now released beta humanmine from this branch (it has not been done before) and it seems fine.
the issue of the link from feature in the results of the region search has been solved (using the correct baseurl in the properties..)
NOTE: i have not checked in the change of cdn location in the flymine and humanmine web.properties files, we should probably test with  https://cdn.intermine.org when available.
flymine has been released again as well. 
it seems also that flymine has been redeployed with the wrong code,

**Comment by julie-sullivan** [comment]
@sergiocontrino try this: go to beta humanmine:

https://beta.humanmine.org/

Click on a template. See the URL? It's dropping the /beta - the path.

Beta humanmine is deployed using your branch and cdn-dev.intermine.org. FlyMine beta is on the dev branch, I can redeploy with your branch except Josh needs it for testing and I am reluctant to break another beta site.

**Comment by sergiocontrino** [comment]
@julie-sullivan you will need to redeploy flymine, since i reverted back to this branch a few minutes ago.

**Comment by sergiocontrino** [comment]
https://beta.humanmine.org/beta/template.do?name=Gene_Protein&scope=all   ??

**Comment by julie-sullivan** [comment]
@sergiocontrino try this: go to beta humanmine:

https://beta.humanmine.org/

Click on a template *on the home page*. See the URL? It's dropping the /beta - the path.

Maybe just an issue with the home page though? Why is that different.

**Comment by julie-sullivan** [comment]
All the images have the same bad path.

human-home

**Comment by julie-sullivan** [comment]
It's just on the home page. And if you go back to the home page from another page, the path stays correct.

**Comment by sergiocontrino** [comment]
i have done some test using http://iodocs.apps.intermine.org/flymine-beta 
not sure it is serving the https.
i have done a few test being logged in with openid.
maybe a few more tests would be good. also i would set up the production cdn https server and test for that.

**Comment by sergiocontrino** [comment]
web services seems to be working fine. there is now a working production cdn served on https.
i have not changed the global.web.properties to use that though.

**Comment by julie-sullivan** [comment]
Going to merge with dev and will make another ticket to fix the clients.

**Pull request merged**
