### PR TITLE
Switch all human data sources to use NCBI identifier by default

### PR DESCRIPTION
**Pull request by julie-sullivan**
Change all human data sources and humanmine to use NCBI identifier instead of Ensembl.

This branch was used to build current beta humanmine.

Also contains the changes to get the complex viewer working.

### CODE REVIEW

**Comment by julie-sullivan** [comment]
Changed data sources to use NCBI Entrez Gene ID.

Either updated the data source to use NCBI identifier, or changed it to use different ID resolver -- NCBI instead of Ensembl.

Not many mines have human data. TargetMine, Mousemine, mitominers.

Summary of changes:

1. sources added
    * GFF - required a few modifications to GFF core source
    * FASTA source
1. Sources changed
    * HumanMine only
      * Array Atlas
      * Atlas express (new)
      * HGNC (new)
      * HPO
      * Huge GWAS
      * NCBI gene
      * NCBI Summaries
      * OMIM
      * Protein Atlas
      * KEGG
    * shared
      * Panther
      * PubMed
1. UniProt 
    * disease is parsed correctly
    * request from Anthony (mitominer) and Rachel. They have okayed the change.
1. PSI Complexes
    * Made this Midas changes here. Should have been their own branch. Ignore, they are fine.  
1. Updated ratmine link out

**Comment by julie-sullivan** [comment]
To test:

* review code, make sure I didn't miss anything
* HumanMine code has been reviewed by Rachel.
* Want to be sure don't hurt other people by this change.
* Mines with human data:
  * [targetmine](https://github.com/chenyian-nibio/targetmine/blob/targetmine/targetmine/project.xml)
  * mousemine - uses NCBI gene ID
  * mitominer

**Comment by chenyian-nibio** [comment]
TargetMine also used NCBI Gene ID as the primaryIdentifier for a while.

**Comment by julie-sullivan** [comment]
@chenyian-nibio I just checked and you are still using NCBI ID as the primary identifier for human genes. Is that right? 

I don't think this changeset effects you anyway as you use all your own data sources. (I think?).

**Comment by chenyian-nibio** [comment]
Yes, your are correct. I also don't think the changes affect anything to TargetMine. Just for reference.

**Comment by julie-sullivan** [comment]
Need to have config for each of these sources: Use Ensembl OR use NCBI.

**Comment by justinccdev** [comment]
One small thing is that in commit 915ff19, the build.xml and project.properties build/description test files start referring to panther names and dependencies.  Should this have stayed as ncbi-gff?  However, I don't see this as enough of a reason to hold up a merge.

**Comment by julie-sullivan** [comment]
@justinccdev thanks nice catch, fixed in 818b8a277be01be4d1f73ecd30d0039c5831adab

**Pull request merged**
