### PR TITLE
Versioned postprocesses

### PR DESCRIPTION
**Pull request by julie-sullivan**
## Details

Users need to be able to version their sources. I did this in #1899. However I missed two things:

* Postprocesses need to be versioned in the same way
* Generating the keys file to use also puts bio-sources on the classpath and needs to use the custom version. I don't know how I missed that in the original commit? 

## Testing

* Versioning sources works with and without a version specified in project XML file
* Versioning postprocesses works with and without a version specified in project XML file

I don't know how I missed the keys thing, so please be sure to clean. However, I am pretty sure I _did_ do a clean. The code worked on FlyMine and locally but NOT in HumanMine. Don't know why. 

## Checklist

Before your pull request can be approved, be sure to check all boxes:

- [ ] Passing unit test for new or updated code (if applicable)
- [ ] Passes all tests – according to Travis
- [ ] Documentation (if applicable)
- [ ] Single purpose
- [ ] Detailed commit messages
- [ ] Well commented code
- [ ] Checkstyle

(I haven't done documentation yet)

### CODE REVIEW

**Comment by julie-sullivan** [comment]
Also maybe test with biotestmine.

**Comment by sergiocontrino** [comment]
flymine buildDB successful (in about 8 mins though).

**Comment by sergiocontrino** [comment]
tried to run 
`postprocess -Pprocess=create-utr-references`
with a wrong version in the project file
`<post-process name="create-utr-references" version="10.1.2"/>`
but the build was successful.
below the downloaded lib.

>  Download https://jcenter.bintray.com/org/intermine/bio-postprocess-create-utr-references/maven-metadata.xml
Download https://jcenter.bintray.com/org/intermine/bio-postprocess-create-utr-references/2.0.0-RC-01/bio-postprocess-create-utr-references-2.0.0-RC-01.pom
Download https://oss.jfrog.org/artifactory/oss-snapshot-local/org/intermine/bio-postprocess-create-utr-references/maven-metadata.xml
Download https://oss.jfrog.org/artifactory/oss-snapshot-local/org/intermine/bio-postprocess-create-utr-references/2.0.0-RC-SNAPSHOT/maven-metadata.xml
Download https://oss.jfrog.org/artifactory/oss-snapshot-local/org/intermine/bio-postprocess-create-utr-references/2.0.0-RC-SNAPSHOT/bio-postprocess-create-utr-references-2.0.0-RC-20180717.093536-10.pom
Download https://jcenter.bintray.com/org/intermine/bio-postprocess-create-utr-references/2.0.0-RC-01/bio-postprocess-create-utr-references-2.0.0-RC-01.jar

**Comment by danielabutano** [comment]
I have installed locally bio-source-uniprot with 2 different versions: 2.1 and 1.8.
I have configured project.xml to use 1.8.
Here the exception when I try to execute buildDB in biotestmin
15:01:06.841 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:01:06.841 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
15:01:06.841 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
15:01:06.841 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':dbmodel:generateKeys'.
15:01:06.841 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Could not resolve all files for configuration ':dbmodel:mergeSource'.
15:01:06.841 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > Could not resolve org.intermine:bio-source-uniprot:1.8.
15:01:06.842 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]      Required by:
15:01:06.842 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]          project :dbmodel
15:01:06.842 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       > Could not resolve org.intermine:bio-source-uniprot:1.8.
15:01:06.842 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]          > Could not get resource 'https://oss.jfrog.org/artifactory/oss-snapshot-local/org/intermine/bio-source-uniprot/1.8/bio-source-uniprot-1.8.pom'.
15:01:06.842 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]             > Could not GET 'https://oss.jfrog.org/artifactory/oss-snapshot-local/org/intermine/bio-source-uniprot/1.8/bio-source-uniprot-1.8.pom'. Received status code 409 from server: 
15:01:06.842 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
15:01:06.842 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
15:01:06.843 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dbmodel:generateKeys'.

**Comment by julie-sullivan** [comment]
@danielabutano I tried the same thing with BioGRID and it worked. 

* Installed 1.8.0 and normal version 2.1.0
* Added print statements to see which version was being used
* Correct version was being used.

In your snippet, it looks like the build found the correct string version to use "1.8" but did not find that JAR in your local repo. Can you verify that JAR is there? It's just a string comparison so "bio-source-uniprot-1.8.0.jar" for example would not work.

Here the build is looking for the correct version number, based on what's in project.xml:
version1

Here I have biogrid installed with multiple versions:

version2

**Comment by julie-sullivan** [comment]
@sergiocontrino This is the error I get:

```
> Could not resolve org.intermine:bio-postprocess-create-utr-references:10.1.2.
```

I can't replicate your error!

**Comment by danielabutano** [comment]
@julie-sullivan it works! the problem was I set 1.8 in the project.xml but the 1.8.0 was installed

**Pull request merged**
