### PR TITLE
Update to avoid reading whole chromosomes.

### PR DESCRIPTION
**Pull request by JoelRichardson**
Would you believe, attempt #4???
@sergiocontrino and @julie-sullivan , all that discussion was really useful (to me, anyway) and resulted in this pull request, which is much simpler than the previous one(s).

### CODE REVIEW

**Comment by sergiocontrino** [comment]
nice, tested with webservice, region search and export, also with reverse strand.

**Comment by JoelRichardson** [comment]
I think region search is handled separately, in GenomicRegionSequenceExporter.java, which I did not touch. Code looks similar so the same solution should work there too.

**Comment by JoelRichardson** [comment]
Hi @sergiocontrino and @julie-sullivan ,

Hmmm... I was going to work on GenomicRegionSequenceExporter.java but ran into a wall.
As you know, we're storing multiple mouse strain genomes, most (but not all) of which have taxon 10090 as their organism. For each strain, there is a chromosome "1", "2", etc. Of course, the current (old) region search UI only allows the user to pick the organism, but not the strain. However, searching for (say) chromosome 5 from 12,345,678 to 12,543,876 is meaningless across multiple genomes. Assuming the user could pick a strain, then I would need to go in here to modify the chromosome selection criteria:

https://github.com/intermine/intermine/blob/dev/bio/webapp/src/org/intermine/bio/web/export/GenomicRegionSequenceExporter.java#L78-82

Note that this issue is separate from applying the technique used in SequenceExporter.java to get the sequence slice. I am sure that will also in this context. It's just that I can't get to that point because right now I cannot get the right chromosome to work with. 

Thoughts?

**Comment by JoelRichardson** [comment]
Just to clarify: the reason I'm hesitant is that it means introducing code to distinguish between multiple genomes, which is something that I know you are also thinking about and is a much bigger task than this one section of code. Also, the approach taken in MouseMine may or may not be a viable common solution.

**Comment by sergiocontrino** [comment]
hi @JoelRichardson , yes i think you are right and that we will merge this pull request as it is and take some time to find a common solution for the multiple genomes issue. it would be great to discuss your mousemine solution and its implications for, for example, plant mines. i think @julie-sullivan is planning something along these lines for around mid september. thanks!

**Comment by JoelRichardson** [comment]
Thanks @sergiocontrino . If you wanted to apply the same  slicing approach to GenomicRegionSequenceExporter.java, the changes would be simple. (I can add this to the PR if you prefer, but I can't test it.):

1. Delete lines 85-95 (https://github.com/intermine/intermine/blob/dev/bio/webapp/src/org/intermine/bio/web/export/GenomicRegionSequenceExporter.java#L85-L95)
2. Add this line after the start/end calculation, e.g. at line 111: 
```
chrResidueString = 
                chr.getSequence().getResidues().subsequence(start - 1, end).toString().toLowerCase();
```
3. Remove the substring call at line 122, ie, just pass chrResidueString (https://github.com/intermine/intermine/blob/dev/bio/webapp/src/org/intermine/bio/web/export/GenomicRegionSequenceExporter.java#L122)

**Pull request merged**
