### PR TITLE
@deepakunni3 fix for range queries missing point mutations

### PR DESCRIPTION
**Pull request by sergiocontrino**

### CODE REVIEW

**Comment by sergiocontrino** [comment]
fixes bug #1283

**Comment by julie-sullivan** [comment]
@sergiocontrino the tests are still failing? Can you double check?

```
AILURE: Class org.intermine.objectstore.intermine.WithNotXmlSqlGeneratorTest, method testOverlapQueries

junit.framework.ComparisonFailure: null expected:<...eStart, a2_.rangeEnd[]) ORDER BY a1_.id, a...> but was:<...eStart, a2_.rangeEnd[, '[]']) ORDER BY a1_.id, a...>

at org.intermine.objectstore.intermine.SqlGeneratorTest.testOverlapQueries(SqlGeneratorTest.java:990)

at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)

at junit.extensions.TestSetup$1.protect(TestSetup.java:23)

at junit.extensions.TestSetup.run(TestSetup.java:27)
```

**Comment by julie-sullivan** [comment]
How do I test this? 

(also this branch should be in your repo, not intermine's)

**Comment by sergiocontrino** [comment]
you could just rebuild a webapp and test you get the point mutations (done).
it would be nice to test with a bioseq instance maybe?
i think these fix branches are very convenient in intermine (and then can just be removed?)

**Comment by julie-sullivan** [comment]
The point mutation 14-3-3epsilon[18A2] has overlaps. Shows up in overlaps for gene FBgn0020238. And show up in region search for  3R:18242531-18250550 .

**Pull request merged**
