### PR TITLE
Template tags webservice

### PR DESCRIPTION
**Pull request by julie-sullivan**
## Details

Adds an end point for adding tags to templates. Needed for bluegenes to be able to favourite templates. Refs #1766
 
## Testing

Adding / removing template tags works as expected. Let me know and I can release beta flymine on this branch.

## Checklist

Before your pull request can be approved, be sure to check all boxes:

- [ ] Passing unit test for new or updated code (if applicable)
- [x] Passes all tests – according to Travis
- [x] Documentation (if applicable)
- [x] Single purpose
- [x] Detailed commit messages
- [x] Well commented code
- [x] Checkstyle

### CODE REVIEW

**Comment by julie-sullivan** [comment]
@yochannah 

1. Set your mine to use the new JARs. e.g. [gradle.properties](https://github.com/intermine/flymine/blob/master/gradle.properties#L1). `3.1.+` is fine.

2. install my new code. This is the command I use:
```
(cd plugin && ./gradlew clean && ./gradlew install) && (cd intermine && ./gradlew clean && ./gradlew install) && (cd bio && ./gradlew clean && ./gradlew install) && (cd bio/sources && ./gradlew clean && ./gradlew install)  && (cd bio/postprocess/ && ./gradlew clean && ./gradlew install)
```
(I have an alias!)

3. Deploy your mine. Run the `template/tags` end point. Tell me what I did wrong.

Alternatively I can release beta flymine on this branch for you to test. Might be easier? Let me know.

**Comment by julie-sullivan** [comment]
@yochannah this web service increments the web service version, but so does #1930. FYI! Fine if they are merged out of order but remind me before you merge.

**Comment by julie-sullivan** [comment]
All tags:

http://beta.flymine.org/beta/service/template/tags?token=<SECRET>

To see all tags for a template:

http://beta.flymine.org/beta/service/template/tags?name=Probe_Gene&token=<NOT_TELLING_YOU_MY_SECRET_TOKEN>

To test adding and removing tags to templates, POST / DELETE:

http://beta.flymine.org/beta/service/template/tags?name=Probe_Gene&tags=monkey&token=<NOT_TELLING_YOU_MY_SECRET_TOKEN>

The tag names are semi-colon delimited, e.g. `cake;banana` will add the `cake` and `banana` tags.

**Comment by yochannah** [comment]
@julie-sullivan am I right in thinking there are no tags on beta flymine? 

Running http://beta.flymine.org/beta/service/template/tags?token=[TOP-SEEKRIT-TOKEN] gives me

```json
{"tags":[

],"executionTime":"2019.02.19 17:42::55","wasSuccessful":true,"error":null,"statusCode":200}
```

I'll make some of my own if that is the case

**Comment by julie-sullivan** [comment]
@yochannah it only returns your tags, not global tags. On purpose.

**Comment by yochannah** [comment]
after reading this morecarefully, I realise that makes sense and this wasn't the ticket I was thinking of. Whoops. Thanks :man_facepalming:

**Comment by julie-sullivan** [comment]
Need this change to the docs:

```
-                <summary>Add one or more tags to a list</summary>
+                <summary>Add one or more tags to a template</summary>
```

**Comment by yochannah** [comment]
## Testing the specified methods

- GET all tags - 
  - :heavy_check_mark:  returns a list of tags that I have associated with templates for my user.
  - :heavy_check_mark: doesn't return anything when not authenticated. 
- POST to a certain template
  - :heavy_check_mark: doesn't allow me to post when not authenticated. 
  - :heavy_check_mark: allows me to post tags when I am authenticated!
  - :heavy_check_mark: allows me to set `im:favourite` as a tag, and then shows up as a favourite in mymine
  - :question: maybe we want to trim tokens? 
  - :question: maybe we want tags to be unique? 

```json
{
  "tags": [
    " dog",
    " squirrel",
    "cat",
    "cat",
    "dog",
    "squirrel"
  ],
"comment" : "(snipped out the boring bits of the response)"
}
```

- DELETE
  - :heavy_check_mark: doesn't deletes tags when unauthenticated
  - :heavy_check_mark: deletes tags as specified when authenticated
  - :heavy_check_mark: deleted `im:favourite` and the yellow star disappeared in mymine.

## Docs

You mentioned the POST docs tweak needed. We need to fix the Delete description, too - it's currently 
> Delete one or more tags from a list

## Other notes

While these methods generally work okay, I'm curious why it isn't integrated with the /templates endpoint more closely. Imagine a possible bluegenes workflow: 

1. User logs in and visits the "My Data" (previously mymine/lists) page. 
2. They're shown a list of their personal templates and lists. Their favourites are highlighted. 

From a coding point of view, to complete the second step, we'll run the following steps:

1. GET /templates
2. Iterate through _every_ template and GET tags for it. There doesn't seem to be a way to know whether a template is a personal template or not, so we'd have to try it for all public templates too. 
3. Where there is `im:favourite`, mark those templates as favourites. 
4. number 2 above raises the question if there's any way to tell _at all_ which templates are personal templates, in order to highlight them to the user? I can create a different issue for this. 

If we integrated tags directly into the `/templates` endpoint (right now it just returns an empty array of tags for a personal template that *does* have tags), then step 2 and a large number of GETs could be avoided. 

If I've missed anything or made a mistake let me know! :)

**Comment by yochannah** [comment]
ah - there is a way to tell between personal and public templates! 

`"tags": ["im:public"]`

That makes things a bit better with regards to the number of http requests made, but if it is possible to include tags in personal templates in the GET `/templates` endpoint, it would still be more efficient.

**Comment by julie-sullivan** [comment]
I did this because Josh asked for this end point.

Do you want to suggest which end point I should implement instead? The end point + params needed.

**Comment by yochannah** [comment]
Yep, the original ticket was a little sparse on detail so that makes sense :) 

The endpoints in question _work_, so barring my comments about possible improvements, which aren't mandatory - I'd be happy to merge this and create a new, more detailed ticket for my request above. 

Also, are there any tests? I didn't check the box for unit testing the new feature yet.

**Comment by julie-sullivan** [comment]
> The endpoints in question _work_, so barring my two question comments about possible improvements, which aren't mandatory - I'd be happy to merge this and create a new, more detailed ticket for my request above.

Yes, let's do this. And I'll fix the text. 

I don't know how to add tests. The tests for these web services are in the `imjs` client.

**Pull request merged**
