### PR TITLE
Java 8

### PR DESCRIPTION
**Pull request by julie-sullivan**
## Details

* Update LazyCollection to extend Collection instead of Set.
* Change SingletonResults to be a Collection instead of Set. 

The objectstore uses SingletonResults as a set, the bio layer uses singletons as a list -- so just cast where appropriate. I don't want to change the data structure being used as I am guessing we rely on the behaviour of lists and sets (e.g ordering, uniqueness) in some way. So best to leave it. 

Refs #1675 and #1343

## Testing

* All tests pass
* Run a build. build is correct
* Webapp - results are okay. making lists are okay.

Worst case scenario:
* Making a new list from a set InterMineBag.java causes something bad to happen. I don't know what.
* Making a new hashset instead of using the results and casting in BaseEquivalentObjectFetcher.java causes problems. Results variable is local so making a new set is safe at least.
* EvictOrphansTask.java isn't used anywhere I don't think!

## Checklist

Before your pull request can be approved, be sure to check all boxes:

- [x] Passing unit test for new or updated code (if applicable)
- [x] Passes all tests – according to Travis
- [x] Documentation (if applicable)
- [x] Single purpose
- [x] Detailed commit messages
- [x] Well commented code
- [x] Checkstyle

### CODE REVIEW

**Comment by julie-sullivan** [comment]
@danielabutano A reminder that I used the `-noverify` flag here:

```
    <jvmarg line="${ENV.ANT_OPTS} -noverify" /> 
```

**Comment by sergiocontrino** [comment]
@danielabutano can you review the latest changes (0c3368c)?

**Comment by sergiocontrino** [comment]
code has been successfully tested with a full flymine build (except homologene) and webapp.
the homologene source gives an error that i am investigating at the moment, see below.

> starting command: ant -v -Dsource=homologene
> 
> BUILD FAILED
> /micklem/data/thalemine/git/intermine/imbuild/integrate.xml:54: The following error occurred while executing this line:
> /micklem/data/thalemine/git/intermine/imbuild/source.xml:330: java.lang.RuntimeException: ObjectStore error has occurred (in get)
> 	at org.intermine.objectstore.query.Results.get(Results.java:233)
> 	at org.intermine.objectstore.query.Results$Iter.hasNext(Results.java:378)
> 	at org.intermine.dataloader.ObjectStoreDataLoader.process(ObjectStoreDataLoader.java:135)
> 	at org.intermine.dataloader.ObjectStoreDataLoader.process(ObjectStoreDataLoader.java:60)
> 	at org.intermine.dataloader.ObjectStoreDataLoaderTask.execute(ObjectStoreDataLoaderTask.java:128)
> 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
> 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
> 	at org.apache.tools.ant.Task.perform(Task.java:348)
> 	at org.apache.tools.ant.Target.execute(Target.java:435)
> 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
> 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
> 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
> 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
> 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
> 	at org.intermine.task.Integrate.performAction(Integrate.java:219)
> 	at org.intermine.task.Integrate.performAction(Integrate.java:132)
> 	at org.intermine.task.Integrate.execute(Integrate.java:123)
> 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
> 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
> 	at org.apache.tools.ant.Task.perform(Task.java:348)
> 	at org.apache.tools.ant.Target.execute(Target.java:435)
> 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
> 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
> 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
> 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
> 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
> 	at org.apache.tools.ant.Main.runBuild(Main.java:851)
> 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
> 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
> 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
> Caused by: org.intermine.objectstore.ObjectStoreException: Error in worker thread
> 	at org.intermine.dataloader.ParallelBatchingFetcher.doPks(ParallelBatchingFetcher.java:100)
> 	at org.intermine.dataloader.BatchingFetcher.getEquivalentsForObjects(BatchingFetcher.java:261)
> 	at org.intermine.dataloader.BatchingFetcher.getEquivalentsFor(BatchingFetcher.java:152)
> 	at org.intermine.dataloader.BatchingFetcher$NoseyObjectStore.execute(BatchingFetcher.java:583)
> 	at org.intermine.objectstore.query.ResultsBatches.fetchBatchFromObjectStore(ResultsBatches.java:193)
> 	at org.intermine.objectstore.query.PrefetchManager.doRequest(PrefetchManager.java:241)
> 	at org.intermine.objectstore.query.PrefetchManager.doRequest(PrefetchManager.java:146)
> 	at org.intermine.objectstore.query.ResultsBatches.getBatch(ResultsBatches.java:164)
> 	at org.intermine.objectstore.query.ResultsBatches.getRowsFromBatch(ResultsBatches.java:139)
> 	at org.intermine.objectstore.query.Results.range(Results.java:197)
> 	at org.intermine.objectstore.query.SingletonResults.range(SingletonResults.java:66)
> 	at org.intermine.objectstore.query.Results.get(Results.java:226)
> 	... 35 more
> Caused by: org.intermine.objectstore.ObjectStoreException: Duplicate objects found for pk org.intermine.model.bio.Gene.key_primaryidentifier: Gene [briefDescription=null, chromosome=null, chromosomeLocation=null, cytoLocation=null, description=null, downstreamIntergenicRegion=null, id=9, length=null, name=null, organism=97793, primaryIdentifier="Acadm", score=null, scoreType=null, secondaryIdentifier=null, sequence=null, sequenceOntologyTerm=97798, symbol=null, upstreamIntergenicRegion=null]
> 	at org.intermine.dataloader.BatchingFetcher.doPk(BatchingFetcher.java:446)
> 	at org.intermine.dataloader.ParallelBatchingFetcher$WorkUnit.fetch(ParallelBatchingFetcher.java:142)
> 	at org.intermine.dataloader.ParallelBatchingFetcher$Worker.run(ParallelBatchingFetcher.java:163)
> 	at java.lang.Thread.run(Thread.java:748)
> 

with these the offending lines on the data file

> 3       10090   11364   Acadm   6680618 NP_031408.1
> 3       10116   24158   Acadm   292494885       NP_058682.2

and this the relevant rows in the gene table

```
select primaryidentifier from gene where symbol like 'Acadm';
 primaryidentifier 
 -------------------
 MGI:87867
 RGD:2012

```

**Comment by sergiocontrino** [comment]
the same error happens with the current setting (java 7), so the testing is successful and the PR could be merged after @danielabutano reviews the changes.

**Comment by intermineorg** [comment]
Hi @sergiocontrino and @julie-sullivan, I have finally reviewed the code and it seems fine with me.We can merge it!

**Comment by danielabutano** [comment]
Hi @sergiocontrino and @julie-sullivan I have finally reviewed the PR and it seems fine with me. We can proceed with the merge.

**Pull request merged**
