### PR TITLE
BioDBConverter.makeLocation has taxonId removed; not used. Dependent files updated.

### PR DESCRIPTION
**Pull request by sammyjava**
## Details

*BioDBConverter.makeLocation had taxonId as an unused argument. That is annoying. I've removed it along with updating the dependent chado loaders.*

## Testing

*Besides running unit tests, how can the reviewer test your feature / bug fix? Are there edge cases to be aware of?*

## Checklist

Before your pull request can be approved, be sure to check all boxes:

- [ ] Passing unit test for new or updated code (if applicable)
- [ ] Passes all tests – according to Travis
- [ ] Documentation (if applicable)
- [ ] Single purpose
- [ ] Detailed commit messages
- [ ] Well commented code
- [ ] Checkstyle

### CODE REVIEW

**Comment by sammyjava** [comment]
```/BioDBConverter.java:124: Line is longer than 100 characters (found 119). [LineLength]
:bio-core:checkstyleMain FAILED```

I'm sorry, but Travis is just pathetic. Of course a line is longer than 100 characters. WE HAVE BIG SCREENS IN 2108.

**Comment by sammyjava** [comment]
OMG I'm gonna let you fix this. Travis gives me a headache, and I don't get headaches!

**Comment by julie-sullivan** [comment]
@sammyjava I updated the JavaDoc but now I am getting a failing test. Can you take a look?

Also ran the FlyBase chado source and everything looks fine there.

**Comment by sammyjava** [comment]
Hrm, that's org.intermine.bio.dataconversion.ChadoDBConverterTest which I didn't touch. I'll investigate, I haven't been testing the unit test tasks.

**Comment by sammyjava** [comment]
I'm totally lost. The code compiles, installs just fine. I've been using it for months. I don't know how to reproduce Travis' complaints so I can fix them! I can't run ./gradlew test in bio/sources because it wants to make a bunch of DB connections. So clearly Travis isn't doing that.

**Comment by julie-sullivan** [comment]
looking at the test failure again, it looks like they are just out of order? Let me try to fix.

**Comment by julie-sullivan** [comment]
```
junit.framework.AssertionFailedError: Item collections do not match.
In expected, not actual: 
[<item id="18_1" class="Location">
  <attribute name="end" value="14990594"/>
  <attribute name="start" value="14985572"/>
  <attribute name="strand" value="1"/>
  <reference name="feature" ref_id="1_2"/>
  <reference name="locatedOn" ref_id="9_1"/>
  <collection name="dataSets">
    <reference ref_id="5_1"/>
  </collection>
</item>
, <item id="18_2" class="Location">
  <attribute name="end" value="102000"/>
  <attribute name="start" value="101001"/>
  <attribute name="strand" value="1"/>
  <reference name="feature" ref_id="1_1"/>
  <reference name="locatedOn" ref_id="9_1"/>
  <collection name="dataSets">
    <reference ref_id="5_1"/>
  </collection>
</item>
, <item id="18_3" class="Location">
  <attribute name="end" value="24577313"/>
  <attribute name="start" value="24574105"/>
  <attribute name="strand" value="-1"/>
  <reference name="feature" ref_id="7_1"/>
  <reference name="locatedOn" ref_id="9_2"/>
  <collection name="dataSets">
    <reference ref_id="5_1"/>
  </collection>
</item>
, <item id="18_4" class="Location">
  <attribute name="end" value="24577107"/>
  <attribute name="start" value="24576947"/>
  <attribute name="strand" value="-1"/>
  <reference name="feature" ref_id="10_2"/>
  <reference name="locatedOn" ref_id="9_2"/>
  <collection name="dataSets">
    <reference ref_id="5_1"/>
  </collection>
</item>
, <item id="18_5" class="Location">
  <attribute name="end" value="24577313"/>
  <attribute name="start" value="24577166"/>
  <attribute name="strand" value="-1"/>
  <reference name="feature" ref_id="10_1"/>
  <reference name="locatedOn" ref_id="9_2"/>
  <collection name="dataSets">
    <reference ref_id="5_1"/>
  </collection>
</item>
]
Summary of expected: 
Location - 5 [18_2, 18_4, 18_1, 18_5, 18_3]
In actual, not expected: 
[<item id="18_1" class="Location">
  <attribute name="end" value="14990594"/>
  <attribute name="start" value="14985572"/>
  <attribute name="strand" value="1"/>
  <reference name="feature" ref_id="1_2"/>
  <reference name="locatedOn" ref_id="9_1"/>
</item>
, <item id="18_2" class="Location">
  <attribute name="end" value="102000"/>
  <attribute name="start" value="101001"/>
  <attribute name="strand" value="1"/>
  <reference name="feature" ref_id="1_1"/>
  <reference name="locatedOn" ref_id="9_1"/>
</item>
, <item id="18_3" class="Location">
  <attribute name="end" value="24577313"/>
  <attribute name="start" value="24574105"/>
  <attribute name="strand" value="-1"/>
  <reference name="feature" ref_id="7_1"/>
  <reference name="locatedOn" ref_id="9_2"/>
</item>
, <item id="18_4" class="Location">
  <attribute name="end" value="24577107"/>
  <attribute name="start" value="24576947"/>
  <attribute name="strand" value="-1"/>
  <reference name="feature" ref_id="10_2"/>
  <reference name="locatedOn" ref_id="9_2"/>
</item>
, <item id="18_5" class="Location">
  <attribute name="end" value="24577313"/>
  <attribute name="start" value="24577166"/>
  <attribute name="strand" value="-1"/>
  <reference name="feature" ref_id="10_1"/>
  <reference name="locatedOn" ref_id="9_2"/>
</item>
]
Summary of actual: 
Location - 5 [18_4, 18_3, 18_1, 18_5, 18_2]
```

**Comment by julie-sullivan** [comment]
Okay, pushed in the update. We'll see what happens. I think our tests depend on the hashsets being in the same order each time. Which works until it doesn't. 

If you have this issue again, you can set up the tests to run locally:
https://intermine.readthedocs.io/en/latest/get-started/intermine-tests/

For fun, here is our travis config: https://github.com/intermine/intermine/blob/dev/.travis.yml

You can see the scripts that travis runs. It creates these test databases everytime. And even launches malariamine for the web services tests.

**Comment by sammyjava** [comment]
Wow. OK. :) I've never really looked at the unit tests. Thanks!

**Pull request closed without merging**
