### PR TITLE
add a end point to only return system templates. 

### PR DESCRIPTION
**Pull request by julie-sullivan**
## Details

Add `/service/templates/system` to get all the system templates (converter templates that are tagged with `im:converter`). Refs #1726

## Testing

Make sure this is what you need.

## Checklist

Before your pull request can be approved, be sure to check all boxes:

- [ ] Passing unit test for new or updated code (if applicable)
- [ ] Passes all tests – according to Travis
- [ ] Documentation (if applicable)
- [ ] Single purpose
- [ ] Detailed commit messages
- [ ] Well commented code
- [ ] Checkstyle

### CODE REVIEW

**Comment by danielabutano** [comment]
- from the description retrieved calling /service it looks like that the service has the parameter "type" instead of "format". Using type it doosn't work

- if you don't specify the format it doesn't work

**Comment by julie-sullivan** [comment]
@danielabutano Can you clarify where you see `type`? I don't see it:

```
      {
         "identifier": "ws-system-template",
         "methods": [
            {
               "DescriptionFormat": "markdown",
               "Description": "Get a listing of the templates configured in an InterMine instance tagged with\nthe `im:converter` tag.\n                ",
               "HTTPMethod": "GET",
               "RequiresAuthentication": "false",
               "URI": "/templates/system",
               "parameters": [
                  {
                     "Type": "enumerated",
                     "Description": "Output format",
                     "Required": "N",
                     "EnumeratedList": [
                        "xml",
                        "json"
                     ],
                     "Default": "xml",
                     "Name": "format"
                  }
               ],
               "Synopsis": "Get the list of system templates.",
               "returnFormats": [
                  {
                     "Name": "xml"
                  },
                  {
                     "key": "templates",
                     "Name": "json"
                  }
               ]
            }
         ],
         "name": "Templates (System)",
         "URI": "/service/templates/system"
      },
```

**Comment by julie-sullivan** [comment]
I use the chrome extension, and it looks fine:

* without a format
* with a format=xml
* with a format=json

e.g. I do this
```
wget http://localhost:8080/flymine/service/templates/system
```

And get this:

```
<template-queries>
<template name="Transcript_To_Gene_Type_Converter" title="Transcript to gene type converter" comment=""><query name="Transcript_To_Gene_Type_Converter" model="genomic" view="Transcript.id Transcript.gene.id" longDescription="" sortOrder="Transcript.id asc"><constraint path="Transcript.id" editable="true" description="Transcript.id" op="=" value="0"/></query></template>
<template name="MRNA_To_Gene_Type_Converter" title="MRNA to gene type converter" comment=""><query name="MRNA_To_Gene_Type_Converter" model="genomic" view="MRNA.id MRNA.gene.id" longDescription="" sortOrder="MRNA.id asc"><constraint path="MRNA.id" editable="true" description="MRNA.id" op="=" value="0"/></query></template>
<template name="Protein_To_MRNA_Type_Converter" title="Protein to mRNA type converter" comment=""><query name="Protein_To_MRNA_Type_Converter" model="genomic" view="Protein.id Protein.genes.CDSs.MRNA.id" longDescription="" sortOrder="Protein.id asc"><constraint path="Protein.id" editable="true" description="Protein.id" op="=" value="0"/></query></template>
<template name="CDNAClone_To_Protein_Type_Converter" title="CDNAClone to protein type converter" comment=""><query name="CDNAClone_To_Protein_Type_Converter" model="genomic" view="CDNAClone.id CDNAClone.gene.proteins.id" longDescription="" sortOrder="CDNAClone.id asc"><constraint path="CDNAClone.id" editable="true" description="CDNAClone.id" op="=" value="0"/></query></template>
<template name="Exon_To_Gene_Type_Converter" title="Exon to gene type converter" comment=""><query name="Exon_To_Gene_Type_Converter" model="genomic" view="Exon.id Exon.gene.id" longDescription="" sortOrder="Exon.id asc"><constraint path="Exon.id" editable="true" description="Exon.id" op="=" value="0"/></query></template>
<template name="MRNA_To_Protein_Type_Converter" title="MRNA to protein type converter" comment=""><query name="MRNA_To_Protein_Type_Converter" model="genomic" view="MRNA.id MRNA.gene.proteins.id" longDescription="" sortOrder="MRNA.id asc"><constraint path="MRNA.id" editable="true" description="MRNA.id" op="=" value="0"/></query></template>
<template name="Transcript_To_Protein_Type_Converter" title="Transcript to protein type converter" comment=""><query name="Transcript_To_Protein_Type_Converter" model="genomic" view="Transcript.id Transcript.gene.proteins.id" longDescription="" sortOrder="Transcript.id asc"><constraint path="Transcript.id" editable="true" description="Transcript.id" op="=" value="0"/></query></template>
<template name="Protein_To_CDNAclone_Type_Converter" title="Protein to cDNAclone type converter" comment=""><query name="Protein_To_CDNAclone_Type_Converter" model="genomic" view="Protein.id Protein.genes.clones.id" longDescription="" sortOrder="Protein.id asc"><constraint path="Protein.id" editable="true" description="Protein.id" op="=" value="0"/></query></template>
<template name="Protein_To_Gene_Type_Converter" title="Protein to gene type converter" comment=""><query name="Protein_To_Gene_Type_Converter" model="genomic" view="Protein.id Protein.genes.id" longDescription="" sortOrder="Protein.id asc"><constraint path="Protein.id" editable="true" description="Protein.id" op="=" value="0"/></query></template>
<template name="Protein_To_Transcript_Type_Converter" title="Protein to transcript type converter" comment=""><query name="Protein_To_Transcript_Type_Converter" model="genomic" view="Protein.id Protein.genes.transcripts.id" longDescription="" sortOrder="Protein.id asc"><constraint path="Protein.id" editable="true" description="Protein.id" op="=" value="0"/></query></template>
<template name="Gene_To_CDNAclone_Type_Converter" title="Gene to cDNAclone type converter" comment=""><query name="Gene_To_CDNAclone_Type_Converter" model="genomic" view="Gene.id Gene.clones.id" longDescription="" sortOrder="Gene.id asc"><constraint path="Gene.id" editable="true" description="Gene.id" op="=" value="0"/></query></template>
<template name="Gene_To_Protein_Type_Converter" title="Gene to protein type converter" comment=""><query name="Gene_To_Protein_Type_Converter" model="genomic" view="Gene.id Gene.proteins.id" longDescription="" sortOrder="Gene.id asc"><constraint path="Gene.id" editable="true" description="Gene.id" op="=" value="0"/></query></template>
<template name="CDNAClone_To_Gene_Type_Converter" title="CDNAClone to gene type converter" comment=""><query name="CDNAClone_To_Gene_Type_Converter" model="genomic" view="CDNAClone.id CDNAClone.gene.id" longDescription="" sortOrder="CDNAClone.id asc"><constraint path="CDNAClone.id" editable="true" description="CDNAClone.id" op="=" value="0"/></query></template>
<template name="Allele_To_Gene_Type_Converter" title="Allele To Gene Type Converter" comment=""><query name="Allele_To_Gene_Type_Converter" model="genomic" view="Allele.id Allele.gene.id" longDescription="" sortOrder="Allele.id asc"><constraint path="Allele.id" editable="true" description="Allele.id" op="=" value="0"/></query></template>
<template name="Gene_To_Transcript_Type_Converter" title="Gene to transcript type converter" comment=""><query name="Gene_To_Transcript_Type_Converter" model="genomic" view="Gene.id Gene.transcripts.id" longDescription="" sortOrder="Gene.id asc"><constraint path="Gene.id" editable="true" description="Gene.id" op="=" value="0"/></query></template>
<template name="Gene_To_MRNA_Type_Converter" title="Gene to mRNA type converter" comment=""><query name="Gene_To_MRNA_Type_Converter" model="genomic" view="Gene.id Gene.CDSs.MRNA.id" longDescription="" sortOrder="Gene.id asc"><constraint path="Gene.id" editable="true" description="Gene.id" op="=" value="0"/></query></template>
<template name="Gene_To_Exon_Type_Converter" title="Gene to exon type converter" comment=""><query name="Gene_To_Exon_Type_Converter" model="genomic" view="Gene.id Gene.exons.id" longDescription="" sortOrder="Gene.id asc"><constraint path="Gene.id" editable="true" description="Gene.id" op="=" value="0"/></query></template></template-queries>

```

Can you tell me the commands you ran? The ones that failed? Thanks!

**Comment by danielabutano** [comment]
@julie-sullivan you are right. I dont' know why I have added that comment. very sorry about this!!
I have noticed one small issue. When there are no templates, the web service  returns status code 404 and  the "error":"No template found called system" and wasSuccessful=false. I don't think it's correct.
For example the service service/lists, if there are no lists, returns status code 200 and wasSuccessfful=true.
Maybe @yochannah  has an opinion about this.

**Comment by yochannah** [comment]
I remember having the conversation, but it was long enough ago I don't
remember the details, and I'm currently drawing a blank. Sorry.

**Comment by julie-sullivan** [comment]
@danielabutano I agree! It should be an empty array not a 404. But I still can't replicate!

I just deleted all my templates, and I get this result

```
{"templates": {} ,"executionTime":"2019.02.19 15:05::38","wasSuccessful":true,"error":null,"statusCode":200}
```
I add a new template, and tag with `im:converter` and results are correct:
```
{"templates": {"Allele_To_Gene_Type_Converter":{"model":{"name":"genomic"},"title":"Allele To Gene Type Converter","select":["Allele.id","Allele.gene.id"],"name":"Allele_To_Gene_Type_Converter","comment":"","tags":["im:converter"],"rank":"unranked","orderBy":[{"Allele.id":"ASC"}],"where":[{"path":"Allele.id","op":"=","code":"A","editable":true,"switchable":false,"switched":"LOCKED","value":"0"}]}} ,"executionTime":"2019.02.19 15:07::58","wasSuccessful":true,"error":null,"statusCode":200}
```

Can you tell me which command you ran? 

I use the chrome extension "rest web service client".

**Comment by julie-sullivan** [comment]
@danielabutano @yochannah that 404 is actually correct because you are on version 27 where that end point hasn't been implemented yet. It should work if you update to version 28. 

However it would be less confusing if it didn't return `template: null` back!

**Pull request merged**
