### PR TITLE
Footer fix issue for #1604

### PR DESCRIPTION
**Pull request by yochannah**
## Details

Issue #1604 - looked like some kind of regression/merge issue with footer. 

* Fixed missing images by cherry-picking my old commits.
* added apple ios store link
* ensure that if mines don't have the "credits" variable set, the screen won't just say ???credits (won't display anything if variable unset).

## Testing

1. deploy local instances of humanmine / flymine.
2. view footer. Are there broken images? See #1604 for the "bad" scenario that should be fixed.

## Checklist

Before your pull request can be approved, be sure to check all boxes:

~- [ ] Passing unit test for new or updated code (if applicable)~
- [x] Passes all tests – according to Travis
~- [ ] Documentation (if applicable)~
- [x] Single purpose
- [x] Detailed commit messages
- [x] Well commented code
- [ ] Checkstyle

### CODE REVIEW

**Comment by julie-sullivan** [comment]
Last footer fix looked different for mousemine. And other mines, I suppose. What would be a good way to go about testing for this? I only checked human and flymines.

**Comment by yochannah** [comment]
I've been wondering about this. The layout for a large block of text (like mousemine) is innately going to be different to that of a small block of text and several images. What works well for one might not for others. 

I've had an idea. Watch this space, don't merge anything!

**Comment by yochannah** [comment]
Okay, I've set it up thus: 

Current flymine footer:

```
funding = <p class="intermine-default-footer"><strong>Funding:</strong> InterMine has been developed principally through support of the <a href="http://www.wellcome.ac.uk/" target="_new" title="Wellcome Trust">Wellcome Trust.</a> Complementary projects have been funded by the <a href="http://www.nih.gov/" target="_new" title="US National Institutes of Health">NIH/NHGRI</a> and the <a href="http://www.bbsrc.ac.uk/" target="_new" title="BBSRC">BBSRC.</a></p> <a href="http://www.wellcome.ac.uk/" target="_new" title="Wellcome Trust"><img src="images/wellcome-logo-black.png" border="0" height="70px" width="70px" ></a><a href="http://www.nih.gov/" target="_new" title="US National Institutes of Health"><img src="images/logo_nhgri.png" height="40px" width="200px" border="0"></a> <a href="http://www.bbsrc.ac.uk/" target="_new" title="BBSRC"><img src="images/bbsrc-logo.gif" border="0" height="57px" width="150px" ></a>
```
this layout works nicely for text-light but logo heavy funding footers, like fly or human. Less so for something like mousemine. For mousemine, or any text-heavy footer, something like this should work instead:

```
<p>All your long credits here. Etc etc etc.</p>
```

note there is no class in the `<p>` so it resorts to a wider default styling behaviour.

**Comment by yochannah** [comment]
To test - try setting /intermine/intermine/flymine/webapp/resources/model.properties 's funding property to the text in the file below and redeploy. Clear your cache if it doesn't work the first time. Don't forget to change it back!

[footer-text.txt](https://github.com/intermine/intermine/files/1330153/footer-text.txt)

looks like this for me:

image

**Comment by julie-sullivan** [comment]
@yochannah I think you DO want to update the documentation as I think the docs are out of date:

http://intermine.readthedocs.io/en/latest/webapp/layout/

**Comment by julie-sullivan** [comment]
@motenko would you be willing to test this for us? Last time we made a footer change it mucked up your footer if I recall correctly!

**Comment by motenko** [comment]
Hi Yo,

I’ve been involve with something else and haven’t really had a chance to look at it.

The same issue was affecting flymine’s footer too.  If it looks good on flymine, I’d suggest merging the fix.


Gratefully,
Howie

**Pull request merged**
