### PR TITLE
Transfer sequences - update CDS to handle discontinous locations

### PR DESCRIPTION
**Pull request by julie-sullivan**
## Details

*Summary of pull request, including references to relevant tickets (if applicable).*

## Testing

*Besides running unit tests, how can the reviewer test your feature / bug fix? Are there edge cases to be aware of?*

## Checklist

Before your pull request can be approved, be sure to check all boxes:

- [x] Passing unit test for new or updated code (if applicable)
- [x] Passes all tests – according to Travis
- [x] Documentation (if applicable)
- [x] Single purpose
- [x] Detailed commit messages
- [x] Well commented code
- [x] Checkstyle

### CODE REVIEW

**Comment by julie-sullivan** [comment]
@JoelRichardson Did you test this? I can't find our emails!

**Comment by julie-sullivan** [comment]
Refs #1803

**Comment by julie-sullivan** [comment]
@sergiocontrino Joel tested this an it worked but can you review as well? Thanks!

**Comment by sergiocontrino** [comment]
checked a few thousands of cds sequences in flymine, no differences with previous method on production (continous locations). fine to merge for me.

**Pull request merged**
