### PR TITLE
keep track of interaction details so they are not duplicated. Refs #1019

### PR DESCRIPTION
**Pull request by julie-sullivan**

### CODE REVIEW

**Comment by julie-sullivan** [comment]
@JoelRichardson - does this fix the problem?

**Comment by JoelRichardson** [comment]
@julie-sullivan - Glanced at the code and it looks like it should work. Will properly test and let you know.

**Comment by julie-sullivan** [comment]
@sergiocontrino Can you test this? https://github.com/intermine/intermine/issues/1019#issuecomment-107867480 is what I am trying to fix, we can confirm with @JoelRichardson that we accomplished this. Maybe you can just check the source works as expected still so we can merge in the change.

**Comment by julie-sullivan** [comment]
@justinccdev  Can you test this? #1019 (comment) is what I am trying to fix, we can confirm with @JoelRichardson that we accomplished this. Maybe you can just check the source works as expected still so we can merge in the change.

**Pull request merged**
