### PR TITLE
Python 3 codegen

### PR DESCRIPTION
**Pull request by justinccdev**
## Details

*Summary of pull request, including references to relevant tickets (if applicable).*

## Testing

*Besides running unit tests, how can the reviewer test your feature / bug fix? Are there edge cases to be aware of?*

## Checklist

Before your pull request can be approved, be sure to check all boxes:

- [ ] Passing unit test for new or updated code (if applicable)
- [ ] Passes all tests – according to Travis
- [ ] Documentation (if applicable)
- [ ] Single purpose
- [ ] Detailed commit messages
- [ ] Well commented code
- [ ] Checkstyle

### CODE REVIEW

**Comment by justinccdev** [comment]
For #1583

**Comment by julie-sullivan** [comment]
Fantastic! Can you update the checkstyle?

Also, can you tell me what I should specifically be testing for?

* generate queries via the webapp (deployed from your branch)
* execute the queries with python3 (not 2.7!)
* make sure results are printing out as expected. 

That's about it I think?

And great job adding a test, good idea!

**Comment by justinccdev** [comment]
How are we running checkstyle now?

Yes, all your bullets should work.  May also be worth testing with 2.7 as
well since the same scripts should/need to be compatible with both.

**Comment by julie-sullivan** [comment]
`./gradlew checkstyleMain` is the command maybe?

**Comment by julie-sullivan** [comment]
@justinccdev potentially dumb question. I exported a template query and got two "different" (but not really) results. 

Does that look ok to you?

```
julie ~/scripts $ /usr/bin/python python3.py
(u'FBcl0152372', u'FBgn0051522', u'CG31522', u'CG31522')
julie ~/scripts $ /usr/bin/python3 python3.py
FBcl0152372 FBgn0051522 CG31522 CG31522
```

**Comment by justinccdev** [comment]
@julie-sullivan Could you attach the script?

**Comment by julie-sullivan** [comment]
Sure!

```
#!/usr/bin/env python

# This is an automatically generated script to run your query
# to use it you will require the intermine python client.
# To install the client, run the following command from a terminal:
#
#     sudo easy_install intermine
#
# For further documentation you can visit:
#     http://intermine.readthedocs.org/en/latest/web-services/

# The following two lines will be needed in every python script:
from intermine.webservice import Service
service = Service("http://localhost:8080/flymine/service")

# Get a new query on the class (table) you will be querying:
query = service.new_query("CDNAClone")

# The view specifies the output columns
query.add_view(
    "primaryIdentifier", "gene.primaryIdentifier", "gene.secondaryIdentifier",
    "gene.symbol"
)

# Uncomment and edit the line below (the default) to select a custom sort order:
# query.add_sort_order("CDNAClone.primaryIdentifier", "ASC")

# You can edit the constraint values below
query.add_constraint("CDNAClone", "LOOKUP", "LD14383", code = "A")

# Uncomment and edit the code below to specify your own custom logic:
# query.set_logic("A")

# Outer Joins
# (display properties of these relations if they exist,
# but also show objects without these relationships)
query.outerjoin("gene")

for row in query.rows():
    print(row["primaryIdentifier"], row["gene.primaryIdentifier"], row["gene.secondaryIdentifier"], \
        row["gene.symbol"])
```

I tried another template, same issue. I can deploy on beta flymine if that helps.

**Comment by julie-sullivan** [comment]
Yes I agree with you! Best to have one script work in either.

> in the next century 
Lol

**Comment by justinccdev** [comment]
Okay, I will implement that soon.

**Comment by justinccdev** [comment]
Okay, that should fix it but let me know if you aren't happy with the comments in the generated script.

**Comment by justinccdev** [comment]
I believe it's just the printing.

**Pull request merged**
