### PR TITLE
process homologues properly

### PR DESCRIPTION
**Pull request by julie-sullivan**
@kkarra Will you test?

### CODE REVIEW

**Comment by kkarra** [comment]
It doesn't seem to work for me.

**Comment by julie-sullivan** [comment]
This is the config I used:

```
   <source name="panther" type="panther">
      <property name="src.data.dir" location="/data/panther"/>
      <property name="panther.organisms" value="7227"/>
      <property name="panther.homologues" value="9606"/>
    </source>
```

**Comment by julie-sullivan** [comment]
I tested both yeast and fly:

```
flymine=# select o.taxonid, count(*) from gene g, organism o where g.organismid = o.id group by o.taxonid;
 taxonid | count 
---------+-------
    9606 | 16561
    4932 |  4420
(2 rows)
```

**Comment by julie-sullivan** [comment]
@sergiocontrino Can you test this for me? The original problem was that human orthologues were not loading for yeastmine for the panther data source. 

FlyMine has yeast orthologues, but then I looked and saw that the config was different. FlyMine had:

```
   <source name="panther" type="panther" dump="true">
      <property name="src.data.dir" location="/micklem/data/panther/current"/>
      <property name="panther.organisms" value="7227 6239 9606 10090 10116 7955 4932"/>
    </source>
```

Whereas yeastmine has https://github.com/yeastgenome/intermine/blob/master/yeastmine/project.xml#L60-L64

```
   <source name="panther" type="panther">
      <property name="src.data.dir" location="/data/intermine/yeast_orthologs/panther"/>
	 <property name="panther.organisms" value="4932"/>   
      <property name="panther.homologues" value="7227 9606 10090 10116 7955 6239 4932"/>
    </source>
```
I tried that and it failed. The source wasn't processing the homologues value correctly. I fixed that and now it seems to be working as expected. Can you verify?

This might even go on the master branch.

**Comment by julie-sullivan** [comment]
Refs #1079

**Comment by kkarra** [comment]
I thought the issue was that Panther switched to using HGNC IDs from probably EntrezIDs and hence the human homologs were not loading correctly. I was lost looking at various parts of the IdResolver and am not sure still if the above change in IDs has been resolved correctly..

**Comment by julie-sullivan** [comment]
@kkarra You are probably right. However everything is working for me correctly. I can load human and yeast data just fine. I am hoping @justinccdev will be able to reproduce your problem.

**Comment by justinccdev** [comment]
I just ran this query with current beta flymine (which incorporates the fix) with two different project XML forms.  First with
```
   <source name="panther" type="panther" dump="true">                                                                                                                                                                         
      <property name="src.data.dir" location="/micklem/data/panther/current"/>
      <property name="panther.organisms" value="7227 6239 9606 10090 10116 7955 4932"/>
    </source>
```

then with

```
   <source name="panther" type="panther" dump="true">
      <property name="src.data.dir" location="/micklem/data/panther/current"/>
      <property name="panther.organisms" value="4932"/>
      <property name="panther.homologues" value="7227 9606 10090 10116 7955 6239 4932"/>
    </source>
```

Both times

```
flymine=# select o.taxonid, count(*) from gene g, organism o where g.organismid = o.id group by o.taxonid;
 taxonid | count 
---------+-------
    7227 | 10720
    7955 | 22423
    4932 |  4442
    6239 | 14697
   10090 | 20804
   10116 | 21354
    9606 | 19150
```

However, I will observe that the number of InterMine database objects loaded each time is very different.  For the first project xml (get_db_stats.py is a script I knocked up to simply count all entities in all tables in an InterMine database).

```
./get_db_stats.py flymine                                                                                                                                                                                                     
bioentitiesdatasets: 28542
bioentity: 28542
crossreference: 1235723
crossreferenceshomologue: 1235722
dataset: 1
datasetshomologue: 1235722
datasetsontologyterm: 1
datasource: 1
evidencehomologue: 1235722
gene: 28542
homologue: 1235723
intermine_metadata: 5
intermineobject: 2500001
ontology: 1
ontologyterm: 1
organism: 7
orthologueevidence: 1
orthologueevidencecode: 1
sequencefeature: 28542
soterm: 1
tracker: 12339750
```

and for the second

```
./get_db_stats.py flymine   
bioentitiesdatasets: 113590
bioentity: 113590
crossreference: 4253624
crossreferenceshomologue: 4253624
dataset: 1
datasetshomologue: 4253624
datasetsontologyterm: 1
datasource: 1
evidencehomologue: 4253624
gene: 113590
homologue: 4253624
intermine_metadata: 5
intermineobject: 8620851
ontology: 1
ontologyterm: 1
organism: 7
orthologueevidence: 1
orthologueevidencecode: 1
sequencefeature: 113590
soterm: 1
tracker: 40327311
```

I don't know if this is of any significance or not.  I also realized I tested against beta when maybe panther-config-fix would have been better.  I can go back and test against that if it's likely to make a difference.

**Comment by julie-sullivan** [comment]
@justinccdev Yes, thanks!! The fix is on the branch so test using that. Actually the branch is from the master branch, so beta wouldn't be a good test of what @kkarra is experiencing.

@kkarra I didn't write down what you told me was the problem. Can you expand?

@justinccdev Kalpana mentions the human identifiers. Can you:

1. run the build on the fixed branch
2. verify the human and yeast genes have loaded
3. human genes have the "correct" (NCBI) identifier. On live yeastmine there are  33,207 human genes created by panther.

```
<query name="" model="genomic" view="Gene.primaryIdentifier Gene.organism.shortName" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.dataSets.name" op="=" value="Panther data set"/>
</query>
```

If you are happy the data created by panther is "correct", assign the ticket to me and I will skype with Kalpana to find out more about the problem.

**Comment by justinccdev** [comment]
Sure.  I don't need to load any source other than Panther do I?  Even just that takes a significant amount of time with the data in /micklem/data/panther/current.

**Comment by kkarra** [comment]
Yeastmine production is on old panther files.

**Comment by justinccdev** [comment]
Okay, I ran the panther-config-fix branch with a configured ID resolver against our /micklem/data/panther/current.  To cut down on the build time, I first tried

```
   <source name="panther" type="panther" dump="true">
      <property name="src.data.dir" location="/micklem/data/panther/current"/>
      <property name="panther.organisms" value="9606 4932"/>
    </source>
```

and then

```
   <source name="panther" type="panther" dump="true">
      <property name="src.data.dir" location="/micklem/data/panther/current"/>
      <property name="panther.organisms" value="4932"/>
      <property name="panther.homologues" value="9606"/>
    </source>
```

to load just human and yeast.  In both cases, my SQL query now matches @julie-sullivan's results above

```
flymine=# select o.taxonid, count(*) from gene g, organism o where g.organismid = o.id group by o.taxonid;
 taxonid | count 
---------+-------
    9606 | 16561
    4932 |  4420
```

Looking in our /micklem/data/panther/current/RefGenomeOrthologs file I see the HGNC IDs and some logging I put in temporarily shows names of the form such as HGNC:18866 being translated to NCBI IDs (in this case 343450).

@kkarra It might be worth checking that your ID resolver is correctly configured.  When I first set this up I just had

```
resolver.file.rootpath=/micklem/data/idresolver
```

in my .intermine/<mine>.properties file.  This doesn't work because the code currently simply appends filenames to the end without putting in a /.  You can see in integrate/intermine.log where it loads resolver data files (search for "Creating id resolver from data file and caching it.") and then check that you don't see a "Resolver file not exists:" (sic) message.

**Comment by justinccdev** [comment]
@kkarra You mean you're still using a Panther file with EntrezID human IDs rather than HGNC ones?

**Comment by kkarra** [comment]
Yes . Although I see that that it has all Ensembl IDs! I am not sure where I saw EntrezIDs.  I will re-try what you suggest and see what I get. If you think all homolog sources are merging human genes correctly then we are good. I will get back to this later in the week.

**Comment by julie-sullivan** [comment]
Thanks so much @justinccdev! Thanks for the thorough testing. 

The bug I aimed to fix (loading all organisms vs. just the homologues) is fixed so I am going to close this ticket. @kkarra If you are still having problems let me know and we can fix.

**Pull request merged**
