### PR TITLE
Adds additional testing goodness

### PR DESCRIPTION
**Pull request by alexkalderimis**
This set of changes was intended to add a chromosome-locationy thing to the testmodel, so that it is more useful for development and we don't have to use the genomic model as much.  In the course of this development I uncovered some major issues with dynamic objects, which have been addressed.

This set of changes includes some significant improvements to the layout and organisation of the keyword search APIs.

### CODE REVIEW

**Comment by julie-sullivan** [comment]
Checkstyle errors:

>  File /local-homes/julie/git/intermine/bio/webapp/src/org/intermine/bio/web/logic/GenomicRegionSearchQueryRunner.java
>   Unused import - org.intermine.api.util.AnonProfile. 33

#937 needs to be fixed!

**Comment by alexkalderimis** [comment]
How do I run the bio checkstyle tests - I will add them to the test suite then fix this.

**Comment by julie-sullivan** [comment]
Thanks! In the bio/test-all directory:

1. `ant fulltest` runs all the bio tests
2. `ant checkstyle` runs checkstyle on the bio packages.

**Comment by julie-sullivan** [comment]
@alexkalderimis Can you run both checkstyle and the JUnit tests? Those aren't running either.

**Comment by alexkalderimis** [comment]
Please clarify - which 'checkstyle and JUnit tests'?

**Comment by julie-sullivan** [comment]
In the `bio/test-all` directory:

1. `ant fulltest` runs all the bio JUnit tests
2. `ant checkstyle` runs checkstyle on the bio packages.

72ebef7163424974f60ed84bddf9066e0ac356d2 addressed no. 2 but not 1.

**Comment by alexkalderimis** [comment]
The bio testall tests are already run by the 'bio' test suite. See `config/travis/run.sh` which runs all the tests.

**Comment by julie-sullivan** [comment]
@alexkalderimis What sorts of things should I test? 

* quick search
* JBrowse

**Comment by alexkalderimis** [comment]
The big thing to test (in terms of importance) is the *quick search*. It has been quick thoroughly refactored, which is a bit dangerous given the lack of tests for it. The only real tests we have for it are in the imjs test suite which tests the quick-search API endpoint. It was through these tests that I discovered the bugs that I I needed to address - so our CI is doing its job at least.

I have tested it on the testmodel so that needs checking, but we also really need to run a full test of a flymine build to check the quick search performance in terms of both load and search performance. We should also check that I haven't leaked any resources (I think this is very unlikely, but it needs checking).

So - the usual things - search for everything, search by term, search by facet, search by term & facet, use logic, use wildcards, etc. Make sure your configuration is obeyed and that results are appropriately presented.

In terms of the dynamic objects in the testmodel that should cause this to blow up in beta, look for Anne (an Employee of Wernham-Hogg), who is a `Bibliophile,Employee`.

As for JBrowse, we should be able to look at text locations in JBrowse - you can use iodocs.labs.intermine.org to test the API, and a JBrowse instance to test the integration with JBrowse.

**Comment by julie-sullivan** [comment]
Running build now to compare search index building times.

**Comment by julie-sullivan** [comment]
I've deployed a test on beta.flymine.org.

When you search for "zen" the facets are wrong. They are listing "sequence feature" instead of gene:

search

The other types (protein publication etc) are correct.

**Comment by julie-sullivan** [comment]
This is how long the search index too to create yesterday:

`create-search-index                                     5908`

It usually takes less than a minute. 

6 Jan

`create-search-index                                     50`

Christmas

`create-search-index                                     66`

**Comment by alexkalderimis** [comment]
Please see the docs on 1.5.0 for information on the change to the search config (tl/dr: swap 'multi' for 'single').

**Comment by julie-sullivan** [comment]
You were right Alex, this fixed the issue: babc0592fa49888c338b4bf05f937f01d5026e69

We will need to ignore bioentity and sequence feature.

**Comment by julie-sullivan** [comment]
@sergiocontrino I've released beta on the relevant branch. I'll test JBrowse and the quick search. Will you test the quick search and leakiness?

**Comment by julie-sullivan** [comment]
unpacking the search index took 2.14 minutes on this new branch, I'll test on the beta branch.

**Comment by julie-sullivan** [comment]
@alexkalderimis the bolded header for each result is now empty. Can you take a look?

empty-results

**Comment by julie-sullivan** [comment]
@alexkalderimis I ran the build again and got the same results:

` create-search-index                                     5735`

So it's clear that the initial result wasn't due to a network issue. I've copied the logs of the two builds, and will run a build with the beta branch. I'll then compare the two and see if I can spot a problem. Here's a snippet:

```
intermine.log.1:2015-01-06 20:39:22 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=10001; thread state=WAITING; docs/ms=0.052929066; memory=1431848k/9102272k; time=188951ms
intermine.log.1:2015-01-06 20:39:27 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=20001; thread state=WAITING; docs/ms=0.1033777; memory=1239614k/9102272k; time=193475ms
intermine.log.1:2015-01-06 20:39:32 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=30001; thread state=WAITING; docs/ms=0.15068308; memory=1468180k/9102272k; time=199100ms
intermine.log.1:2015-01-06 20:39:45 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=40001; thread state=RUNNABLE; docs/ms=0.18897367; memory=1384303k/9102272k; time=211675ms
intermine.log.1:2015-01-06 20:39:47 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=50001; thread state=RUNNABLE; docs/ms=0.23326585; memory=1393685k/9102272k; time=214352ms
intermine.log.1:2015-01-06 20:39:49 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=60001; thread state=RUNNABLE; docs/ms=0.27787888; memory=1576815k/9102272k; time=215925ms
intermine.log.1:2015-01-06 20:39:50 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=70001; thread state=WAITING; docs/ms=0.32201096; memory=1273514k/9102272k; time=217387ms
intermine.log.1:2015-01-06 20:39:53 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=80001; thread state=RUNNABLE; docs/ms=0.3639751; memory=1513689k/9102272k; time=219798ms
intermine.log.1:2015-01-06 20:39:53 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=90001; thread state=RUNNABLE; docs/ms=0.40880743; memory=1209819k/9102272k; time=220155ms
intermine.log.1:2015-01-06 20:39:56 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=100001; thread state=WAITING; docs/ms=0.4495599; memory=1701019k/9102272k; time=222442ms
intermine.log.1:2015-01-06 20:39:56 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=110001; thread state=WAITING; docs/ms=0.49293318; memory=1311374k/9102272k; time=223156ms
intermine.log.1:2015-01-06 20:39:59 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=120001; thread state=RUNNABLE; docs/ms=0.5320608; memory=981222k/9102272k; time=225540ms
intermine.log.1:2015-01-06 20:40:00 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=130001; thread state=RUNNABLE; docs/ms=0.5733205; memory=1615728k/9102272k; time=226751ms
```

**Comment by julie-sullivan** [comment]
Just a reminder to me when I come back to this in a few weeks. I ran a couple builds and the new search index creation took 5000 seconds instead of 60, consistently.

I grepped the log file of the build on the beta branch and got this:

```
intermine.log:2015-03-03 18:55:47 INFO  org.intermine.api.lucene.KeywordSearch     - Indexing - Temp Dir: /data/tmp
intermine.log:2015-03-03 18:55:47 INFO  org.intermine.api.lucene.KeywordSearch     - Starting fetcher thread...
intermine.log:2015-03-03 18:55:47 INFO  org.intermine.api.lucene.KeywordSearch     - Preparing indexer...
intermine.log:2015-03-03 18:55:47 INFO  org.intermine.api.lucene.KeywordSearch     - Index directory: /data/tmp/search_index7524017078465534876
intermine.log:2015-03-03 18:56:26 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=1; thread state=RUNNABLE; docs/ms=2.5749305E-5; memory=1382772k/9102272k; time=38836ms
intermine.log:2015-03-03 18:58:51 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=10001; thread state=RUNNABLE; docs/ms=0.054584354; memory=1469750k/9102272k; time=183221ms
intermine.log:2015-03-03 18:58:55 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=20001; thread state=RUNNABLE; docs/ms=0.106520884; memory=1316719k/9102272k; time=187766ms
intermine.log:2015-03-03 18:59:00 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=30001; thread state=RUNNABLE; docs/ms=0.15531121; memory=1194131k/9102272k; time=193167ms
intermine.log:2015-03-03 18:59:12 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=40001; thread state=WAITING; docs/ms=0.19514397; memory=1318099k/9102272k; time=204982ms
```

I need to compare these numbers with the numbers for the new build. I grepped the new logs but these mesages were not there, I don't know why. Will fix the logs and build again.

**Comment by julie-sullivan** [comment]
Here's a snippet from my new build today:

```
2015-03-10 15:23:22 ERROR      org.intermine.api.lucene.Indexer     - docs indexed=9480001; thread=RUNNABLE; docs/ms=1.79; memory=23.93% free (of 9102272k); time=5309425ms
2015-03-10 15:23:36 ERROR      org.intermine.api.lucene.Indexer     - docs indexed=9490001; thread=RUNNABLE; docs/ms=1.78; memory=18.89% free (of 9102272k); time=5323628ms
2015-03-10 15:23:42 INFO  org.intermine.objectstore.intermine.NotXmlParser     - (Fast Class) Split: 50048 ms, Class: 2595 ms, Create: 9495 ms, Parse: 8812 ms
2015-03-10 15:23:50 ERROR      org.intermine.api.lucene.Indexer     - docs indexed=9500001; thread=RUNNABLE; docs/ms=1.78; memory=13.89% free (of 9102272k); time=5337310ms
2015-03-10 15:24:04 ERROR      org.intermine.api.lucene.Indexer     - docs indexed=9510001; thread=RUNNABLE; docs/ms=1.78; memory=8.89% free (of 9102272k); time=5351025ms
2015-03-10 15:24:04 INFO  org.intermine.objectstore.proxy.ProxyCollection     - Created: 79000000, Used: 0, Evaluated: 0
2015-03-10 15:24:20 ERROR      org.intermine.api.lucene.Indexer     - docs indexed=9520001; thread=RUNNABLE; docs/ms=1.77; memory=45.55% free (of 9102272k); time=5367898ms
2015-03-10 15:24:34 INFO  org.intermine.sql.precompute.PrecomputedTableManager     - Dropped precomputed table temporary_precomp_52792
2015-03-10 15:24:34 INFO  org.intermine.sql.precompute.PrecomputedTableManager     - Dropped precomputed table temporary_precomp_52791
2015-03-10 15:24:34 INFO  org.intermine.sql.precompute.PrecomputedTableManager     - Dropped precomputed table temporary_precomp_52793
2015-03-10 15:24:34 INFO  org.intermine.sql.precompute.PrecomputedTableManager     - Dropped precomputed table temporary_precomp_52794
2015-03-10 15:24:34 INFO  org.intermine.sql.precompute.PrecomputedTableManager     - Dropped precomputed table temporary_precomp_52799
2015-03-10 15:24:34 INFO  org.intermine.sql.precompute.PrecomputedTableManager     - Dropped precomputed table temporary_precomp_52795
2015-03-10 15:24:34 INFO  org.intermine.sql.precompute.PrecomputedTableManager     - Dropped precomputed table temporary_precomp_52796
2015-03-10 15:24:34 INFO  org.intermine.sql.precompute.PrecomputedTableManager     - Dropped precomputed table temporary_precomp_52798
2015-03-10 15:24:34 INFO  org.intermine.sql.precompute.PrecomputedTableManager     - Dropped precomputed table temporary_precomp_52797
2015-03-10 15:25:53 INFO       org.intermine.api.lucene.Indexer     - Indexing of 9529840 documents finished in 91:00.998 minutes

```

1. Took 90 mins instead of 15.
2. The average document / ms is less than 2, whilst the old build starts slow but then ends with an avg of 10 docs per ms.
3. Lots of precomputed table talk in logs. Might be an artefact of how I set my logs up.

Last couple lines of the build from the beta branch:

```
intermine.log.1:2015-03-03 19:11:33 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=9600001; thread state=WAITING; docs/ms=10.148433; memory=4772283k/9102272k; time=945960ms
intermine.log.1:2015-03-03 19:11:33 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=9610001; thread state=RUNNABLE; docs/ms=10.157189; memory=4740218k/9102272k; time=946128ms
intermine.log.1:2015-03-03 19:11:34 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=9620001; thread state=RUNNABLE; docs/ms=10.165707; memory=4728945k/9102272k; time=946319ms
intermine.log.1:2015-03-03 19:11:34 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=9630001; thread state=RUNNABLE; docs/ms=10.174704; memory=4721016k/9102272k; time=946465ms
intermine.log.1:2015-03-03 19:12:47 INFO  org.intermine.api.lucene.KeywordSearch     - Indexing of 9634106 documents finished in 16:59.645 minutes

```

**Comment by julie-sullivan** [comment]
I am re-running the build with line 516 commented out. https://github.com/alexkalderimis/intermine/blob/corporate-jbrowse/intermine/api/main/src/org/intermine/api/lucene/InterMineObjectFetcher.java#L516

This line adds the parent classes to the search index.

**Comment by julie-sullivan** [comment]
@alexkalderimis This https://github.com/intermine/intermine/pull/944#issuecomment-76368963 is still a problem. If you search for a gene, gene doesn't appear but Sequence feature does.

Can you fix?

**Comment by julie-sullivan** [comment]
The collections on report pages have a trail:

trail

**Comment by julie-sullivan** [comment]
The report pages don't load:

report-death

**Comment by alexkalderimis** [comment]
that is many unhappy things...

**Comment by julie-sullivan** [comment]
I generated the search index on kermit my computer using the beta branch:

> beta branch
> Total time: 18 minutes 56 seconds

I tried using the new branch With modifications. I commented out these three lines:

https://github.com/intermine/intermine/blob/corporate-jbrowse/intermine/api/main/src/org/intermine/api/lucene/InterMineObjectFetcher.java#L502-L504

And it still took much much longer:

> corporate-jbrowse
> Total time: 127 minutes 12 seconds

@alexkalderimis Can you make sure I did the right thing? If I did, can you take a look at creating the indexes and see what else changed?

**Comment by julie-sullivan** [comment]
removing from 1.6 for now, will try to get sorted before Alex leaves.

**Comment by julie-sullivan** [comment]
Is this pull request still valid? Which one am I supposed to use? If not, can you please delete.

**Pull request closed without merging**
