### PR TITLE
GFF: add header

### PR DESCRIPTION
**Pull request by julie-sullivan**
## Details

The header of the GFF file (the top bit that has a #) often has important metadata, such as the genome build, date of annotation, etc. but is discarded.

Instead, I set the header to a variable, and made that variable available in the `GFFRecord`

See: #1786

## Testing

@sergiocontrino Can you test that the GFF loading still works as expected? I only changed the constructor.

@JoelRichardson Can you verify this is what you asked for?

## Checklist

Before your pull request can be approved, be sure to check all boxes:

- [ ] Passing unit test for new or updated code (if applicable)
- [ ] Passes all tests – according to Travis
- [ ] Documentation (if applicable)
- [ ] Single purpose
- [ ] Detailed commit messages
- [ ] Well commented code
- [ ] Checkstyle

### CODE REVIEW

**Comment by sergiocontrino** [comment]
code seems fine, and complying with the request of having gff header available with each gff record.

**Comment by julie-sullivan** [comment]
@sergiocontrino @JoelRichardson Can you look at the last commit? ac6b644b92bee80a5c4f6add8a531fe4fbbe6f7a

There are lines that start with `#` in the GFF file, but we only want the ones at the top. Does it make sense what I did? Or is there a better way?

**Comment by JoelRichardson** [comment]
@julie-sullivan This looks right to me. The only thing I would suggest for efficiency's sake is to convert to string the first time you reach line 56 then pass the converted string at line 59. Not a big deal for small files but might be if there are millions of lines? Question: what's happening at line 89?

**Comment by julie-sullivan** [comment]
@JoelRichardson @sergiocontrino Thanks, think I got it now! Maybe.

* the FIRST loop in this parser `breaks` when first GFF record is found
* until that happens, we collect the header -- anything that starts with `#`

* Once the first GFF record is found, the SECOND loop goes through the GFF lines in the rest of the file
* In this second loop, we ignore lines that start with `#`
* for efficiency, we set the header.toString() once just before the second loop. Instead of inside the loop on each line. (good tip!)

**Comment by JoelRichardson** [comment]
> * In this second loop, we ignore lines that start with `#`
But isn't line 89 adding `#` lines to the header?
  https://github.com/intermine/intermine/blob/ac6b644b92bee80a5c4f6add8a531fe4fbbe6f7a/bio/core/src/main/java/org/intermine/bio/io/gff3/GFF3Parser.java#L89

**Comment by julie-sullivan** [comment]
@JoelRichardson Yes! You pointed that out, and I fixed it. I don't know how to link but see here: https://github.com/intermine/intermine/pull/1924/files

We are skipping `#` lines instead.

**Comment by JoelRichardson** [comment]
Oh ok. Thanks!

**Pull request merged**
