### PR TITLE
  Add UI support for range queries.

### PR DESCRIPTION
**Pull request by julie-sullivan**
Refs #797 

~~Waiting for update to imtables~~

This adds the region search to the QueryBuilder. To test:

* build a query with a range contraint, e.g. chromosome location
* make sure all constraints work, we had problems with OUTSIDE

There is no user validation, the user has to put in the correct format. But I figured that someone using this feature would know that.

### CODE REVIEW

**Comment by alexkalderimis** [comment]
imtables is ready - this needs testing.

**Comment by julie-sullivan** [comment]
@alexkalderimis 

1. I still can't run queries with some constraints, e.g. OUTSIDE fails
2. I tool string, integer out of valid ranges. Were we going to add date?

**Comment by alexkalderimis** [comment]
This needs to be tested with imtables 2.0.

**Comment by julie-sullivan** [comment]
Is this pull request still valid? Which one am I supposed to use?

**Comment by julie-sullivan** [comment]
this is going in the imtables-2.0 pull request

**Comment by julie-sullivan** [comment]
imtables-2.0 pull request isn't going to be merged but this pull request can be.

> I still can't run queries with some constraints, e.g. OUTSIDE fails

**Comment by julie-sullivan** [comment]
Tests are failing that used range constraints of type string, need to fix these.

**Pull request merged**
