### PR TITLE
Added QueryExpression.LENGTH and QueryExpression.CONCAT operators.

### PR DESCRIPTION
**Pull request by sammyjava**
## Details

*Summary of pull request, including references to relevant tickets (if applicable).*

## Testing

*Besides running unit tests, how can the reviewer test your feature / bug fix? Are there edge cases to be aware of?*

## Checklist

Before your pull request can be approved, be sure to check all boxes:

- [ ] Passing unit test for new or updated code (if applicable)
- [ ] Passes all tests – according to Travis
- [ ] Documentation (if applicable)
- [x] Single purpose
- [ ] Detailed commit messages
- [x] Well commented code
- [ ] Checkstyle

### CODE REVIEW

**Comment by sammyjava** [comment]
Here's the PR again, extremely minor tweaks, I expect Travis to give it the Bronx Cheer. (You should look that one up, Daniela, I'm sure there's an Italian name for the same thing.) :)

**Comment by sammyjava** [comment]
Oh, BTW, i fixed the Emacs settings on my dev server so it never uses tab indents again. But that's not the only thing Travis doesn't like.

**Comment by danielabutano** [comment]
@sammyjava  Have you killed Travis? I do no see Travis CI build linked to this PR....:confused:

**Comment by sammyjava** [comment]
NO! I thought maybe you told Travis to stay away from me! No idea why Travis is silent, but I love it!

**Comment by sammyjava** [comment]
Closing to replace with a fresh, clean PR and I'll deal with Travis checkstyle.

**Pull request closed without merging**
