### PR TITLE
add protein.isoforms collection. Refs #1116

### PR DESCRIPTION
**Pull request by julie-sullivan**
To test:

* isoforms are created correctly
* canonical proteins have correctly populated isoforms collection
  * nothing left out! There's a loop so need to make sure didn't miss any
* isoforms have correct reference to the correct canonical protein
  * to get the canonical protein I am just chopping off the prefix. this may be wrong!
* single proteins have empty canonical protein ref and isoforms collection

### CODE REVIEW

**Comment by sergiocontrino** [comment]
it seems i am unable to test, i always get the 
Error: Could not find isoforms in undefined when parsing Protein.isoforms.primaryAccession
(clean, re-built database, restarted tomcat)
isoforms appear in the query builder, but not in im-table (manage colums)

**Comment by julie-sullivan** [comment]
@sergiocontrino That is because the model is cached, a refresh should fix your problem.

**Comment by rachellyne** [comment]
Where is this? Do you want me to test?

**Comment by julie-sullivan** [comment]
@rachellyne @sergiocontrino is looking at this now. I am working on the protein interactions and accidentally removed my database.

**Comment by sergiocontrino** [comment]
@julie-sullivan, oops. all looks fine (and i like it!  much nicer) checked a few in uniprot.

**Comment by julie-sullivan** [comment]
Refs #1116

**Pull request merged**
