### PR TITLE
Hardcoded CDN values 

### PR DESCRIPTION
**Pull request by yochannah**
set CDN root url for the script loader to allow self-hosted CDNs. Note that this pull is dependent on https://github.com/intermine/CDN/commit/73bb2ae675bd4f9eb6e1f2a49f366a3e76cc5dcb going live in the master branch

This addresses #1245 

See also https://github.com/yochannah/intermine-api-loader/commit/1dcfcaafbda52b51a68953e9e437d38b5630d50e

### CODE REVIEW

**Comment by julie-sullivan** [comment]
@yochannah @JoeCarlson  mentioned the enrichment widgets. This pull request doesn't address the widgets. Should it? Or are those already sorted?

**Comment by yochannah** [comment]
The API loader had the widget javascript paths hardcoded (see paths.yml https://github.com/yochannah/intermine-api-loader/commit/1dcfcaafbda52b51a68953e9e437d38b5630d50e ) which was why the widgets wouldn't load if the CDN was down. This pull changes all instances of the API loader, telling the API to use the preferred CDN rather than the (potentially broken) hardcoded Intermine CDN values.

**Comment by julie-sullivan** [comment]
Got it! Thanks!

**Comment by julie-sullivan** [comment]
This pull request is not needed because CDN dependency has been fixed in a version of InterMine after 1.4

**Pull request closed without merging**
