### PR TITLE
Kill build on indexing error

### PR DESCRIPTION
**Pull request by justinccdev**
Refers to #1041, #896, #992

### CODE REVIEW

**Comment by justinccdev** [comment]
I have now fixed the other checkstyle failure in #1118.  With some other im.js fixes the tests are now green across the board! (at least until the race condition failure next crops up).

**Comment by justinccdev** [comment]
This works.  The build failures are due to the other issues discussed above that have been fixed elsewhere.  Did you want me to merge it?

**Comment by julie-sullivan** [comment]
No, assign this to me and I will test. Also, remerge in beta to get the fixes.

**Comment by justinccdev** [comment]
What input is needed?

**Comment by julie-sullivan** [comment]
Assign this to me and I will test. Also, remerge in beta to get the fixes.

**Comment by justinccdev** [comment]
Alright, I accidentally rebased the commits instead of merging them which is why they appear twice.  A clean branch with these commits on top of current beta is in #1128

**Pull request closed without merging**
