### PR TITLE
add does not contain op. 

### PR DESCRIPTION
**Pull request by julie-sullivan**
## Details

Refs #1847

## Testing

Make sure DOES NOT CONTAIN op acts as expected

## Checklist

Before your pull request can be approved, be sure to check all boxes:

- [ ] Passing unit test for new or updated code (if applicable)
- [ ] Passes all tests – according to Travis
- [ ] Documentation (if applicable)
- [ ] Single purpose
- [ ] Detailed commit messages
- [ ] Well commented code
- [ ] Checkstyle

### CODE REVIEW

**Comment by julie-sullivan** [comment]
so that's a good point, and I should fix it.

you mean here right:

contains


But this sort of brings up the point that `contains` and `like` to the same thing. meaning they put wildcards around both sides of the search word.

Options:

* be consistent. Use LIKE or CONTAINS. Not both.
* (Probably too late to be consistent. ha ha.) Just add DOES NOT CONTAIN to dropdown.
* just check this commit in to make DOES NOT CONTAIN work. Leave UI alone. Solve in blue genes.

Let me know what you think.

**Comment by sergiocontrino** [comment]
i would probably keep only contains/does not contain in drop down.
alternatively i would just add 'does not contain' in the drop down

**Comment by julie-sullivan** [comment]
is this something we want to fix in the current UI?

As for changing what's available, I am worried about backwards compatibility.

**Comment by julie-sullivan** [comment]
We can make new tickets if we need to update anything else. We'll make sure the query builder in bluegenes is consistent. Maybe

**Pull request merged**
