### PR TITLE
Openid migration

### PR DESCRIPTION
**Pull request by alexkalderimis**
This is the result of cherry picking the changes from the imtables-2.0 branch that provide the migration features. This should be an intermediate release (tested) before we release the tables.

### CODE REVIEW

**Comment by alexkalderimis** [comment]
@julie-sullivan Please check and merge this as a patch release, and we can inform all the other groups.

**Comment by julie-sullivan** [comment]
@alexkalderimis It can't automatically merge for some reason. Can you look? Also, can we have a smaller changeset, e.g. a branch with only the open ID changes? That will help testing, and people will be able to merge faster.

**Comment by julie-sullivan** [comment]
never mind. the changes:

1. adding humanmine
2. new data source

So not dangerous.

**Comment by julie-sullivan** [comment]
The merge conflict is in the release notes of all things.

**Comment by julie-sullivan** [comment]
```
Apr 20, 2015 11:01:23 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [openid-auth] in context with path [/humanmine] threw exception
java.lang.IllegalArgumentException: Missing argument
        at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:93)
        at org.expressme.openid.OpenIdManager.getHmacSha1(OpenIdManager.java:182)
        at org.expressme.openid.OpenIdManager.getAuthentication(OpenIdManager.java:112)
        at org.intermine.web.logic.login.OpenIDAuthenticator.doGet(OpenIDAuthenticator.java:92)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
```

**Comment by julie-sullivan** [comment]
As for google, it's not working on humanmine:

> 400. That’s an error.
> OpenID auth request contains an unregistered domain: http://www.humanmine.org

It's fine on FlyMine

**Comment by julie-sullivan** [comment]
@alexkalderimis Testing using beta worked. It's correctly updating the queries, lists and templates. Sorry for the confusion.

Some tests are failing though:

1. checkstyle error
2. selenium log in test fails

Fix those, then I'll release this as 1.5.

**Comment by julie-sullivan** [comment]
This fixes #854

**Pull request merged**
