### PR TITLE
close connections left open by the integrate task

### PR DESCRIPTION
**Pull request by danielabutano**
## Details
This PR includes fix suggested by @JoeCarlson. (I was wondering if we can close the db, using Databasefacroty.getDataBase().shutdown() instead)

## Testing

*Besides running unit tests, how can the reviewer test your feature / bug fix? Are there edge cases to be aware of?*

## Checklist

Before your pull request can be approved, be sure to check all boxes:

- [ ] Passing unit test for new or updated code (if applicable)
- [ ] Passes all tests – according to Travis
- [ ] Documentation (if applicable)
- [ ] Single purpose
- [ ] Detailed commit messages
- [ ] Well commented code
- [ ] Checkstyle

### CODE REVIEW

**Comment by julie-sullivan** [comment]
After this command, there are open database connections:

    ./gradlew bio-source-entrez-organism:test

After this command, there are NO open database connections:

    ./gradlew bio-source-entrez-organism:test --no-daemon

Adding "org.gradle.daemon=false" to gradle.properties also works. We recommend adding  ` -Dorg.gradle.daemon=false` to the `GRADLE_OPTS`

The gradle daemon is the one that gets the shutdown signal, not the Java process. Since Java never gets it, the InterMine shutdown hook never gets triggered and the database connections never get closed. I don't know why Gradle isn't passing the shutdown signal along. 

Getting rid of the daemon sees everything work as expected. There are speed penalties I expect, but seems fine to me.

**Comment by JoeCarlson** [comment]
Julie,
I have been running with --no-daemon when I first saw the problem. I don't think running without a daemon is a sufficient workaround.
The issue is only apparent if you attempt to load many sources in one 'gradlew integrate' process. In my original bug report, I had suggested a simple repeat of the uniprot-malaria with dummy taxon id's. Depending on the value of maximum postgres connections and the connections in each pool (I have 100 and 20), the build fails after 5 sources.

**Comment by julie-sullivan** [comment]
As I understand it, here the database is added to the shutdown hook: [Database.java#L140](https://github.com/intermine/intermine/blob/dev/intermine/objectstore/src/main/java/org/intermine/sql/Database.java#L140)

The when the thread or process is through the shutdown signal gets sent and the database is closed. The helpful gradle deamons prevent this.

For the `integrate` task, @danielabutano do we even handle multiple sources with the `integrate` command. I believe not -- which was the original reason for the `project_build` script! 

However, I think that closing the databases after use will be problematic as we reuse the connections. Which is why it's not done that way now. (I assume!)

@sergiocontrino maybe your input too? What do you think?

**Comment by sergiocontrino** [comment]
just an aside, i would try a lower number of connections for the pool, which is potentially high. this could be an interesting read
https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing

**Comment by JoeCarlson** [comment]
Hi Sergio, Adjusting the number of connections in the pool is important, but I don't think it'll be a good long term solution. My current build is ~ 400 data sources and I'll run into the problem again unless I really open up the max number of allowed connections in the server.
This is an issue that Sam and I had both noticed in the past. For me, I had a problem in the old build system where do-sources in postprocessing would run out of connections and fail. This is not one that can be fixed by using project_build.

**Pull request closed without merging**
