### PR TITLE
Remove Phenotype, it's not in the core model and has conflicting key …

### PR DESCRIPTION
**Pull request by sammyjava**
…defined here.

So as far as I can tell, the core model does not include Phenotype. This key definition conflicts with the Phenotype that I've defined in the soon-to-be-proposed-for-the-core GWAS model. So I've removed it, since it was breaking my loaders.

### CODE REVIEW

**Comment by julie-sullivan** [comment]
@sammyjava can you remerge dev into your branch? I broke a test.

**Comment by sammyjava** [comment]
Done, do I need to initiate the PR again?

**Comment by julie-sullivan** [comment]
Can you copy this change too: https://github.com/intermine/intermine/commit/f079ea235dea459767fdd3043187298cc5dfced3

Basically our tests rely on maps being ordered. Of course maps are not ordered but the results will be the same. Unless something changes. (Dumb I know). This test is failing because the results are out of order. If you renumber them, the tests will pass, and then I can merge this pull request.

**Comment by sammyjava** [comment]
Done, do I need a new PR as well?

**Comment by julie-sullivan** [comment]
> Done, do I need a new PR as well?
no! the PR updates automagically

**Comment by sammyjava** [comment]
Good to know, so a PR always reflects the current state of the source repo/branch. I did not know that! Key Fact.

**Comment by julie-sullivan** [comment]
and don't tell Yo I used the word "automagically". I promised her I would stop.

**Comment by sammyjava** [comment]
That explains why you can't do multiple PRs from a given repo/branch, which confused me before.

**Comment by sammyjava** [comment]
"automagically" is an actual tech term. It's in the tech dictionary. It's different from "automatic." An automatic door is not automagic.

**Pull request merged**
