### PR TITLE
Template tags added to JSON

### PR DESCRIPTION
**Pull request by julie-sullivan**
I've updated the `/templates` endpoint to include global tags. 

```
{"templates":[
{"tags":["im:aspect:Genes","im:public","monkey"],"authorized":false,"title":"All genes in organism --> All chromosomal locations.","description":"For a specified organism, show the chromosomal location and sequence length for all genes.","query":"{\"model\":{\"name\":\"genomic\"},\"title\":\"All genes in organism --> All chromosomal locations.\",\"description\":\"For a specified organism, show the chromosomal location and sequence length for all genes.\",\"select\":[\"Gene.chromosome.primaryIdentifier\",\"Gene.chromosomeLocation.strand\",\"Gene.chromosomeLocation.start\",\"Gene.chromosomeLocation.end\",\"Gene.length\",\"Gene.symbol\",\"Gene.secondaryIdentifier\"],\"name\":\"AllGene_Chromosome\",\"comment\":\"\",\"orderBy\":[{\"Gene.chromosome.primaryIdentifier\":\"ASC\"}],\"where\":[{\"path\":\"Gene.organism.name\",\"op\":\"=\",\"code\":\"A\",\"editable\":true,\"switchable\":false,\"switched\":\"LOCKED\",\"value\":\"Drosophila melanogaster\"}]}","name":"AllGene_Chromosome"}
```

Refs #1154

### CODE REVIEW

**Comment by julie-sullivan** [comment]
@justinccdev @sergiocontrino Maybe we could do a code review for this. The getTags() method is deprecated and I don't know why. There are lots of ways to get tags for lists and templates, my way might not be the best.

**Comment by justinccdev** [comment]
This is working code?

**Comment by justinccdev** [comment]
By visual inspection, I suspect that JSONTemplateFormatter.templateToMap() has a bug in commit 0b76303.  I don't believe the line 

```
boolean belongsToMe = templateMap == profile.getSavedTemplates().get(template.getName())
```

will ever return true because the objects being compared are not of the same class.

**Comment by justinccdev** [comment]
On discussion, this code wasn't used in the end so that comment can be ignored.

**Pull request closed without merging**
