### PR TITLE
Add List.ID to all end points

### PR DESCRIPTION
**Pull request by julie-sullivan**
Add internal InterMine ID to list attributes output in web services.

Refs #1669

### CODE REVIEW

**Comment by julie-sullivan** [comment]
@joshkh @yochannah Can you look at this too? 

```
  2) Query#appendToList target: String "before all" hook:

     Error: Could not parse response to POST http://localhost:8080/intermine-demo/service/query/append/tolist: "{

131

,"executionTime":"2017.09.11 09:01::47","wasSuccessful":true,"error":null,"statusCode":200}" (200: SyntaxError: Unexpected number in JSON at position 2)
```

Python client is also failing:

```
ERROR: test_appending_collection_of_lists (tests.live_lists.LiveListTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/julie-sullivan/intermine/client/tests/live_lists.py", line 400, in test_appending_collection_of_lists

    listA += [listA, listB, listC]

  File "/home/travis/build/julie-sullivan/intermine/client/intermine/lists/list.py", line 286, in __iadd__

    return self.append(other)

  File "/home/travis/build/julie-sullivan/intermine/client/intermine/lists/list.py", line 326, in append

    return self._do_append(appendix)

  File "/home/travis/build/julie-sullivan/intermine/client/intermine/lists/list.py", line 301, in _do_append

    content = self._manager._get_listable_query(content)

  File "/home/travis/build/julie-sullivan/intermine/client/intermine/lists/listmanager.py", line 145, in _get_listable_query

    q = queryable.to_query()

AttributeError: 'list' object has no attribute 'to_query'
```

I'll look at that one.

**Comment by justinccdev** [comment]
The problem is not with the Python client but that the list creation JSON response is now malformed.  It is now:

```
{
10
,"executionTime":"2017.09.21 12:06::15","wasSuccessful":true,"error":null,"statusCode":200}
```

Note the 10 stuck there on its own, which I'm guessing is the added ID.

**Comment by justinccdev** [comment]
In fact, you can see this is the problem that the Javascript code is reporting directly.  If you want to run the Python tests against the testmodel server, you can do download the latest python client from Github (I just fixed a few defaults) and run the command

```
python setup.py livetest
```

**Comment by julie-sullivan** [comment]
@justinccdev the 10 is the size I believe, and that's not the results i get from making the request directly.

**Comment by justinccdev** [comment]
Looking at the existing dev branch where the Python tests pass, the response is

```
{"listName":"my_list_1","listSize":
10
,"executionTime":"2017.09.21 12:23::53","wasSuccessful":true,"error":null,"statusCode":200}
```

So it looks like your change is somehow obliterating the first part (which I would suspect is a problem in our horrible JSON generation code).  This is a print out of the raw response Python is getting back before any processing.  When you execute directly, what JSON response do you see?

**Comment by julie-sullivan** [comment]
Request:

```
beta.flymine.org/beta/service/query/tolist?query=%3Cquery%20model%3D%22genomic%22%20view%3D%22Gene.id%22%20%3E%0A%20%20%3Cconstraint%20path%3D%22Gene.length%22%20op%3D%22%26lt%3B%22%20value%3D%2250%22%20code%3D%22A%22%20%2F%3E%0A%3C%2Fquery%3E&token=MY-SECRET-TOKEN
```

The query, it has 57 results:

```
<query model="genomic" view="Gene.id" >
  <constraint path="Gene.length" op="&lt;" value="50" code="A" />
</query>

```

Response:

```
{"listId":179000000,"listName":"new_list_3","listSize":
57
,"executionTime":"2017.09.21 13:01::22","wasSuccessful":true,"error":null,"statusCode":200}
```

**Comment by justinccdev** [comment]
This might be a failure specific to appending - all the Python tests that fail are append tests, other list query tests are fine.

**Comment by justinccdev** [comment]
I can confirm that the Python tests now pass.

**Comment by joshkh** [comment]
### Tests ###


Lists used for testing:

* 4genes `(eve, thor, zen, mad)`
* 1eve `(eve)`
* 1thor `(thor)`

```
Union: http://beta.flymine.org/beta/service/lists/union

Params:

lists: 1eve
lists: 1thor
name: union
format: json

Response:

{"listId":181000009,"listName":"union","type":"Gene","listSize":2,"executionTime":"2017.09.27 15:55::06","wasSuccessful":true,"error":null,"statusCode":200}
```

```
Intersect: http://beta.flymine.org/beta/service/lists/intersect

Params:

lists: 4genes
lists: 1thor
name: intersected
format: json

Response:

{"listId":181000012,"listName":"intersected","type":"Gene","listSize":1,"executionTime":"2017.09.27 15:59::54","wasSuccessful":true,"error":null,"statusCode":200}
```

```
Difference: http://beta.flymine.org/beta/service/lists/diff

Params:

lists: 4genes
lists: 1thor
name: differenced
format: json

Response:

{"listId":181000011,"listName":"differenced","type":"Gene","listSize":3,"executionTime":"2017.09.27 15:58::20","wasSuccessful":true,"error":null,"statusCode":200}
```

```
Subtraction: http://beta.flymine.org/beta/service/lists/subtract

Params:

references: 4genes
subtract: 1eve
name: newlist
format: json

Response

{"listId":181000008,"listName":"newlist","type":"Gene","listSize":3,"executionTime":"2017.09.27 15:51::45","wasSuccessful":true,"error":null,"statusCode":200}
```

**Pull request merged**
