### PR TITLE
tomcat 8.5 fix

### PR DESCRIPTION
**Pull request by justinccdev**

### CODE REVIEW

**Comment by justinccdev** [comment]
Don't test yet, I forgot there was that other pipe problem as well

**Comment by justinccdev** [comment]
Okay, review/test when ready

**Comment by julie-sullivan** [comment]
beta FlyMine is using tomcat 8.5 on @justinccdev's branch and everything, including the pipes, looks correct.

**Comment by justinccdev** [comment]
Things appear to be working under Tomcat 9 as well, at least in 9.0.0.M20.

**Pull request merged**
